In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)


df_artists = pd.read_csv('df_artists.csv')
df_songs   = pd.read_csv('df_songs.csv')
df_albums  = pd.read_csv('df_albums.csv')

print(f"df_artists: {df_artists.shape}")
print(f"df_songs:   {df_songs.shape}")
print(f"df_albums:  {df_albums.shape}")

df_kang_data_w_spotify = pd.read_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/kang_data_w_spotify.csv')
print(f"df_kang_data_w_spotify: {df_kang_data_w_spotify.shape}")

df_artists: (14226, 72)
df_songs:   (5099, 35)
df_albums:  (4569, 35)
df_kang_data_w_spotify: (22517, 7)

,id,name,isdone,spotifyid,genres,popularity,followers
0,600808,Drake,True,3TVXtAsR1Inumwj472S9r4,"['canadian hip hop', 'canadian pop', 'hip hop'...",98.0,61377383.0
1,706819,Ed Sheeran,True,6eUKZXaKkcviH0Ku9w2n3V,"['pop', 'uk pop']",95.0,93327682.0
2,823336,Ariana Grande,True,66CXWjxzNUsdJxJ2JdwvnR,"['dance pop', 'pop']",93.0,76626333.0
3,1492430,Bad Bunny,True,4q3ewBCX7sLwd24euuV69X,"['latin', 'reggaeton', 'trap latino']",100.0,44516743.0
4,796889,The Weeknd,True,1Xyo4u8uXC1ZmMpatF05PJ,"['canadian contemporary r&b', 'canadian pop', ...",98.0,42275433.0

In [ ]:
df_artists.head()

,performer_normalized,performer,first_song_year,first_album_year,years_active_on_charts,total_charting_songs,total_charting_albums,#1_hit_song_count,#1_hit_album_count,top_10_song_count,top_10_album_count,highest_charting_song_name,highest_charting_song_position,first_charting_song_name,first_charting_song_position,first_charting_song_duration,highest_charting_album_name,highest_charting_album_position,first_charting_album_name,first_charting_album_position,first_charting_album_duration,genre_tags_musicbrainz,first_year_on_chart_songs,first_year_top_10_songs,first_year_num1_songs,first_year_on_chart_albums,first_year_top_10_albums,first_year_num1_albums,aggregate_labels,first_top_10_song_#_of_connected_artists_to_labels_single_year,first_top_10_song_#_of_connected_artists_to_labels_past_5_years,first_top_10_song_total_power_of_connected_artists_to_labels_single_year,first_top_10_song_total_power_of_connected_artists_to_labels_past_5_years,first_top_10_song_#_of_connected_artists_to_big3_single_year,first_top_10_song_#_of_connected_artists_to_big3_past_5_years,first_top_10_song_total_power_of_connected_artists_to_big3_single_year,first_top_10_song_total_power_of_connected_artists_to_big3_past_5_years,first_top_10_hit_song_genre_tags,first_top_10_hit_album_genre_tags,genre_tags_through_first_top_10_hit,major_genre_categories_through_first_top_10_hit,#_of_major_genre_categories_through_first_top_10_hit,top_10_1hit_wonder_song,top_10_1hit_wonder_album,top_10_hitmaker_songs,top_10_hitmaker_albums,musicbrainz_artist_id,musicbrainz_mbid,major_genre_category,#_of_genres,degree_centrality_top10_yearly,degree_centrality_firstsong_yearly,degree_centrality_top10_rolling10,degree_centrality_firstsong_rolling10,closeness_centrality_top10_yearly,closeness_centrality_firstsong_yearly,closeness_centrality_top10_rolling10,closeness_centrality_firstsong_rolling10,harmonic_closeness_centrality_top10_yearly,harmonic_closeness_centrality_firstsong_yearly,harmonic_closeness_centrality_top10_rolling10,harmonic_closeness_centrality_firstsong_rolling10,betweenness_centrality_top10_yearly,betweenness_centrality_firstsong_yearly,betweenness_centrality_top10_rolling10,betweenness_centrality_firstsong_rolling10,eigenvector_centrality_top10_yearly,eigenvector_centrality_firstsong_yearly,eigenvector_centrality_top10_rolling10,eigenvector_centrality_firstsong_rolling10,power_of_connected_artists_at_first_song_year,power_of_connected_artists_at_first_top10_year
0,!!! (chk chk chk),!!! (Chk Chk Chk),NaN,2007.0,2007-2007,0,1,0,0,0,0,NaN,0,NaN,0,0,Myth Takes,195,Myth Takes,195,1,NaN,NaN,NaN,NaN,2007.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,False,False,False,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""groove"" holmes","""Groove"" Holmes",1966.0,NaN,1966-1966,2,0,0,0,0,0,Misty,44,Misty,44,11,NaN,0,NaN,0,0,NaN,1966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,False,False,False,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"""little"" jimmy dickens","""Little"" Jimmy Dickens",1965.0,NaN,1965-1965,1,0,0,0,0,0,May The Bird Of Paradise Fly Up Your Nose,15,May The Bird Of Paradise Fly Up Your Nose,15,10,NaN,0,NaN,0,0,NaN,1965.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,False,False,False,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""pookie"" hudson","""Pookie"" Hudson",1963.0,NaN,1963-1963,1,0,0,0,0,0,I Know I Know,96,I Know I Know,96,1,NaN,0,NaN,0,0,NaN,1963.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,False,False,False,False,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"""weird al"" yankovic","""Weird Al"" Yankovic",1983.0,NaN,1983-2014,11,0,0,0,1,0,White & Nerdy,9,Ricky,63,8,NaN,0,NaN,0,0,NaN,1983.0,2006.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,True,False,False,False,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_post2000_top10 = df_artists[
    (df_artists['first_year_top_10_songs'] >= 2000) &
    (df_artists['top_10_song_count'] > 0)
]

missing_post2000 = df_post2000_top10['musicbrainz_artist_id'].isna().sum()
total_post2000   = len(df_post2000_top10)

missing_all = df_artists['musicbrainz_artist_id'].isna().sum()
total_all   = len(df_artists)

print("All artists:")
print(f"  Total:   {total_all}")
print(f"  Missing: {missing_all} ({missing_all/total_all*100:.1f}%)")
print(f"  Have ID: {total_all - missing_all} ({(total_all-missing_all)/total_all*100:.1f}%)")

print("\nPost-2000 top 10 artists:")
print(f"  Total:   {total_post2000}")
print(f"  Missing: {missing_post2000} ({missing_post2000/total_post2000*100:.1f}%)")
print(f"  Have ID: {total_post2000 - missing_post2000} ({(total_post2000-missing_post2000)/total_post2000*100:.1f}%)")

All artists:
  Total:   14226
  Missing: 2662 (18.7%)
  Have ID: 11564 (81.3%)

Post-2000 top 10 artists:
  Total:   639
  Missing: 105 (16.4%)
  Have ID: 534 (83.6%)

In [8]:
missing_artists = df_post2000_top10[
    df_post2000_top10['musicbrainz_artist_id'].isna()
]['performer_normalized'].sort_values().tolist()

print(f"{len(missing_artists)} artists missing musicbrainz_artist_id:\n")
for name in missing_artists:
    print(f"  {name}")

105 artists missing musicbrainz_artist_id:

  "weird al" yankovic
  & jack harlow
  50 cent feat. mobb deep
  alex band or chad kroeger
  american idol finalists
  anderson .paak)
  andrew seeley
  ariana grande feat. doja cat
  beyonce
  beyonce knowles
  brian & brandon casey
  cam'ron
  carolina gaitan
  cataracs & dev
  ciara & fat man scoop
  colby o'donis
  coldplay x bts
  d.r.a.m.
  dixie chicks
  dj sammy & yanou
  eden's crush
  encanto cast
  eslabon armado
  far*east movement
  fun.
  g-eazy
  g-eazy x bebe rexha
  high school musical 2 cast
  huntr/x: ejae
  irv gotti presents the inc.
  j balvin & willy william
  j-kwon
  j. weav
  ja rule, ashanti, charli baltimore & vita
  jaden smith
  janelle monae
  jawsh 685 x jason derulo
  jay z kanye west
  jay-z + alicia keys
  jay-z + mr. hudson
  jhay cortez
  johnta austin
  jordin sparks duet
  juelz santana, freekey zekey & toya
  juice wrld x marshmello
  kanye west
  karol g x shakira
  ke$ha
  kevin woo
  kygo x selena gomez
  kyjuan, ali & murphy lee
  lady antebellum
  lauren bennett & goonrock
  lil nas
  lil peanut & charlay
  lil wayne & french montana or too $hort or tyga
  lil' flip
  lil' kim
  lil' mo & vita
  lil' phat & lil' boosie
  lil' romeo
  loon, mario winans & tammy ruggeri
  ludacris & dj frank e
  machine gun kelly x camila cabello
  missy elliott & lil kim
  mystikal & infamous 2.0
  nat "king" cole
  ne-yo
  ne-yo, afrojack & nayer
  o-town
  oliver anthony music
  olivia o'brien
  paul wall, ali & gipp
  pharrell & uncle charlie wilson
  plain white t's
  s club 7
  sage the gemini & lookas
  saja boys: andrew choi
  samuil lee
  sean paul feat. keyshia cole
  sean paul of the youngbloodz
  shaggy feat. ricardo "rikrok" ducent
  sheryl crow or allison moorer
  silento
  silk sonic (bruno mars
  soulja boy tell 'em
  soulja boy tell'em
  styles p.
  t-pain
  t.i. + pharrell
  tamia or ashanti
  the all-american rejects
  the black eyed peas
  the flipmode squad
  the scotts, travis scott & kid cudi
  tony! toni! tone!
  vanessa anne hudgens
  wizkid & kyla
  wynter
  yael naim
  ying yang twins & mr. collipark
  young jeezy
  zayn / taylor swift
  ¥$: kanye west
  ¥$: ye

In [19]:
import subprocess

drake_uuid = '9fff2f8a-21e6-47de-a2b8-7f449929d43f'
artist_path = '/Users/jamesemcnally/musicbrainz_data/mbdump/artist'

result = subprocess.run(
    ['grep', drake_uuid, artist_path],
    capture_output=True, text=True
)
print(result.stdout)

600808	9fff2f8a-21e6-47de-a2b8-7f449929d43f	Drake	Drake	1986	10	24	\N	\N	\N	1	38	1	Canadian rapper	0	2026-01-11 21:00:33.515863+00	f	5076	\N

In [23]:
# Rename column
df_artists = df_artists.rename(columns={'performer_normalized': 'name'})

# Fix Drake's musicbrainz_artist_id and mbid
df_artists.loc[df_artists['name'] == 'Drake', 'musicbrainz_artist_id'] = 600808
df_artists.loc[df_artists['name'] == 'Drake', 'mbid'] = '9fff2f8a-21e6-47de-a2b8-7f449929d43f'

# Verify
print(df_artists[df_artists['name'] == 'Drake'][['name', 'musicbrainz_artist_id', 'mbid']])

# Save
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

Empty DataFrame
Columns: [name, musicbrainz_artist_id, mbid]
Index: []
Saved.

In [28]:
df_artists.loc[df_artists['name'] == 'drake', 'musicbrainz_artist_id'] = 600808
df_artists.loc[df_artists['name'] == 'drake', 'musicbrainz_mbid'] = '9fff2f8a-21e6-47de-a2b8-7f449929d43f'
df_artists.loc[df_artists['name'] == 'drake', 'mbid'] = '9fff2f8a-21e6-47de-a2b8-7f449929d43f'

# Verify
print(df_artists[df_artists['name'] == 'drake'][['name', 'musicbrainz_artist_id', 'musicbrainz_mbid', 'mbid']])

# Save
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

       name  musicbrainz_artist_id                      musicbrainz_mbid  \
3522  drake               600808.0  9fff2f8a-21e6-47de-a2b8-7f449929d43f

                                      mbid
3522  9fff2f8a-21e6-47de-a2b8-7f449929d43f
Saved.

In [30]:
# Merge on artist name (both lowercased for matching)
kang_lookup = df_kang_data_w_spotify[['name', 'id']].copy()
kang_lookup['name_lower'] = kang_lookup['name'].str.lower().str.strip()

df_check = df_artists[['name', 'musicbrainz_artist_id']].copy()
df_check['name_lower'] = df_check['name'].str.lower().str.strip()

merged = df_check.merge(kang_lookup, on='name_lower', suffixes=('_ours', '_kang'))

# Flag mismatches
merged['match'] = merged['musicbrainz_artist_id'].astype('Int64') == merged['id'].astype('Int64')
mismatches = merged[~merged['match']]

print(f"Total matched artists: {len(merged)}")
print(f"Mismatches: {len(mismatches)}")
print(mismatches[['name_lower', 'musicbrainz_artist_id', 'id']].to_string())

Total matched artists: 3454
Mismatches: 605
                 name_lower  musicbrainz_artist_id       id
1               $uicideboy$              2805605.0  1242195
13                     2pac              2418574.0      163
19                       3t              2457950.0    15127
39                  aaliyah              1585341.0      358
47                      ace              2740540.0    37467
56              adam levine              2872763.0   309381
57                    adele               343673.0   497084
62                      afi              1951807.0    11170
64               aftershock              1236901.0  1914097
66                    ahmad                61330.0  1069772
69                      air              2353616.0   419866
70                      air              2353616.0      911
71                      ajr              2998051.0   745888
78                  alabama              2067546.0     9298
79             alan jackson               987264.0     1830
81              alan walker              1595910.0  1313031
86              albert king              2025700.0    21320
93               alex faith               822332.0   949987
94                   alex g               464435.0  1034607
110            all time low              2802268.0   232670
113              alphaville              1351064.0     2926
120                 america              1950882.0     2715
145              andy pratt              1503167.0   129376
146           andy williams               616257.0    32737
147                   angel              2015451.0   773582
164        anthony hamilton              1326568.0   136446
166        anthony phillips              1733643.0    38396
167                 anthrax              2048503.0     9125
172                   april              1395510.0  1321720
181                  arkade              1117236.0  1997712
186                 ashanti               569942.0    41057
187                    ashe              1959135.0  1541463
193                    asia              1580722.0     2778
196                   aswad              2773387.0    38526
200              atmosphere              1235852.0     7872
205                  aurora               244616.0  1216723
206                  aurora               244616.0   244623
209                  avalon               348910.0   766752
210                   avant              1939212.0    20487
218                  azteca              2098125.0  1982751
221                   b.o.b              2075237.0   596411
224                babyface              1311651.0    11819
235                   bakar               421878.0  1870771
239                   banks              2666755.0   975366
247             barry white              2786818.0     1127
248                     bas               601297.0  1125382
259                    beam              2304563.0  1541051
268                  beirut               838226.0   350267
272                   belly                 1083.0   456908
273                     ben              2548857.0  1721254
278              ben harper              2633219.0   134858
286            benny blanco              1358963.0   629401
287           benny goodman              2133999.0     4473
289                  berlin              2060570.0      393
299                     bia              2927266.0  1383395
305                   big l               752634.0    36964
313                 bigbang                47598.0   527153
315                   bilal               455288.0    46618
325            billy childs               471804.0     5347
332              billy paul               726048.0    12725
340                 birdman               445483.0   246274
348               black box               917740.0    12543
350              black lips              2186897.0   325361
351              black midi              1751819.0  1673338
365                   blaze              3103398.0    31728
372                 blondie              2136054.0      488
374            blood orange              1876292.0   820845
376                    blue              2761207.0     6519
381                     boa               849285.0     9496
385               bob james               921508.0     3222
391          bobby caldwell               558860.0    37279
403                   bones              1871454.0  1036076
409                    bono              1995451.0    35575
410                  bonobo               444337.0    24146
414                  boston              2460525.0      183
425                  brando              1604788.0  1695221
429                  brandy                 9341.0   141191
447               brian may               322217.0    22918
450            brian wilson              1675946.0     9350
461                  brooks               126072.0  1494212
473                      bt              1877152.0      239
487                    bush              2977138.0       22
493                    cage              3029966.0    52924
500           calvin harris              1244091.0   204321
501                     cam              2873305.0  1238179
502                   cameo              1837388.0     9344
503                  camila              2466918.0   382866
505                  camilo              2184382.0   771929
512                   canon               522729.0   929698
518                 caribou              2891274.0   235523
519             carl thomas              1857678.0    11227
528                 carnage              1614760.0   988437
534                    case              3149052.0     2882
535            casey abrams              2136512.0   298333
541                    cast              2812391.0    10718
543             cat stevens              2360403.0  1220000
556          changing faces              1255916.0    22444
560             charles fox              2840998.0   175195
582                 chicago               237226.0     2726
584                   chico               479880.0  1132652
592                   chinx              2003372.0  1257035
594             chris brown              1338343.0   240486
597              chris lane               467570.0  1317654
598            chris martin              2477817.0    83943
601         chris stapleton               951030.0   951571
627              city girls              1847860.0  1593507
629                      cj              2450770.0  2039270
630                      cl               727030.0   883896
638               cleopatra              1281157.0    11290
639                  clever               559925.0  1789872
643                  clutch              1515646.0     1871
646             code orange              1938296.0   897902
651           cold war kids              2033519.0   332417
663                converge              1741310.0     6060
678                 cracker              2835928.0     1092
682             crazy horse              2001653.0    74236
683                   cream              2703499.0     1435
688                   crush              2275479.0  1131831
718           daniel caesar              3163249.0  1165290
722             danny brown              1365976.0   644166
724                   dante               388756.0   915590
725            dante thomas              2813956.0    31466
728              dark angel              2930364.0    36610
733                daughter              2784567.0   818151
734                    dave              2036710.0  1416329
735              dave alvin               340402.0    48309
744              dave mason              2864444.0    37413
745           dave matthews              1232245.0   115893
748            dave stewart              1994337.0    24089
760            david foster               640564.0    41326
763              david gray               701477.0     1770
766              david hill              2403089.0   177385
773                    dawn              2430285.0  1417549
774                    daya              2983974.0  1279068
780           dead or alive              3062165.0      351
799                    deja               862461.0  1903799
814               destroyer              1985061.0    90283
815                     dev              1619562.0   773065
820                    devo               868017.0     1166
827                   diddy                65660.0   167512
828                    dido              2642032.0     1949
831                  diesel              2441775.0    65221
832                   dijon               662285.0  1866293
840                     dio               483466.0     1443
841                    dion               647225.0    16437
848              disclosure              1270844.0   859924
849               disturbed               793682.0      244
850                  divine              1429518.0  1901426
858               dj shadow              2287816.0    10230
859                dj snake              1839685.0   923140
862                     dna              1866362.0   114708
869                 domingo               550840.0   303625
874                   don q              2539144.0   378628
881            donna summer               236439.0      792
884                 donovan              2418268.0     4690
888                   doves              2701657.0    22303
892                dr. john               532332.0     6436
896                   drama              1071500.0  1900449
898                   dream              1937907.0  2116044
899                   dream              1937907.0   259886
904                     drs              2521504.0   536617
913                    dvsn              2999013.0  1348182
921              ed sheeran               946348.0   706819
922                   eddie              1274249.0  1491510
926            eddie murphy              2095431.0    15991
930                    eden              3069181.0  1356579
931                    eden              3069181.0  1926821
940            elephant man              1493852.0    20638
956                  emilia              2421055.0  1877396
958                  eminem              2316009.0      946
964   engelbert humperdinck               323769.0    43566
966                  enigma               828478.0      116
970                   epica               250508.0   107173
978            eric johnson               360718.0    37448
988                 esquire              2995335.0  1035143
997                     eve              1819048.0    11664
998                     eve              1819048.0  1450060
999                     eve              1819048.0  1981344
1000               everlast              2794072.0    23953
1003                  exile               481489.0  1882202
1004                    exo              1002807.0   883129
1005                 exodus              1481837.0    46213
1008           face to face              1235600.0      508
1009                  faces               796283.0    41129
1015                  falco              1690829.0     1147
1038                 filter              2566919.0     1007
1039                  finch               259332.0  1756503
1044                   five              1928117.0      800
1049                  flame              2720190.0   327753
1053               fletcher              1191817.0  1416745
1054                    flo              1454028.0  1783884
1066                  focus              2226979.0    37948
1075                    fox              1461294.0  1263078
1085           frank turner              1925241.0   313164
1099                freeway              1771203.0    67117
1112                 future               966592.0   800841
1114             futuristic              3031510.0  1102951
1120              gabrielle              2275045.0    10246
1126                garbage              1768914.0       37
1132             gary moore              1456225.0    10284
1134            gary wright              2158975.0     1740
1141                genesis              2993175.0     1492
1143         george clinton              2539654.0     1621
1146        george harrison               586253.0     2863
1147           george jones              2246595.0    15689
1149         george michael              2549388.0      142
1158                  ghost               732198.0   845194
1161                  giggs               764586.0   623242
1173          glen campbell              1436821.0      379
1175            glenn jones               711769.0    88616
1184                 gojira              2060106.0    92422
1185                 goldie               525559.0     2240
1187                  gomez              3114894.0     2131
1194                  grace              2821647.0    10673
1212                   grey              2932560.0  1307469
1221             gucci mane              2581473.0   255180
1225                   guru              2900791.0    11213
1256                  heart              2167143.0     1883
1258              heaven 17              2676720.0     5026
1262                 helmet              2449193.0     1646
1274                   hole              1247744.0       38
1275                  holly               882733.0  1508866
1299                   hyde              1001258.0   363593
1302           ian anderson              3091391.0     1518
1304             ian thomas                15944.0   998941
1311                   icon              2963898.0  2158651
1314                    idk              2474103.0  1270566
1323               immortal              2445027.0    33697
1328                incubus               771957.0      365
1336            iron maiden               413736.0    10042
1338                   isis              1514795.0    32304
1347             jack black              1118849.0     3957
1349           jack johnson              2729117.0    24227
1350             jack white               379191.0   145263
1361                  jaden              2698995.0   771896
1364              jake owen              1959552.0   374763
1365             jake scott              1428949.0  1962243
1370            james brown              1564558.0     1629
1375           james ingram              2636919.0     2807
1379         james morrison               375655.0    32583
1381           james taylor              1433672.0      127
1409               jay rock               538853.0   819032
1417                  jeezy              2888690.0   269029
1418              jeff beck              2290304.0     5033
1429             jelly roll               644324.0  1110058
1432        jennifer hanson              1536582.0    66359
1455                    jet              1305643.0    99187
1457                  jewel               611107.0      807
1459                    jid              1743479.0  1195592
1466              jim jones              1805784.0   194404
1467             jim reeves               963187.0    35917
1477             jimmy reed              1636847.0     3411
1478            jimmy smith              2163089.0    21043
1493          joe henderson               433030.0    31296
1499              joe walsh              1418358.0     1663
1506         john carpenter              2493691.0    52181
1516            john martin               237133.0   959369
1517             john mayer               276401.0    33563
1518        john mclaughlin              1014554.0    21982
1523              john rich               674340.0   212087
1527         john sebastian              2923669.0     3607
1531          john williams              2788464.0       94
1532          john williams              2788464.0   238569
1547                   jojo              2692561.0   161805
1548           jon anderson              1376414.0     5006
1563           jordan davis               701023.0  1591132
1566           josh kaufman              2288957.0  2152335
1570                journey              2786298.0     1658
1593                  julie              1943097.0  2215022
1599                 jungle              1136681.0  1045880
1604                justice              2178212.0   323048
1606           justin moore              1728706.0   636099
1610               juvenile               325885.0      377
1619                    kai              1186698.0   984798
1623                   kali              2848174.0   862749
1624                   kali              2848174.0  1012758
1625                   kali              2848174.0   812834
1630                   kano              1997039.0    66393
1655                     kb              2398433.0   908068
1656                     kc              3061269.0  2201830
1662         keith richards              1208409.0    24274
1676                kenny g              1556380.0     9491
1689                 khalid               816264.0  1445809
1693               kid rock              1430966.0     9760
1704                   king              2433948.0  2197225
1713                   kiss              1970351.0     3198
1715            knife party              1131266.0   251839
1737                 krokus              2090211.0    51208
1738                    ksi              1713735.0  1266982
1744                   kyle              2124679.0  1456211
1752                labelle               872482.0   240413
1754                 lady a              2984535.0   518096
1757              laid back              3073130.0    37624
1771              laura lee              1125523.0   121537
1780        laurie anderson               608560.0    10298
1784                    lay              2693564.0  1216964
1787                    lea              2826520.0  1314952
1797             lee morgan              2885221.0     9305
1805              lenny dee               648421.0    23262
1808         lenny williams               547811.0    64925
1818                 leroux              2830430.0   379738
1824                    lfo               625242.0    14767
1825         liam gallagher              1557146.0   118680
1829                 lights               116280.0   525804
1830                  lil b              2850872.0   787838
1860            linkin park              2818914.0    11330
1863                   lisa              2901418.0   711029
1869          little dragon              2929473.0   473170
1880                  lloyd               522790.0    30679
1883                  logic              2852276.0   942935
1892              los lobos              2304340.0     9579
1902                   love              2899804.0    20198
1905                    low               762468.0    32662
1906                     lp              1537035.0   182141
1909                 lucero              3012227.0   344348
1912                 lucius               306917.0   935325
1924                   lulu              1023825.0    40328
1939                 m.i.a.              2601561.0    64499
1940                  mabel              2298972.0  1276260
1944      machine gun kelly              1410916.0   830986
1945           machine head               262607.0     2075
1956                madness              3129818.0       85
1957                madonna              1690463.0       89
1963                  magoo               272574.0   124646
1970                 malice               712793.0  1374556
1974               mandrill               649035.0    38327
1976           manfred mann               387216.0      820
1981           marc anthony              1694909.0     1684
1984          marcus miller              1005859.0    35648
1997         marilyn manson                  187.0   255235
1999                 marina              2430288.0   596594

In [32]:
# Spot check a few well-known artists to confirm kang IDs are correct
spot_check = ['the beatles', 'nirvana', 'madonna', 'eminem', 'adele', 'eminem']
print(conflict_candidates[conflict_candidates['name_lower'].isin(spot_check)][
    ['name_lower', 'musicbrainz_artist_id', 'id']
])

       name_lower  musicbrainz_artist_id      id
57          adele               343673.0  497084
958        eminem              2316009.0     946
1957      madonna              1690463.0      89
2270      nirvana              1706467.0      54
2978  the beatles              2589354.0     303

In [35]:
# When we originally assigned MusicBrainz integer IDs to artists in df_artists, we used
# name-based matching against the MusicBrainz database. This introduced systematic errors:
# many common artist names (e.g. "The Beatles", "Nirvana", "Madonna", "Eminem") match
# multiple MusicBrainz entries, and our lookup frequently resolved to the wrong artist —
# often an obscure band or foreign artist who happened to share the name. For example:
#   - "The Beatles" → a 1960s Philadelphia doo-wop group (id=2589354) instead of the Fab Four (id=303)
#   - "Nirvana"     → a Croatian prog-rock band (id=1706467) instead of the US grunge band (id=54)
#   - "Madonna"     → a Lebanese singer (id=1690463) instead of the Queen of Pop (id=89)
#
# We corrected this by cross-referencing against the Kang et al. dataset, which contains
# verified MusicBrainz IDs for charting artists. A spot check against the local MusicBrainz
# database dump confirmed the Kang IDs are correct in every case. We apply those corrections
# here for all 564 unambiguous conflicts (cases where the name maps to exactly one Kang entry).

update_map = conflict_candidates.set_index('name_lower')['id'].to_dict()

df_artists['name_lower'] = df_artists['name'].str.lower().str.strip()
df_artists.loc[df_artists['name_lower'].isin(update_map), 'musicbrainz_artist_id'] = (
    df_artists.loc[df_artists['name_lower'].isin(update_map), 'name_lower'].map(update_map)
)
df_artists = df_artists.drop(columns=['name_lower'])

print(f"Updated {len(update_map)} artist IDs from kang dataset.")

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

Updated 564 artist IDs from kang dataset.
Saved.

In [37]:
fill_map = fill_candidates.set_index('name_lower')['id'].to_dict()

df_artists['name_lower'] = df_artists['name'].str.lower().str.strip()
df_artists.loc[df_artists['name_lower'].isin(fill_map), 'musicbrainz_artist_id'] = (
    df_artists.loc[df_artists['name_lower'].isin(fill_map), 'name_lower'].map(fill_map)
)
df_artists = df_artists.drop(columns=['name_lower'])

print(f"Filled {len(fill_map)} previously-null artist IDs from kang dataset.")
print(fill_candidates[['name_lower', 'id']].to_string())

Filled 18 previously-null artist IDs from kang dataset.
                 name_lower       id
34                a$ap ferg   838293
490                    c-bo    14586
593           chloe x halle  1291761
698         cyhi the prynce   726074
712           damian marley    51406
1109                   fun.   620911
1458            jhay cortez  1669383
1632             kanye west   127482
1673            kenny beats  1657929
2053  medeski martin & wood     9632
2060         meli'sa morgan   133468
2161                mos def     2212
2442          play-n-skillz   300423
2656               s club 7   584605
2737     sheku kanneh-mason  1496144
3049          the jackson 5    63498
3425              yung bleu  1594826
3445            zhavia ward  1660598

In [38]:
kang_lookup = df_kang_data_w_spotify[['name', 'id']].copy()
kang_lookup['name_lower'] = kang_lookup['name'].str.lower().str.strip()

df_check = df_artists[['name', 'musicbrainz_artist_id']].copy()
df_check['name_lower'] = df_check['name'].str.lower().str.strip()

merged = df_check.merge(kang_lookup, on='name_lower', suffixes=('_ours', '_kang'))
kang_name_counts = kang_lookup.groupby('name_lower')['id'].count().reset_index()
kang_name_counts.columns = ['name_lower', 'kang_name_count']
merged2 = merged.merge(kang_name_counts, on='name_lower')
merged2['match'] = merged2['musicbrainz_artist_id'].astype('Int64') == merged2['id'].astype('Int64')

fill_remaining = merged2[merged2['musicbrainz_artist_id'].isna() & (merged2['kang_name_count'] == 1)]
conflicts_remaining = merged2[merged2['musicbrainz_artist_id'].notna() & ~merged2['match'] & (merged2['kang_name_count'] == 1)]
ambiguous = merged2[merged2['kang_name_count'] > 1]

print(f"Remaining safe fills:  {len(fill_remaining)}")
print(f"Remaining conflicts:   {len(conflicts_remaining)}")
print(f"Ambiguous (multi-match): {len(ambiguous)}")

Remaining safe fills:  0
Remaining conflicts:   0
Ambiguous (multi-match): 52

In [39]:
total = len(df_artists)
missing = df_artists['musicbrainz_artist_id'].isna().sum()
print(f"Total artists: {total}")
print(f"Missing musicbrainz_artist_id: {missing} ({missing/total*100:.1f}%)")

# Break down by whether they had a top 10 hit
has_top10 = df_artists['top_10_song_count'] > 0
print(f"\nAmong top-10 artists: {df_artists[has_top10]['musicbrainz_artist_id'].isna().sum()} missing")
print(f"Among non-top-10 artists: {df_artists[~has_top10]['musicbrainz_artist_id'].isna().sum()} missing")

Total artists: 14226
Missing musicbrainz_artist_id: 2644 (18.6%)

Among top-10 artists: 375 missing
Among non-top-10 artists: 2269 missing

In [44]:
import re

def normalize_name(name):
    if not isinstance(name, str):
        return ''
    n = name.lower().strip()
    # Remove punctuation except letters, numbers, spaces
    n = re.sub(r"[\"'\.&,\-\(\)]", ' ', n)
    n = re.sub(r'\s+', ' ', n).strip()
    return n

# Flag artifact names
artifact_patterns = r'^(&|feat|ft\.?|w/|x |and )'
missing['is_artifact'] = missing['name'].str.lower().str.strip().str.match(artifact_patterns)

real_missing = missing[~missing['is_artifact']].copy()
real_missing['name_norm'] = real_missing['name'].apply(normalize_name)
df_mb['name_norm'] = df_mb['name'].apply(normalize_name)

print(f"Artifacts filtered out: {missing['is_artifact'].sum()}")
print(f"Real missing artists: {len(real_missing)}")

# Try normalized join
merged_norm = real_missing[['name', 'name_norm']].merge(
    df_mb[['id', 'name_norm', 'comment']],
    on='name_norm', how='left'
)
counts = merged_norm.groupby('name_norm')['id'].count().reset_index()
counts.columns = ['name_norm', 'mb_match_count']
merged_norm = merged_norm.merge(counts, on='name_norm')

safe_norm   = merged_norm[merged_norm['mb_match_count'] == 1].drop_duplicates('name_norm')
ambig_norm  = merged_norm[merged_norm['mb_match_count'] > 1]['name_norm'].nunique()
no_match    = merged_norm[merged_norm['id'].isna()]['name_norm'].nunique()

print(f"\nUnambiguous matches: {len(safe_norm)}")
print(f"Ambiguous (multiple): {ambig_norm}")
print(f"No match:            {no_match}")

Artifacts filtered out: 8
Real missing artists: 2636

Unambiguous matches: 93
Ambiguous (multiple): 16
No match:            2509

In [46]:
# For each of the 93 candidates, use the comment field as a tiebreaker
# Flag likely wrong matches based on suspicious comments

# Artists we can reasonably verify as correct (comment is NaN or plausible)
print(safe_norm[['name', 'id', 'comment']].to_string())

# Manually flag known bad matches based on comment review
bad_matches = {
    "'n sync", 'the black eyed peas', 'jay-z', 'hit-boy', 'j-hope',
    'j.i.d', 'ice-t', 'b-real', "lil'z", "t'pau", 'disco tex',
    'lenny b.', 'd-mob'
}

safe_norm['name_lower'] = safe_norm['name'].str.lower().str.strip()
verified = safe_norm[~safe_norm['name_lower'].isin(bad_matches)]
print(f"\nVerified safe matches after removing known bad ones: {len(verified)}")
print(verified[['name', 'id', 'comment']].to_string())

                               name         id                                                               comment
3                   "pookie" hudson   232958.0                                                                   NaN
6                               '68  2698113.0                                                                   NaN
7                           'n sync   526373.0                        US dance music duo Bryan Thompson & Paul Scott
18           100 proof aged in soul    38496.0                                                70s US funk/soul group
43                       a r rahman    36611.0                                                                   NaN
98                  anderson .paak)  1130852.0                                          American rapper and producer
150                          b-real  2377122.0                                      US rapper, member of Intoxicated
191                        becky g.   899493.0                                                       American singer
285                         boney m    11046.0                                                                   NaN
303                brenda k. starr)    97896.0                                                                   NaN
338                           bun-b   273194.0                                                                   NaN
341                       c company   323837.0                                                                   NaN
363               carl dobkins, jr.    96335.0                                                                   NaN
391                     chaka khan)     9346.0                                                                   NaN
467                           d-mob     7283.0                                 British DJ, producer, remixer and A&R
474                       d.l.byron   640456.0                                                                   NaN
477                  da' t.r.u.t.h.  2453156.0                                                                   NaN
498           daryl hall john oates    37921.0                                                                   NaN
512                  david t walker   200655.0                                                                   NaN
617                       disco tex   359326.0                              House artist, active since the mid-1990s
676                     drum corps.  1895791.0                                                                   NaN
701                   eddie levert)   260820.0                                                                   NaN
731                     elton john)      236.0                     English singer, songwriter, pianist, and composer
737                    encanto cast  3077062.0                                                   Cast from "Encanto"
842                         gary o'  2017760.0                                                                   NaN
910               hank williams jr.    21829.0                                                                   NaN
917              heavy d & the boyz    47072.0                                                                   NaN
947                         hit-boy   898319.0                                                         Japanese band
957                     houndmouth.   991343.0                                                                   NaN
970                  i the breather   778928.0                                                                   NaN
978                           ice-t  2571373.0                                                       Early 80s dance
992                 invent, animate  1148546.0                                                             metalcore
995            isley, jasper, isley    48088.0                                                                   NaN
1008                         j-hope  2068752.0                                                     English violinist
1011                      j. balvin   803820.0                                                                   NaN
1017                          j.i.d  1743477.0                                                             rock band
1021                  jacci mcghee)   166267.0                                                                   NaN
1039              jamie n commons &   645962.0                                                                   NaN
1052                          jay-z  2133824.0                             US hip-hop DJ and producer Jeremy Jackson
1149                          jon b    35887.0                                                                   NaN
1194                          k'jon  1356267.0                                                                   NaN
1207             karen clark-sheard   298584.0                                                         gospel singer
1209               karl hammel, jr.   184322.0                                                                   NaN
1239                  kenny rogers)     1119.0  US country singer, songwriter, actor, record producer & entrepreneur
1270                    kip winger)   160135.0                                                                   NaN
1289                      l.a. jets  2034101.0                                                                   NaN
1290                    l.a.boppers   147185.0                                                                   NaN
1291                    l.a.express   338777.0                                                                   NaN
1298                       la' chat   266918.0                                            US rapper Chastity Daniels
1313           lauren spencer-smith  2275267.0                                                                   NaN
1315    lawrence welk his orchestra   444026.0                                                                   NaN
1326                       lenny b.  2154641.0                                               German hip hop producer
1333                leslie odom jr.   964777.0                                                                   NaN
1364                     lil' duval   855038.0                                                                   NaN
1366                      lil' keke  3118664.0                                                  rapper from Georgia?
1378                     lil' wayne    57186.0                                                                   NaN
1380                          lil'z  2663054.0                                             Hip-Hop singer at Myanmar
1447               luis r conriquez  2365185.0                                                                   NaN
1461                           m83.    77161.0                                                                   NaN
1470                      mad'house  1516615.0                                                     US hip-hop artist
1559               midi maxi & efti   261331.0                                                                   NaN
1619                nat "king" cole    14410.0                                                                   NaN
1661                   nuttin' nyce  1315219.0                                                  Hip hop / Horrorcore
1672                       ol skool   218980.0                                                             R&B Group
1699               oscar toney, jr.   467904.0                                                                   NaN
1711                 ozzy osbourne)      188.0                                                                   NaN
1713                        p reign  1310142.0                                                                   NaN
1716                          p.f.m  3014539.0     alias for: Tadashi Sawashita, Masato Shimohashi, Shinji Kawashima
1720          parliament funkadelic   352228.0                                                                   NaN
1802                       pop-tops   133491.0                                                                   NaN
1806              pozo seco singers   148092.0                                                                   NaN
1823              public image ltd.    12434.0                                                                   NaN
1838             r.a the rugged man    77598.0                                                                   NaN
1903        robert maxwell his harp  3193135.0                                                                   NaN
1955          russell thompkins,jr.   739254.0                                                                   NaN
1956                         ruth b  1312914.0                                                                   NaN
1963                         s.m.v.   551869.0                       Stanley Clarke, Marcus Miller and Victor Wooten
2014                shanice wilson)  2451674.0                                                                   NaN
2017                    shaw-blades   967659.0                                              Tommy Shaw & Jack Blades
2023            shirley (& company)    38279.0                                                                   NaN
2109                 stealin horses   129447.0                                                                   NaN
2120  steve stevens atomic playboys   143124.0                                                                   NaN
2121                 steve wariner)    45143.0                                         American country music singer
2130                      styles p.    49634.0                                                 aka Styles of the LOX
2151                          t'pau  1807439.0                                             production music composer
2158                     t.d. jakes  2238310.0                                                                   NaN
2241            the black eyed peas  1228175.0                    obscure backing vocals for Potliquor in the 1970's
2242               the blackhearts)  1525533.0                                   wonderland & "flowers for tomorrow"
2244                the blue belles  1032771.0                                                                   NaN
2379                 the ly - dells   575807.0                                                                   NaN
2516                 the wild pair)   937308.0                                                                   NaN
2517                  the wild-cats  2264297.0                                                                   NaN
2568                     too $hort)     7028.0                                                                   NaN

Verified safe matches after removing known bad ones: 80
                               name         id                                                               comment
3                   "pookie" hudson   232958.0                                                                   NaN
6                               '68  2698113.0                                                                   NaN
18           100 proof aged in soul    38496.0                                                70s US funk/soul group
43                       a r rahman    36611.0                                                                   NaN
98                  anderson .paak)  1130852.0                                          American rapper and producer
191                        becky g.   899493.0                                                       American singer
285                         boney m    11046.0                                                                   NaN
303                brenda k. starr)    97896.0                                                                   NaN
338                           bun-b   273194.0                                                                   NaN
341                       c company   323837.0                                                                   NaN
363               carl dobkins, jr.    96335.0                                                                   NaN
391                     chaka khan)     9346.0                                                                   NaN
474                       d.l.byron   640456.0                                                                   NaN
477                  da' t.r.u.t.h.  2453156.0                                                                   NaN
498           daryl hall john oates    37921.0                                                                   NaN
512                  david t walker   200655.0                                                                   NaN
676                     drum corps.  1895791.0                                                                   NaN
701                   eddie levert)   260820.0                                                                   NaN
731                     elton john)      236.0                     English singer, songwriter, pianist, and composer
737                    encanto cast  3077062.0                                                   Cast from "Encanto"
842                         gary o'  2017760.0                                                                   NaN
910               hank williams jr.    21829.0                                                                   NaN
917              heavy d & the boyz    47072.0                                                                   NaN
957                     houndmouth.   991343.0                                                                   NaN
970                  i the breather   778928.0                                                                   NaN
992                 invent, animate  1148546.0                                                             metalcore
995            isley, jasper, isley    48088.0                                                                   NaN
1011                      j. balvin   803820.0                                                                   NaN
1021                  jacci mcghee)   166267.0                                                                   NaN
1039              jamie n commons &   645962.0                                                                   NaN
1149                          jon b    35887.0                                                                   NaN
1194                          k'jon  1356267.0                                                                   NaN
1207             karen clark-sheard   298584.0                                                         gospel singer
1209               karl hammel, jr.   184322.0                                                                   NaN
1239                  kenny rogers)     1119.0  US country singer, songwriter, actor, record producer & entrepreneur
1270                    kip winger)   160135.0                                                                   NaN
1289                      l.a. jets  2034101.0                                                                   NaN
1290                    l.a.boppers   147185.0                                                                   NaN
1291                    l.a.express   338777.0                                                                   NaN
1298                       la' chat   266918.0                                            US rapper Chastity Daniels
1313           lauren spencer-smith  2275267.0                                                                   NaN
1315    lawrence welk his orchestra   444026.0                                                                   NaN
1333                leslie odom jr.   964777.0                                                                   NaN
1364                     lil' duval   855038.0                                                                   NaN
1366                      lil' keke  3118664.0                                                  rapper from Georgia?
1378                     lil' wayne    57186.0                                                                   NaN
1447               luis r conriquez  2365185.0                                                                   NaN
1461                           m83.    77161.0                                                                   NaN
1470                      mad'house  1516615.0                                                     US hip-hop artist
1559               midi maxi & efti   261331.0                                                                   NaN
1619                nat "king" cole    14410.0                                                                   NaN
1661                   nuttin' nyce  1315219.0                                                  Hip hop / Horrorcore
1672                       ol skool   218980.0                                                             R&B Group
1699               oscar toney, jr.   467904.0                                                                   NaN
1711                 ozzy osbourne)      188.0                                                                   NaN
1713                        p reign  1310142.0                                                                   NaN
1716                          p.f.m  3014539.0     alias for: Tadashi Sawashita, Masato Shimohashi, Shinji Kawashima
1720          parliament funkadelic   352228.0                                                                   NaN
1802                       pop-tops   133491.0                                                                   NaN
1806              pozo seco singers   148092.0                                                                   NaN
1823              public image ltd.    12434.0                                                                   NaN
1838             r.a the rugged man    77598.0                                                                   NaN
1903        robert maxwell his harp  3193135.0                                                                   NaN
1955          russell thompkins,jr.   739254.0                                                                   NaN
1956                         ruth b  1312914.0                                                                   NaN
1963                         s.m.v.   551869.0                       Stanley Clarke, Marcus Miller and Victor Wooten
2014                shanice wilson)  2451674.0                                                                   NaN
2017                    shaw-blades   967659.0                                              Tommy Shaw & Jack Blades
2023            shirley (& company)    38279.0                                                                   NaN
2109                 stealin horses   129447.0                                                                   NaN
2120  steve stevens atomic playboys   143124.0                                                                   NaN
2121                 steve wariner)    45143.0                                         American country music singer
2130                      styles p.    49634.0                                                 aka Styles of the LOX
2158                     t.d. jakes  2238310.0                                                                   NaN
2242               the blackhearts)  1525533.0                                   wonderland & "flowers for tomorrow"

In [47]:
bad_matches = {
    "'n sync", 'the black eyed peas', 'jay-z', 'hit-boy', 'j-hope',
    'j.i.d', 'ice-t', 'b-real', "lil'z", "t'pau", 'disco tex',
    'lenny b.', 'd-mob', 'p.f.m', 'the blackhearts)', "lil' keke"
}

safe_norm['name_lower'] = safe_norm['name'].str.lower().str.strip()
verified = safe_norm[~safe_norm['name_lower'].isin(bad_matches)]
print(f"Applying {len(verified)} verified matches")

# Build update map and apply
update_map_norm = dict(zip(verified['name'].str.lower().str.strip(), verified['id']))
df_artists['name_lower'] = df_artists['name'].str.lower().str.strip()
df_artists.loc[
    df_artists['name_lower'].isin(update_map_norm) & df_artists['musicbrainz_artist_id'].isna(),
    'musicbrainz_artist_id'
] = df_artists.loc[
    df_artists['name_lower'].isin(update_map_norm) & df_artists['musicbrainz_artist_id'].isna(),
    'name_lower'
].map(update_map_norm)
df_artists = df_artists.drop(columns=['name_lower'])

# Verify and save
missing_after = df_artists['musicbrainz_artist_id'].isna().sum()
print(f"Missing IDs after update: {missing_after}")
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

Applying 77 verified matches
Missing IDs after update: 2567
Saved.

In [53]:
has_id = df_artists[df_artists['musicbrainz_artist_id'].notna()][['name', 'musicbrainz_artist_id']].copy()
has_id['musicbrainz_artist_id'] = has_id['musicbrainz_artist_id'].astype(int)

kang = df_kang_data_w_spotify[['id', 'name']].rename(columns={'name': 'kang_name'}).copy()
kang['kang_name_lower'] = kang['kang_name'].str.lower().str.strip()

merged = has_id.merge(kang, left_on='musicbrainz_artist_id', right_on='id', how='inner')
merged['name_lower'] = merged['name'].str.lower().str.strip()

mismatches = merged[merged['name_lower'] != merged['kang_name_lower']]
print(f"Artists with ID in both datasets: {len(merged)}")
print(f"Name mismatches: {len(mismatches)}")
print(mismatches[['name', 'kang_name', 'musicbrainz_artist_id']].to_string())

Artists with ID in both datasets: 3455
Name mismatches: 42
                       name                kang_name  musicbrainz_artist_id
32               a r rahman             A. R. Rahman                  36611
38                     a-ha                     a‐ha                    823
48                    ac/dc                     ACDC                   1352
118             amanda cook      Amanda Lindsey Cook                 163013
137         anderson .paak)           Anderson .Paak                1130852
268                becky g.                  Becky G                 899493
407                 boney m                 Boney M.                  11046
438        brenda k. starr)          Brenda K. Starr                  97896
487                   bun-b                    Bun B                 273194
558             chaka khan)               Chaka Khan                   9346
735   daryl hall john oates  Daryl Hall & John Oates                  37921
951             elton john)               Elton John                    236
1237      hank williams jr.       Hank Williams, Jr.                  21829
1256     heavy d & the boyz      Heavy D. & the Boyz                  47072
1342              j. balvin                 J Balvin                 803820
1345         jaci velasquez           Jaci Velásquez                   1706
1388      jamie n commons &          Jamie N Commons                 645962
1629     karen clark-sheard       Karen Clark Sheard                 298584
1668                  ken-y                    Ken‐Y                 731729
1677          kenny rogers)             Kenny Rogers                   1119
1692          kierra sheard       Kierra Kiki Sheard                 199670
1742           kxng crooked                Crooked I                 153124
1821        leslie odom jr.         Leslie Odom, Jr.                 964777
1841              lil poppa               Lil' Poppa                1876294
1852             lil' duval                Lil Duval                 855038
1853             lil' wayne                Lil Wayne                  57186
1879          little steven         Steven Van Zandt                 433395
1945                   m83.                      M83                  77161
2072    meshell ndegeocello     Me’Shell NdegéOcello                  30291
2081                    mgk        Machine Gun Kelly                 830986
2200        nat "king" cole            Nat King Cole                  14410
2327                outkast                 Outkastz                    525
2333         ozzy osbourne)            Ozzy Osbourne                    188
2484     r.a the rugged man      R.A. the Rugged Man                  77598
2618            ronnie wood                 Ron Wood                  53334
2646                 ruth b                  Ruth B.                1312914
2881              styles p.                 Styles P                  49634
2917                taeyang                       태양                 650037
3047           the jacksons            The Jackson 5                  63498
3221             too $hort)                Too $hort                   7028
3394                     ye               Kanye West                 127482
3449          zion & lennox                   Zion I                 157343

In [54]:
import subprocess
artist_path = '/Users/jamesemcnally/musicbrainz_data/mbdump/artist'

for mbid in [525, 157343]:
    result = subprocess.run(['grep', f'^{mbid}\t', artist_path], capture_output=True, text=True)
    fields = result.stdout.strip().split('\t')
    print(f"id={mbid}: name='{fields[2]}', comment='{fields[13]}'")

id=525: name='OutKast', comment=''
id=157343: name='Zion & Lennox', comment=''

In [55]:
import random

has_id = df_artists[df_artists['musicbrainz_artist_id'].notna()].copy()
has_id['musicbrainz_artist_id'] = has_id['musicbrainz_artist_id'].astype(int)

kang_ids = set(df_kang_data_w_spotify['id'].astype(int))
in_both = has_id[has_id['musicbrainz_artist_id'].isin(kang_ids)]

sample = in_both.sample(10)

kang_lookup = df_kang_data_w_spotify.set_index('id')['name']
for _, row in sample.iterrows():
    mbid = int(row['musicbrainz_artist_id'])
    print(f"ID {mbid:>8} | ours: {row['name']:<35} | kang: {kang_lookup[mbid]}")

ID    23980 | ours: grover washington, jr.              | kang: Grover Washington, Jr.
ID  1139485 | ours: zella day                           | kang: Zella Day
ID  1738026 | ours: lyanno                              | kang: Lyanno
ID     2829 | ours: sister sledge                       | kang: Sister Sledge
ID     1559 | ours: craig david                         | kang: Craig David
ID   353667 | ours: rick ross                           | kang: Rick Ross
ID    21671 | ours: marvin hamlisch                     | kang: Marvin Hamlisch
ID   218982 | ours: the diplomats                       | kang: The Diplomats
ID     3217 | ours: redman                              | kang: Redman
ID    32860 | ours: mobb deep                           | kang: Mobb Deep

In [56]:
# Step 1 & 4: merge spotify_id and genres from kang
kang_merge = df_kang_data_w_spotify[['id', 'spotifyid', 'genres']].copy()
kang_merge['id'] = kang_merge['id'].astype('Int64')
df_artists['musicbrainz_artist_id'] = df_artists['musicbrainz_artist_id'].astype('Int64')

df_artists = df_artists.merge(
    kang_merge.rename(columns={'spotifyid': 'spotify_id', 'genres': 'spotify_genres'}),
    left_on='musicbrainz_artist_id', right_on='id', how='left'
).drop(columns=['id'])

# Step 3: rename performer
df_artists = df_artists.rename(columns={'performer': 'performer_pre_normalized'})

# Step 5: drop centrality/network columns
cols_to_drop = [
    'degree_centrality_top10_yearly', 'degree_centrality_firstsong_yearly',
    'degree_centrality_top10_rolling10', 'degree_centrality_firstsong_rolling10',
    'closeness_centrality_top10_yearly', 'closeness_centrality_firstsong_yearly',
    'closeness_centrality_top10_rolling10', 'closeness_centrality_firstsong_rolling10',
    'harmonic_closeness_centrality_top10_yearly', 'harmonic_closeness_centrality_firstsong_yearly',
    'harmonic_closeness_centrality_top10_rolling10', 'harmonic_closeness_centrality_firstsong_rolling10',
    'betweenness_centrality_top10_yearly', 'betweenness_centrality_firstsong_yearly',
    'betweenness_centrality_top10_rolling10', 'betweenness_centrality_firstsong_rolling10',
    'eigenvector_centrality_top10_yearly', 'eigenvector_centrality_firstsong_yearly',
    'eigenvector_centrality_top10_rolling10', 'eigenvector_centrality_firstsong_rolling10',
    'power_of_connected_artists_at_first_song_year', 'power_of_connected_artists_at_first_top10_year'
]
cols_to_drop = [c for c in cols_to_drop if c in df_artists.columns]
df_artists = df_artists.drop(columns=cols_to_drop)

# Step 2: reorder columns — name, musicbrainz_artist_id, musicbrainz_mbid, spotify_id, performer_pre_normalized, then rest
priority = ['name', 'musicbrainz_artist_id', 'musicbrainz_mbid', 'spotify_id', 'performer_pre_normalized', 'spotify_genres']
remaining = [c for c in df_artists.columns if c not in priority]
df_artists = df_artists[priority + remaining]

print(df_artists.shape)
print(df_artists.columns.tolist()[:10])

(14226, 53)
['name', 'musicbrainz_artist_id', 'musicbrainz_mbid', 'spotify_id', 'performer_pre_normalized', 'spotify_genres', 'first_song_year', 'first_album_year', 'years_active_on_charts', 'total_charting_songs']

In [59]:
df_artists = df_artists.drop(columns=['mbid'])
print(df_artists.shape)

(14226, 52)

In [62]:
df_artists = df_artists.rename(columns={
    'major_genre_category': 'musicbrainz_major_genre_category',
    '#_of_genres': 'musicbrainz_#_of_genres'
})

# Move spotify_genres to last
cols = [c for c in df_artists.columns if c != 'spotify_genres'] + ['spotify_genres']
df_artists = df_artists[cols]

print(df_artists.columns.tolist())

['name', 'musicbrainz_artist_id', 'musicbrainz_mbid', 'spotify_id', 'performer_pre_normalized', 'first_song_year', 'first_album_year', 'years_active_on_charts', 'total_charting_songs', 'total_charting_albums', '#1_hit_song_count', '#1_hit_album_count', 'top_10_song_count', 'top_10_album_count', 'highest_charting_song_name', 'highest_charting_song_position', 'first_charting_song_name', 'first_charting_song_position', 'first_charting_song_duration', 'highest_charting_album_name', 'highest_charting_album_position', 'first_charting_album_name', 'first_charting_album_position', 'first_charting_album_duration', 'genre_tags_musicbrainz', 'first_year_on_chart_songs', 'first_year_top_10_songs', 'first_year_num1_songs', 'first_year_on_chart_albums', 'first_year_top_10_albums', 'first_year_num1_albums', 'aggregate_labels', 'first_top_10_song_#_of_connected_artists_to_labels_single_year', 'first_top_10_song_#_of_connected_artists_to_labels_past_5_years', 'first_top_10_song_total_power_of_connected_artists_to_labels_single_year', 'first_top_10_song_total_power_of_connected_artists_to_labels_past_5_years', 'first_top_10_song_#_of_connected_artists_to_big3_single_year', 'first_top_10_song_#_of_connected_artists_to_big3_past_5_years', 'first_top_10_song_total_power_of_connected_artists_to_big3_single_year', 'first_top_10_song_total_power_of_connected_artists_to_big3_past_5_years', 'first_top_10_hit_song_genre_tags', 'first_top_10_hit_album_genre_tags', 'genre_tags_through_first_top_10_hit', 'major_genre_categories_through_first_top_10_hit', '#_of_major_genre_categories_through_first_top_10_hit', 'top_10_1hit_wonder_song', 'top_10_1hit_wonder_album', 'top_10_hitmaker_songs', 'top_10_hitmaker_albums', 'musicbrainz_major_genre_category', 'musicbrainz_#_of_genres', 'spotify_genres']

In [64]:
"""
Spotify Genre Categorization
=================================
Maps 546 MusicBrainz genres using the Spotify genre data to 18 major categories.
Based on Grammy/AllMusic/Billboard industry standards.
"""

import pandas as pd

# Complete mapping: MusicBrainz genre → Major Category
musicbrainz_to_major_genre = {
    
    # ROCK
    'rock': 'Rock',
    'rock and roll': 'Rock',
    'classic rock': 'Rock',
    'hard rock': 'Rock',
    'soft rock': 'Rock',
    'arena rock': 'Rock',
    'heartland rock': 'Rock',
    'mainstream rock': 'Rock',
    'southern rock': 'Rock',
    'roots rock': 'Rock',
    'swamp rock': 'Rock',
    'pub rock': 'Rock',
    'garage rock': 'Rock',
    'garage rock revival': 'Rock',
    'garage psych': 'Rock',
    'psychedelic rock': 'Rock',
    'psychedelic': 'Rock',
    'acid rock': 'Rock',
    'raga rock': 'Rock',
    'heavy psych': 'Rock',
    'progressive rock': 'Rock',
    'progressive': 'Rock',
    'prog rock': 'Rock',
    'symphonic rock': 'Rock',
    'symphonic prog': 'Rock',
    'crossover prog': 'Rock',
    'krautrock': 'Rock',
    'space rock': 'Rock',
    'glam rock': 'Rock',
    'glam': 'Rock',
    'blues rock': 'Rock',
    'boogie rock': 'Rock',
    'surf rock': 'Rock',
    'surf': 'Rock',
    'instrumental rock': 'Rock',
    'post-rock': 'Rock',
    'noise rock': 'Rock',
    'alternative rock': 'Rock',
    'indie rock': 'Rock',
    'grunge': 'Rock',
    'post-grunge': 'Rock',
    'britpop': 'Rock',
    'post-britpop': 'Rock',
    'shoegaze': 'Rock',
    'dream pop': 'Rock',
    'jangle pop': 'Rock',
    'paisley underground': 'Rock',
    'neo-psychedelia': 'Rock',
    'lo-fi': 'Rock',
    'slacker rock': 'Rock',
    'geek rock': 'Rock',
    'merseybeat': 'Rock',
    'beat music': 'Rock',
    'freakbeat': 'Rock',
    'mod': 'Rock',
    'nederbeat': 'Rock',
    'nederpop': 'Rock',
    'frat rock': 'Rock',
    'yacht rock': 'Rock',
    'aor': 'Rock',
    'industrial rock': 'Rock',
    'electronic rock': 'Rock',
    'dance-rock': 'Rock',
    'folk rock': 'Rock',
    'celtic rock': 'Rock',
    'medieval rock': 'Rock',
    'country rock': 'Rock',
    'reggae rock': 'Rock',
    'tropical rock': 'Rock',
    'stoner rock': 'Rock',
    'desert rock': 'Rock',
    'occult rock': 'Rock',
    'rockabilly': 'Rock',
    'psychobilly': 'Rock',
    'acoustic rock': 'Rock',
    'piano rock': 'Rock',
    'vocal surf': 'Rock',
    'jam band': 'Rock',
    'steampunk': 'Rock',
    'rock opera': 'Rock',
    'comedy rock': 'Rock',
    'j-rock': 'Rock',
    'visual kei': 'Rock',
    'gothic': 'Rock',
    'gothic rock': 'Rock',
    'funk rock': 'Rock',
    'rap rock': 'Rock',
    
    # ELECTRONIC/DANCE
    'electronic': 'Electronic/Dance',
    'electronica': 'Electronic/Dance',
    'dance': 'Electronic/Dance',
    'club': 'Electronic/Dance',
    'edm': 'Electronic/Dance',
    'rave': 'Electronic/Dance',
    'house': 'Electronic/Dance',
    'deep house': 'Electronic/Dance',
    'tech house': 'Electronic/Dance',
    'progressive house': 'Electronic/Dance',
    'electro house': 'Electronic/Dance',
    'acid house': 'Electronic/Dance',
    'afro house': 'Electronic/Dance',
    'funky house': 'Electronic/Dance',
    'vocal house': 'Electronic/Dance',
    'french house': 'Electronic/Dance',
    'italo house': 'Electronic/Dance',
    'dutch house': 'Electronic/Dance',
    'euro house': 'Electronic/Dance',
    'tropical house': 'Electronic/Dance',
    'big room house': 'Electronic/Dance',
    'festival progressive house': 'Electronic/Dance',
    'ambient house': 'Electronic/Dance',
    'techno': 'Electronic/Dance',
    'ambient techno': 'Electronic/Dance',
    'trance': 'Electronic/Dance',
    'progressive trance': 'Electronic/Dance',
    'vocal trance': 'Electronic/Dance',
    'hard trance': 'Electronic/Dance',
    'big room trance': 'Electronic/Dance',
    'euro-trance': 'Electronic/Dance',
    'goa trance': 'Electronic/Dance',
    'psytrance': 'Electronic/Dance',
    'psybient': 'Electronic/Dance',
    'dubstep': 'Electronic/Dance',
    'brostep': 'Electronic/Dance',
    'future garage': 'Electronic/Dance',
    'uk garage': 'Electronic/Dance',
    'uk funky': 'Electronic/Dance',
    'drum and bass': 'Electronic/Dance',
    'jungle': 'Electronic/Dance',
    'liquid funk': 'Electronic/Dance',
    'neurofunk': 'Electronic/Dance',
    'drill and bass': 'Electronic/Dance',
    'jungle terror': 'Electronic/Dance',
    'breakbeat': 'Electronic/Dance',
    'breakbeat hardcore': 'Electronic/Dance',
    'breakcore': 'Electronic/Dance',
    'big beat': 'Electronic/Dance',
    'happy hardcore': 'Electronic/Dance',
    'ambient': 'Electronic/Dance',
    'dark ambient': 'Electronic/Dance',
    'drone': 'Electronic/Dance',
    'downtempo': 'Electronic/Dance',
    'trip hop': 'Electronic/Dance',
    'chillout': 'Electronic/Dance',
    'chillwave': 'Electronic/Dance',
    'idm': 'Electronic/Dance',
    'glitch': 'Electronic/Dance',
    'glitch hop': 'Electronic/Dance',
    'wonky': 'Electronic/Dance',
    'electro': 'Electronic/Dance',
    'disco': 'Electronic/Dance',
    'nu disco': 'Electronic/Dance',
    'italo disco': 'Electronic/Dance',
    'euro-disco': 'Electronic/Dance',
    'electro-disco': 'Electronic/Dance',
    'hi-nrg': 'Electronic/Dance',
    'freestyle': 'Electronic/Dance',
    'synthwave': 'Electronic/Dance',
    'vaporwave': 'Electronic/Dance',
    'future bass': 'Electronic/Dance',
    'bass music': 'Electronic/Dance',
    'trap edm': 'Electronic/Dance',
    'moombahton': 'Electronic/Dance',
    'jersey club': 'Electronic/Dance',
    'ghettotech': 'Electronic/Dance',
    'eurodance': 'Electronic/Dance',
    'eurobeat': 'Electronic/Dance',
    'italo dance': 'Electronic/Dance',
    'bubblegum dance': 'Electronic/Dance',
    'new beat': 'Electronic/Dance',
    'electroclash': 'Electronic/Dance',
    'new rave': 'Electronic/Dance',
    'electro swing': 'Electronic/Dance',
    'complextro': 'Electronic/Dance',
    'future rave': 'Electronic/Dance',
    'industrial': 'Electronic/Dance',
    'ebm': 'Electronic/Dance',
    'martial industrial': 'Electronic/Dance',
    'dark wave': 'Electronic/Dance',
    'witch house': 'Electronic/Dance',
    'futurepop': 'Electronic/Dance',
    'berlin school': 'Electronic/Dance',
    'minimal synth': 'Electronic/Dance',
    'progressive electronic': 'Electronic/Dance',
    'bitpop': 'Electronic/Dance',
    'ethereal wave': 'Electronic/Dance',
    'hip house': 'Electronic/Dance',
    'alternative dance': 'Electronic/Dance',
    'folktronica': 'Electronic/Dance',
    'funktronica': 'Electronic/Dance',
    'electropunk': 'Electronic/Dance',
    
    # POP
    'pop': 'Pop',
    'pop rock': 'Pop',
    'pop soul': 'Pop',
    'dance-pop': 'Pop',
    'electropop': 'Pop',
    'teen pop': 'Pop',
    'bubblegum pop': 'Pop',
    'power pop': 'Pop',
    'baroque pop': 'Pop',
    'art pop': 'Pop',
    'chamber pop': 'Pop',
    'indie pop': 'Pop',
    'noise pop': 'Pop',
    'sunshine pop': 'Pop',
    'sophisti-pop': 'Pop',
    'brill building': 'Pop',
    'space age pop': 'Pop',
    'europop': 'Pop',
    'j-pop': 'Pop',
    'k-pop': 'Pop',
    'q-pop': 'Pop',
    'alternative pop': 'Pop',
    'ambient pop': 'Pop',
    'psychedelic pop': 'Pop',
    'progressive pop': 'Pop',
    'avant-garde pop': 'Pop',
    'traditional pop': 'Pop',
    'schlager': 'Pop',
    'yé-yé': 'Pop',
    'pop yeh-yeh': 'Pop',
    'shibuya-kei': 'Pop',
    'ballad': 'Pop',
    'synth-pop': 'Pop',
    'new romantic': 'Pop',
    'new wave': 'Pop',
    'hyperpop': 'Pop',
    'glitch pop': 'Pop',
    'hypnagogic pop': 'Pop',
    'bedroom pop': 'Pop',
    'pop punk': 'Punk/Hardcore',
    'pop rap': 'Hip Hop/Rap',
    'emo pop': 'Punk/Hardcore',
    
    # HIP HOP/RAP
    'hip hop': 'Hip Hop/Rap',
    'rap': 'Hip Hop/Rap',
    'east coast hip hop': 'Hip Hop/Rap',
    'west coast hip hop': 'Hip Hop/Rap',
    'southern hip hop': 'Hip Hop/Rap',
    'dirty south': 'Hip Hop/Rap',
    'gangsta rap': 'Hip Hop/Rap',
    'g-funk': 'Hip Hop/Rap',
    'hardcore hip hop': 'Hip Hop/Rap',
    'conscious hip hop': 'Hip Hop/Rap',
    'political hip hop': 'Hip Hop/Rap',
    'alternative hip hop': 'Hip Hop/Rap',
    'experimental hip hop': 'Hip Hop/Rap',
    'abstract hip hop': 'Hip Hop/Rap',
    'instrumental hip hop': 'Hip Hop/Rap',
    'drumless hip hop': 'Hip Hop/Rap',
    'boom bap': 'Hip Hop/Rap',
    'jazz rap': 'Hip Hop/Rap',
    'trap': 'Hip Hop/Rap',
    'drill': 'Hip Hop/Rap',
    'chicago drill': 'Hip Hop/Rap',
    'jersey drill': 'Hip Hop/Rap',
    'detroit trap': 'Hip Hop/Rap',
    'grime': 'Hip Hop/Rap',
    'crunk': 'Hip Hop/Rap',
    'crunkcore': 'Hip Hop/Rap',
    'snap': 'Hip Hop/Rap',
    'hyphy': 'Hip Hop/Rap',
    'cloud rap': 'Hip Hop/Rap',
    'emo rap': 'Hip Hop/Rap',
    'plugg': 'Hip Hop/Rap',
    'rage': 'Hip Hop/Rap',
    'miami bass': 'Hip Hop/Rap',
    'memphis rap': 'Hip Hop/Rap',
    'chopped and screwed': 'Hip Hop/Rap',
    'horrorcore': 'Hip Hop/Rap',
    'nerdcore': 'Hip Hop/Rap',
    'underground hip hop': 'Hip Hop/Rap',
    'industrial hip hop': 'Hip Hop/Rap',
    'turntablism': 'Hip Hop/Rap',
    'lo-fi hip hop': 'Hip Hop/Rap',
    'ratchet music': 'Hip Hop/Rap',
    'digicore': 'Hip Hop/Rap',
    
    # R&B/SOUL/FUNK
    'r&b': 'R&B/Soul/Funk',
    'rhythm & blues': 'R&B/Soul/Funk',
    'contemporary r&b': 'R&B/Soul/Funk',
    'alternative r&b': 'R&B/Soul/Funk',
    'neo soul': 'R&B/Soul/Funk',
    'quiet storm': 'R&B/Soul/Funk',
    'soul': 'R&B/Soul/Funk',
    'southern soul': 'R&B/Soul/Funk',
    'northern soul': 'R&B/Soul/Funk',
    'deep soul': 'R&B/Soul/Funk',
    'psychedelic soul': 'R&B/Soul/Funk',
    'progressive soul': 'R&B/Soul/Funk',
    'blue-eyed soul': 'R&B/Soul/Funk',
    'smooth soul': 'R&B/Soul/Funk',
    'chicago soul': 'R&B/Soul/Funk',
    'philly soul': 'R&B/Soul/Funk',
    'motown': 'R&B/Soul/Funk',
    'doo-wop': 'R&B/Soul/Funk',
    'funk': 'R&B/Soul/Funk',
    'p-funk': 'R&B/Soul/Funk',
    'synth funk': 'R&B/Soul/Funk',
    'boogie': 'R&B/Soul/Funk',
    'go-go': 'R&B/Soul/Funk',
    'new orleans r&b': 'R&B/Soul/Funk',
    'minneapolis sound': 'R&B/Soul/Funk',
    'electro-funk': 'R&B/Soul/Funk',
    'hip hop soul': 'R&B/Soul/Funk',
    'new jack swing': 'R&B/Soul/Funk',
    'trap soul': 'R&B/Soul/Funk',
    
    # COUNTRY/AMERICANA
    'country': 'Country/Americana',
    'classic country': 'Country/Americana',
    'traditional country': 'Country/Americana',
    'contemporary country': 'Country/Americana',
    'country pop': 'Country/Americana',
    'country soul': 'Country/Americana',
    'outlaw country': 'Country/Americana',
    'alternative country': 'Country/Americana',
    'progressive country': 'Country/Americana',
    'neo-traditional country': 'Country/Americana',
    'bakersfield sound': 'Country/Americana',
    'nashville sound': 'Country/Americana',
    'honky tonk': 'Country/Americana',
    'western swing': 'Country/Americana',
    'bluegrass': 'Country/Americana',
    'progressive bluegrass': 'Country/Americana',
    'bro-country': 'Country/Americana',
    'red dirt': 'Country/Americana',
    'urban cowboy': 'Country/Americana',
    'country yodeling': 'Country/Americana',
    'yodeling': 'Country/Americana',
    'americana': 'Country/Americana',
    'cajun': 'Country/Americana',
    'zydeco': 'Country/Americana',
    'swamp pop': 'Country/Americana',
    'country blues': 'Blues',
    'country folk': 'Folk',
    'country gospel': 'Gospel/Christian/Religious',
    
    # FOLK
    'folk': 'Folk',
    'contemporary folk': 'Folk',
    'folk pop': 'Pop',
    'progressive folk': 'Folk',
    'psychedelic folk': 'Folk',
    'chamber folk': 'Folk',
    'avant-folk': 'Folk',
    'anti-folk': 'Folk',
    'indie folk': 'Folk',
    'neofolk': 'Folk',
    'neo-acoustic': 'Folk',
    'stomp and holler': 'Folk',
    'singer-songwriter': 'Folk',
    'ambient americana': 'Folk',
    'british folk rock': 'Rock',
    'folk punk': 'Punk/Hardcore',
    'folk metal': 'Metal',
    'irish folk': 'Folk',
    'celtic new age': 'Easy Listening/Vocal',
    
    # JAZZ
    'jazz': 'Jazz',
    'bebop': 'Jazz',
    'hard bop': 'Jazz',
    'post-bop': 'Jazz',
    'cool jazz': 'Jazz',
    'free jazz': 'Jazz',
    'avant-garde jazz': 'Jazz',
    'jazz fusion': 'Jazz',
    'jazz rock': 'Jazz',
    'jazz pop': 'Jazz',
    'contemporary jazz': 'Jazz',
    'smooth jazz': 'Jazz',
    'swing': 'Jazz',
    'big band': 'Jazz',
    'dixieland': 'Jazz',
    'acid jazz': 'Jazz',
    'spiritual jazz': 'Jazz',
    'vocal jazz': 'Jazz',
    'digital fusion': 'Jazz',
    'jazz-funk': 'Jazz',
    'soul jazz': 'Jazz',
    'close harmony': 'Jazz',
    
    # BLUES
    'blues': 'Blues',
    'electric blues': 'Blues',
    'chicago blues': 'Blues',
    'delta blues': 'Blues',
    'acoustic blues': 'Blues',
    'texas blues': 'Blues',
    'electric texas blues': 'Blues',
    'hill country blues': 'Blues',
    'classic blues': 'Blues',
    'piano blues': 'Blues',
    'british blues': 'Blues',
    'british rhythm & blues': 'Blues',
    'soul blues': 'Blues',
    'boogie-woogie': 'Blues',
    
    # METAL
    'metal': 'Metal',
    'heavy metal': 'Metal',
    'thrash metal': 'Metal',
    'death metal': 'Metal',
    'black metal': 'Metal',
    'power metal': 'Metal',
    'speed metal': 'Metal',
    'progressive metal': 'Metal',
    'folk metal': 'Metal',
    'gothic metal': 'Metal',
    'symphonic metal': 'Metal',
    'glam metal': 'Metal',
    'nu metal': 'Metal',
    'metalcore': 'Metal',
    'deathcore': 'Metal',
    'grindcore': 'Metal',
    'goregrind': 'Metal',
    'melodic death metal': 'Metal',
    'melodic black metal': 'Metal',
    'atmospheric black metal': 'Metal',
    'depressive black metal': 'Metal',
    'blackgaze': 'Metal',
    'symphonic black metal': 'Metal',
    'brutal death metal': 'Metal',
    'technical death metal': 'Metal',
    'death-doom metal': 'Metal',
    'funeral doom metal': 'Metal',
    'traditional doom metal': 'Metal',
    'doom metal': 'Metal',
    'sludge metal': 'Metal',
    'stoner metal': 'Metal',
    'groove metal': 'Metal',
    'industrial metal': 'Metal',
    'neoclassical metal': 'Metal',
    'nwobhm': 'Metal',
    'mathcore': 'Metal',
    'djent': 'Metal',
    'kawaii metal': 'Metal',
    'alternative metal': 'Metal',
    'crossover thrash': 'Metal',
    'noisecore': 'Metal',
    'post-metal': 'Metal',
    'funk metal': 'Metal',
    'rap metal': 'Metal',
    'rapcore': 'Metal',
    'trap metal': 'Metal',
    'mashcore': 'Metal',
    
    # PUNK/HARDCORE
    'punk': 'Punk/Hardcore',
    'punk rock': 'Punk/Hardcore',
    'hardcore punk': 'Punk/Hardcore',
    'post-hardcore': 'Punk/Hardcore',
    'anarcho-punk': 'Punk/Hardcore',
    'd-beat': 'Punk/Hardcore',
    'skate punk': 'Punk/Hardcore',
    'ska punk': 'Punk/Hardcore',
    'horror punk': 'Punk/Hardcore',
    'glam punk': 'Punk/Hardcore',
    'art punk': 'Punk/Hardcore',
    'proto-punk': 'Punk/Hardcore',
    'dance-punk': 'Punk/Hardcore',
    'emo': 'Punk/Hardcore',
    'emocore': 'Punk/Hardcore',
    'screamo': 'Punk/Hardcore',
    'emoviolence': 'Punk/Hardcore',
    'grebo': 'Punk/Hardcore',
    'post-punk': 'Punk/Hardcore',
    'post-punk revival': 'Punk/Hardcore',
    'no wave': 'Punk/Hardcore',
    'midwest emo': 'Punk/Hardcore',
    'punk blues': 'Punk/Hardcore',
    
    # LATIN
    'latin': 'Latin',
    'latin ballad': 'Latin',
    'latin pop': 'Latin',
    'latin rock': 'Latin',
    'salsa': 'Latin',
    'bachata': 'Latin',
    'mambo': 'Latin',
    'son cubano': 'Latin',
    'tango': 'Latin',
    'mariachi': 'Latin',
    'norteño': 'Latin',
    'corrido tumbado': 'Latin',
    'regional mexicano': 'Latin',
    'reggaeton': 'Latin',
    'electro latino': 'Latin',
    'canción melódica': 'Latin',
    'tex-mex': 'Latin',
    'trap latino': 'Latin',
    'bossa nova': 'Latin',
    'choro': 'Latin',
    'mpb': 'Latin',
    'latin jazz': 'Jazz',
    
    # REGGAE/CARIBBEAN
    'reggae': 'Reggae/Caribbean',
    'roots reggae': 'Reggae/Caribbean',
    'dub': 'Reggae/Caribbean',
    'lovers rock': 'Reggae/Caribbean',
    'ragga': 'Reggae/Caribbean',
    'reggae-pop': 'Reggae/Caribbean',
    'ska': 'Reggae/Caribbean',
    'rocksteady': 'Reggae/Caribbean',
    'third wave ska': 'Reggae/Caribbean',
    '2 tone': 'Reggae/Caribbean',
    'calypso': 'Reggae/Caribbean',
    'soca': 'Reggae/Caribbean',
    'dancehall': 'Reggae/Caribbean',
    'gospel reggae': 'Gospel/Christian/Religious',
    
    # CLASSICAL
    'classical': 'Classical',
    'contemporary classical': 'Classical',
    'modern classical': 'Classical',
    'cinematic classical': 'Classical',
    'post-minimalism': 'Classical',
    'opera': 'Classical',
    'orchestral': 'Classical',
    'operatic pop': 'Easy Listening/Vocal',
    
    # GOSPEL/CHRISTIAN/RELIGIOUS
    'gospel': 'Gospel/Christian/Religious',
    'contemporary gospel': 'Gospel/Christian/Religious',
    'southern gospel': 'Gospel/Christian/Religious',
    'christian rock': 'Gospel/Christian/Religious',
    'contemporary christian': 'Gospel/Christian/Religious',
    'christmas music': 'Gospel/Christian/Religious',
    
    # WORLD MUSIC
    'world fusion': 'World Music',
    'afrobeat': 'World Music',
    'afrobeats': 'World Music',
    'afro-funk': 'World Music',
    'soukous': 'World Music',
    'chalga': 'World Music',
    'maloya élektrik': 'World Music',
    'filmi': 'World Music',
    'persian pop': 'World Music',
    'amapiano': 'World Music',
    'néo-trad': 'World Music',
    'hindustani classical': 'World Music',
    'indian classical': 'World Music',
    'chanson française': 'World Music',
    'celtic': 'World Music',
    'klezmer': 'World Music',
    'fado': 'World Music',
    'flamenco': 'World Music',
    
    # EXPERIMENTAL/AVANT-GARDE
    'experimental': 'Experimental/Avant-Garde',
    'avant-garde': 'Experimental/Avant-Garde',
    'experimental rock': 'Experimental/Avant-Garde',
    'noise': 'Experimental/Avant-Garde',
    'harsh noise': 'Experimental/Avant-Garde',
    'black noise': 'Experimental/Avant-Garde',
    'sound art': 'Experimental/Avant-Garde',
    'sound collage': 'Experimental/Avant-Garde',
    'plunderphonics': 'Experimental/Avant-Garde',
    'epic collage': 'Experimental/Avant-Garde',
    'spamwave': 'Experimental/Avant-Garde',
    'dariacore': 'Experimental/Avant-Garde',
    'experimental electronic': 'Experimental/Avant-Garde',
    'art rock': 'Experimental/Avant-Garde',
    'math rock': 'Experimental/Avant-Garde',
    
    # EASY LISTENING/VOCAL
    'easy listening': 'Easy Listening/Vocal',
    'lounge': 'Easy Listening/Vocal',
    'cocktail nation': 'Easy Listening/Vocal',
    'comedy': 'Easy Listening/Vocal',
    'spoken word': 'Easy Listening/Vocal',
    "children's music": 'Easy Listening/Vocal',
    'instrumental': 'Easy Listening/Vocal',
    'musical': 'Easy Listening/Vocal',
    'music hall': 'Easy Listening/Vocal',
    'new age': 'Easy Listening/Vocal',
}

# Apply categorization
def categorize_musicbrainz_genres(genre_string):
    if pd.isna(genre_string) or not isinstance(genre_string, str):
        return None
    
    genres = [g.strip().lower() for g in genre_string.split(',')]
    categories = set()
    
    for genre in genres:
        if genre in musicbrainz_to_major_genre:
            categories.add(musicbrainz_to_major_genre[genre])
    
    return ', '.join(sorted(categories)) if categories else None

# Apply to dataframe
df_artists['major_genre_category'] = df_artists['genre_tags_musicbrainz'].apply(categorize_musicbrainz_genres)

# Analysis
total_with_genres = df_artists['genre_tags_musicbrainz'].notna().sum()
categorized = df_artists['major_genre_category'].notna().sum()

print("Major Genre Categorization Results:")
print("="*80)
print(f"Artists with MusicBrainz genres: {total_with_genres:,}")
print(f"Successfully categorized: {categorized:,} ({categorized/total_with_genres*100:.1f}%)")

print("\nDistribution across 18 major categories:")
print("-"*80)
all_categories = []
for cats in df_artists['major_genre_category'].dropna():
    all_categories.extend([c.strip() for c in cats.split(',')])

category_counts = pd.Series(all_categories).value_counts()
print(category_counts.to_string())

# Check uncategorized
def get_uncategorized_tags(genre_string):
    if pd.isna(genre_string) or not isinstance(genre_string, str):
        return []
    genres = [g.strip().lower() for g in genre_string.split(',')]
    return [g for g in genres if g not in musicbrainz_to_major_genre]

uncategorized_tags = []
for genre_str in df_artists['genre_tags_musicbrainz'].dropna():
    uncategorized_tags.extend(get_uncategorized_tags(genre_str))

if uncategorized_tags:
    print(f"\n\nUncategorized tags ({len(set(uncategorized_tags))} unique):")
    print("-"*80)
    print(pd.Series(uncategorized_tags).value_counts().to_string())
else:
    print("\n\n✓ All 546 tags categorized!")

print("\n" + "="*80)

Major Genre Categorization Results:
================================================================================
Artists with MusicBrainz genres: 8,351
Successfully categorized: 8,313 (99.5%)

Distribution across 18 major categories:
--------------------------------------------------------------------------------
Rock                          3591
Pop                           2748
R&B/Soul/Funk                 1511
Hip Hop/Rap                   1400
Electronic/Dance              1400
Metal                         1067
Punk/Hardcore                  951
Jazz                           903
Folk                           868
Country/Americana              827
Experimental/Avant-Garde       362
Gospel/Christian/Religious     337
Blues                          304
Easy Listening/Vocal           301
Latin                          301
Classical                      216
Reggae/Caribbean               195
World Music                    102


Uncategorized tags (350 unique):
--------------------------------------------------------------------------------
indietronica                    58
melodic metalcore               46
melodic hardcore                34
classical crossover             23
garage punk                     20
banda sinaloense                17
praise & worship                17
slowcore                        16
avant-garde metal               15
production music                14
ranchera                        13
electro-industrial              13
cowpunk                         13
christian metal                 12
texas country                   12
chiptune                        11
progressive metalcore           11
easycore                        11
free improvisation              11
deathgrind                      11
poetry                          10
crust punk                      10
avant-prog                      10
neue deutsche welle             10
electronicore                   10
twee pop                         9
bolero                           9
contra                           9
merengue                         9
freak folk                       9
country rap                      9
cumbia                           9
modal jazz                       8
canterbury scene                 8
electroacoustic                  7
celtic punk                      7
old-time                         7
baroque                          7
leftfield                        7
alternative folk                 7
southern metal                   7
italo-disco                      7
breaks                           7
hardstyle                        7
standup comedy                   7
sierreño                         6
corrido                          6
vallenato                        6
western                          6
us power metal                   6
nu jazz                          6
christian hip hop                6
dungeon synth                    6
lolicore                         6
afro-cuban jazz                  5
jump blues                       5
hardcore techno                  5
third stream                     5
post-industrial                  5
neo-progressive rock             5
space rock revival               5
dark cabaret                     5
melodic techno                   5
instrumental jazz                5
future house                     5
atmospheric sludge metal         5
comedy hip hop                   5
oi                               5
tejano                           5
c86                              5
old school hip hop               4
neon pop punk                    4
beatdown hardcore                4
future funk                      4
post-dubstep                     4
deathrock                        4
audio drama                      4
power electronics                4
opm                              4
cabaret                          4
gabber                           4
zolo                             4
sketch comedy                    4
powerviolence                    4
western classical                4
barbershop                       4
renaissance                      3
slushwave                        3
jazz blues                       3
dub techno                       3
hybrid trap                      3
truck driving country            3
ambient dub                      3
technical thrash metal           3
sleaze rock                      3
field recording                  3
romantic classical               3
nintendocore                     3
jersey club rap                  3
filk                             3
worldbeat                        3
dark electro                     3
minimalism                       3
tribal ambient                   3
sampledelia                      3
flamenco pop                     3
jamaican ska                     3
jazz poetry                      3
ragtime                          3
scam rap                         3
beat poetry                      3
exotica                          3
countrypolitan                   3
queercore                        3
drumstep                         3
mod revival                      3
swancore                         3
blackened death metal            3
crossover jazz                   3
viking metal                     3
acoustic texas blues             2
slam death metal                 2
gorenoise                        2
modern blues                     2
french electro                   2
new orleans blues                2
digital hardcore                 2
disco polo                       2
bhangra                          2
kawaii future bass               2
urban contemporary gospel        2
appalachian folk                 2
hardcore breaks                  2
street punk                      2
grupera                          2
stride                           2
midtempo bass                    2
swing revival                    2
death industrial                 2
zamrock                          2
louisiana blues                  2
chicano rap                      2
indorock                         2
narcocorrido                     2
melodic dubstep                  2
cybergrind                       2
madchester                       2
indie surf                       2
neue deutsche härte              2
jerk                             2
belgian techno                   2
deep tech                        2
melodic house                    2
brass band                       2
piedmont blues                   2
jerk rap                         2
darksynth                        2
bass house                       2
musique concrète                 2
acoustic chicago blues           2
hauntology                       2
pop metal                        2
uptempo hardcore                 2
liedermacher                     2
samba                            2
battle rap                       2
city pop                         2
bolero son                       2
pigfuck                          2
medieval                         2
coldwave                         2
gypsy jazz                       2
uk drill                         2
drone metal                      2
gnawa                            2
spirituals                       2
classical period                 2
punk rap                         2
samba-jazz                       2
cumbia mexicana                  2
carnatic classical               2
technobanda                      2
thrashcore                       2
halftime                         2
schranz                          1
colour bass                      1
swamp blues                      1
hard techno                      1
techstep                         1
minimal wave                     1
pipe band music                  1
microsound                       1
melbourne bounce                 1
turkish classical                1
dissonant death metal            1
sertanejo                        1
horror synth                     1
power noise                      1
makossa                          1
sigilkore                        1
jug band                         1
modern creative                  1
afro-jazz                        1
traditional black gospel         1
marchinha                        1
marabi                           1
stenchcore                       1
dancefloor drum and bass         1
funk ostentação                  1
funk carioca                     1
shitgaze                         1
bassline                         1
old school death metal           1
krushclub                        1
dark plugg                       1
marching band                    1
desert blues                     1
salsa dura                       1
chap hop                         1
sacred steel                     1
livetronica                      1
nuevo flamenco                   1
latin disco                      1
sasscore                         1
downtempo deathcore              1
nu style gabber                  1
frenchcore                       1
suomisaundi                      1
mass                             1
arabesk                          1
country boogie                   1
música criolla                   1
acid trance                      1
sea shanty                       1
minimal techno                   1
slam poetry                      1
country and irish                1
mafioso rap                      1
central asian throat singing     1
christian hardcore               1
dream trance                     1
rautalanka                       1
euphoric hardstyle               1
hardbass                         1
bluegrass gospel                 1
concerto                         1
jackin house                     1
pachanga                         1
boogaloo                         1
drift phonk                      1
phonk house                      1
brit funk                        1
puirt à beul                     1
skiffle                          1
pluggnb                          1
prank calls                      1
circus march                     1
festival trap                    1
phonk                            1
celtic metal                     1
forest psytrance                 1
raï                              1
chopper                          1
neoclassicism                    1
pilón                            1
guajira                          1
danzón                           1
epic doom metal                  1
death 'n' roll                   1
guaracha                         1
cantopop                         1
chicago bop                      1
manila sound                     1
coke rap                         1
artcore                          1
denpa                            1
dansktop                         1
neoclassical dark wave           1
dark folk                        1
bit music                        1
graphical sound                  1
industrial musical               1
latin house                      1
dark psytrance                   1
canzone napoletana               1
deconstructed club               1
tribal guarachero                1
ambient trance                   1
ambient noise wall               1
alternative punk                 1
flamenco jazz                    1
duranguense                      1
string quartet                   1
indian pop                       1
trance metal                     1
chutney soca                     1
algerian chaabi                  1
new mexico music                 1
acid breaks                      1
acid techno                      1
sexy drill                       1
alté                             1
junkanoo                         1
drumfunk                         1
data sonification                1
medieval metal                   1
cumbia peruana                   1
beatboxing                       1
2-step                           1
symphony                         1
black ambient                    1
bhavageethe                      1
hexd                             1
lambada                          1
zeuhl                            1
bounce                           1
kuda lumping                     1
ytpmv                            1
donosti sound                    1
atmospheric drum and bass        1
riot grrrl                       1
township bubblegum               1
doomgaze                         1
t-pop                            1
j-core                           1
turkish pop                      1
singeli                          1
speed garage                     1
uk hardcore                      1
slap house                       1
industrial techno                1
math pop                         1
skacore                          1
hopepunk                         1
speedcore                        1
stutter house                    1
space ambient                    1
chillstep                        1
neoclassical new age             1
salsa romántica                  1
chillsynth                       1
rumba flamenca                   1
rumba catalana                   1
war metal                        1
gypsy punk                       1
polka                            1
rumba                            1
mento                            1
levenslied                       1
techno kayō                      1

================================================================================

In [67]:
import ast

# Rename musicbrainz column to plural
df_artists = df_artists.rename(columns={'musicbrainz_major_genre_category': 'musicbrainz_major_genre_categories'})

# Parse spotify_genres (stored as string representation of a list)
def categorize_spotify_genres(genre_val):
    if pd.isna(genre_val) or not isinstance(genre_val, str) or genre_val.strip() == '':
        return None
    try:
        genres = ast.literal_eval(genre_val)
    except Exception:
        genres = [g.strip() for g in genre_val.split(',')]
    
    categories = set()
    for genre in genres:
        genre_lower = genre.strip().lower()
        if genre_lower in musicbrainz_to_major_genre:
            categories.add(musicbrainz_to_major_genre[genre_lower])
    
    return ', '.join(sorted(categories)) if categories else None

df_artists['spotify_major_genre_categories'] = df_artists['spotify_genres'].apply(categorize_spotify_genres)

# Summary
total = df_artists['spotify_genres'].notna().sum()
matched = df_artists['spotify_major_genre_categories'].notna().sum()
print(f"Artists with Spotify genres: {total:,}")
print(f"Successfully categorized: {matched:,} ({matched/total*100:.1f}%)")

print("\nDistribution:")
all_cats = []
for cats in df_artists['spotify_major_genre_categories'].dropna():
    all_cats.extend([c.strip() for c in cats.split(',')])
print(pd.Series(all_cats).value_counts().to_string())

# Check uncategorized spotify genres
unmatched = []
for val in df_artists['spotify_genres'].dropna():
    try:
        genres = ast.literal_eval(val)
    except:
        genres = [g.strip() for g in val.split(',')]
    for g in genres:
        if g.strip().lower() not in musicbrainz_to_major_genre:
            unmatched.append(g.strip().lower())

print(f"\nUnmatched Spotify genres ({len(set(unmatched))} unique):")
print(pd.Series(unmatched).value_counts().head(30).to_string())

Artists with Spotify genres: 3,455
Successfully categorized: 2,933 (84.9%)

Distribution:
Pop                           1150
Rock                          1059
Hip Hop/Rap                    572
R&B/Soul/Funk                  407
Electronic/Dance               367
Folk                           231
Country/Americana              205
Jazz                           198
Metal                          191
Easy Listening/Vocal           186
Punk/Hardcore                  141
Experimental/Avant-Garde       126
Latin                           91
Blues                           66
Reggae/Caribbean                37
Gospel/Christian/Religious      22
World Music                     11
Classical                        8

Unmatched Spotify genres (960 unique):
indietronica                  38
post-disco                    37
ccm                           36
dance rock                    31
christian music               30
canadian pop                  30
vapor trap                    29
indie soul                    29
worship                       29
melancholia                   29
alt z                         28
modern blues                  27
latin hip hop                 26
viral pop                     26
modern country rock           24
west coast rap                24
houston rap                   23
christian alternative rock    23
reggae fusion                 23
chicago rap                   23
uk pop                        22
boy band                      22
british invasion              22
acoustic pop                  22
jazz saxophone                21
country dawn                  21
hollywood                     21
melodic metalcore             21
cali rap                      21
christian hip hop             20

In [66]:
musicbrainz_to_major_genre.update({
    'dance pop': 'Pop',
    'mellow gold': 'Rock',
    'album rock': 'Rock',
    'adult standards': 'Easy Listening/Vocal',
    'urban contemporary': 'R&B/Soul/Funk',
    'modern rock': 'Rock',
    'new wave pop': 'Pop',
    'post-teen pop': 'Pop',
    'gangster rap': 'Hip Hop/Rap',
    'hip pop': 'Hip Hop/Rap',
    'brill building pop': 'Pop',
    'permanent wave': 'Rock',
    'neo mellow': 'Rock',
    'pop dance': 'Pop',
    'synthpop': 'Pop',
    'atl hip hop': 'Hip Hop/Rap',
    'dirty south rap': 'Hip Hop/Rap',
    'rock-and-roll': 'Rock',
    'lilith': 'Folk',
    'classic soul': 'R&B/Soul/Funk',
    'country road': 'Country/Americana',
    'pop r&b': 'R&B/Soul/Funk',
    'classic uk pop': 'Pop',
    'modern alternative rock': 'Rock',
    'new americana': 'Country/Americana',
    'escape room': 'Pop',
    'indie poptimism': 'Pop',
    'jazz funk': 'Jazz',
    'metropopolis': 'Pop',
    'melodic rap': 'Hip Hop/Rap',
})

print(f"Total genres in mapping: {len(musicbrainz_to_major_genre)}")

Total genres in mapping: 579

In [70]:
df_artists = df_artists.drop(columns=['major_genre_category'], errors='ignore')
print(df_artists.shape)

(14226, 53)

In [72]:
top500 = df_kang_data_w_spotify.nlargest(500, 'popularity')[['id', 'name', 'popularity']]

in_df = top500[top500['id'].isin(df_artists['musicbrainz_artist_id'].dropna().astype(int))]
not_in_df = top500[~top500['id'].isin(df_artists['musicbrainz_artist_id'].dropna().astype(int))]

print(f"Top 500 by popularity: {len(top500)}")
print(f"Found in df_artists:   {len(in_df)}")
print(f"Not in df_artists:     {len(not_in_df)}")
print("\nNot in df_artists:")
print(not_in_df.to_string())

Top 500 by popularity: 500
Found in df_artists:   392
Not in df_artists:     108

Not in df_artists:
            id                                     name  popularity
187    1309563                         Marília Mendonça        89.0
74     1290934                          Sebastián Yatra        88.0
276    1079251                            Lenny Tavárez        88.0
32      422058                                  Beyoncé        87.0
124     191988                                   Tiësto        87.0
137        167                                    JAY‐Z        87.0
363    1670724                                     Duki        87.0
431     868677                             Arijit Singh        87.0
885    2009378                            María Becerra        87.0
993     192940                                 Arcángel        87.0
268    1030105                          Henrique Albino        85.0
381    1252793                                    Ninho        85.0
170     831916  Banda Sinaloense MS de Sergio Lizárraga        84.0
262     804367                            Gusttavo Lima        84.0
346    1083137                                      Jul        84.0
467    1311809                         Maiara & Maraisa        84.0
937    1587139                           Eladio Carrión        84.0
1425    368737                                   Pritam        84.0
1892   1839802                             Nicki Nicole        84.0
6948   2090996                            Santa Fe Klan        84.0
219     577669                           Jorge & Mateus        83.0
225    1644516                                    Dalex        83.0
270     713629                                     Alok        83.0
274    1503351                                    Morat        83.0
434    1388488                                  ROSALÍA        83.0
490      34802                         Ludovico Einaudi        83.0
505    1505352                                   Rels B        83.0
507    1586989                                 Måneskin        83.0
1025   1953368                                   GIVĒON        83.0
2051     39366                                     Pnau        83.0
2807    665128                                Zé Felipe        83.0
144       1440                            Guns N’ Roses        82.0
248     304981                                    Ne‐Yo        82.0
305     157342                           Wisin & Yandel        82.0
330    1560062                               Nio García        82.0
365     857223                               Jhené Aiko        82.0
388    1179459                         Lost Frequencies        82.0
647    1974150                              Jay Wheeler        82.0
721    1663900                                   Aitana        82.0
989     293426                               Ñengo Flow        82.0
1200   1247518                               Anne‐Marie        82.0
1670    917633                                     Tini        82.0
63      867864                                   G‐Eazy        81.0
121     232732                 Bob Marley & The Wailers        81.0
260    1318006                      Zé Neto & Cristiano        81.0
508     294212                                   T‐Pain        81.0
510      23514                        Vicente Fernández        81.0
553     809281                               C. Tangana        81.0
2059      2327                    Johann Sebastian Bach        81.0
3197    198731                           Shreya Ghoshal        81.0
3409   2018750                                   Trueno        81.0
3412   1782325                               Lit Killah        81.0
5173   1774552                                     Xamã        81.0
5217   1839814                            PEDRO SAMPAIO        81.0
6618   1337899                           Tanishk Bagchi        81.0
7201   1467181                               Steve Lacy        81.0
14712   851111                      Anirudh Ravichander        81.0
172        241                                blink‐182        80.0
236    1637497                             Paulo Londra        80.0
291        202                              Hans Zimmer        80.0
293      38536                      Alejandro Fernández        80.0
300       1319                                     Maná        80.0
377     626805                                    R3HAB        80.0
390    1689884                              Danny Ocean        80.0
497    1747885                                     KHEA        80.0
530    1282361                                  El Alfa        80.0
16743  1600180                                 Cavetown        80.0
21639  1626646                           Shiloh Dynasty        80.0
136      77944                            Michael Bublé        79.0
331    1277539                             Matheus Mota        79.0
336        139                              Céline Dion        79.0
425     777891                               RAF Camora        79.0
463     975013                               Becky Hill        79.0
475    2103723                   Os Barões da Pisadinha        79.0
477    1243587                                 Bonez MC        79.0
482    1975382                                  Imanbek        79.0
486     596594                                   MARINA        79.0
533      54739                       Los Ángeles Azules        79.0
542    1784564                                   MEDUZA        79.0
556    1366235                            Sfera Ebbasta        79.0
600    1591256                              El Fantasma        79.0
643         83                          Fryderyk Chopin        79.0
745      78755                       Natalia Lafourcade        79.0
771      11285                  Wolfgang Amadeus Mozart        79.0
788    1162500                            Ludmilla Dabo        79.0
1143   2094779                                    Morad        79.0
1632     46521                              Gabry Ponte        79.0
2120   1438142                            Gloria Groove        79.0
3211   1170661                           Jubin Nautiyal        79.0
3588   1646833                           D-Block Europe        79.0
18184      104                                 [Disney]        79.0
252    1425714                                  Piso 21        78.0
325     650387                       Lin‐Manuel Miranda        78.0
344     799435                            Pablo Alborán        78.0
428    1574933                              Mau y Ricky        78.0
435    1167607                                Sam Feldt        78.0
448     497122                               Jesse Cook        78.0
464    1099337                                Jax Jones        78.0
520    1489816                                 Brytiago        78.0
544    1296270                                    Damso        78.0
607     727129                             Luan Santana        78.0
649     645007                              Danna Paola        78.0
738    1678838                                 Dilsinho        78.0
801    1583680                                   Neffex        78.0
808    1616649                              Luísa Sonza        78.0
820    1502637                               Ghostemane        78.0
917    1216723                                   AURORA        78.0
918    1279452                          Vintage Culture        78.0

In [73]:
not_in_df_copy = not_in_df.copy()
not_in_df_copy['name_lower'] = not_in_df_copy['name'].str.lower().str.strip()

df_artists_names = df_artists[['name', 'musicbrainz_artist_id']].copy()
df_artists_names['name_lower'] = df_artists_names['name'].str.lower().str.strip()

name_matches = not_in_df_copy.merge(
    df_artists_names,
    on='name_lower', how='inner'
)

print(f"Name matches: {len(name_matches)}")
print(name_matches[['name_x', 'id', 'musicbrainz_artist_id', 'popularity']].to_string())

Name matches: 3
       name_x       id  musicbrainz_artist_id  popularity
0  Steve Lacy  1467181                 249403        81.0
1      MARINA   596594                2430288        79.0
2      AURORA  1216723                 244616        78.0

In [74]:
import unicodedata

def strip_accents(s):
    if not isinstance(s, str):
        return s
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    ).lower().strip()

not_in_df_copy['name_norm'] = not_in_df_copy['name'].apply(strip_accents)
df_artists_names['name_norm'] = df_artists_names['name'].apply(strip_accents)

name_matches = not_in_df_copy.merge(
    df_artists_names,
    on='name_norm', how='inner'
)

print(f"Name matches (accent-insensitive): {len(name_matches)}")
print(name_matches[['name_x', 'name_y', 'id', 'musicbrainz_artist_id', 'popularity']].to_string())

Name matches (accent-insensitive): 21
                                     name_x                                   name_y       id  musicbrainz_artist_id  popularity
0                           Sebastián Yatra                          sebastian yatra  1290934                   <NA>        88.0
1                                   Beyoncé                                  beyonce   422058                   <NA>        87.0
2                                    Tiësto                                   tiesto   191988                   <NA>        87.0
3                                  Arcángel                                 arcangel   192940                   <NA>        87.0
4   Banda Sinaloense MS de Sergio Lizárraga  banda sinaloense ms de sergio lizarraga   831916                   <NA>        84.0
5                            Eladio Carrión                           eladio carrion  1587139                   <NA>        84.0
6                                   ROSALÍA                                  rosalia  1388488                2308830        83.0
7                                  Måneskin                                 maneskin  1586989                   <NA>        83.0
8                                    GIVĒON                                   giveon  1953368                   <NA>        83.0
9                                Nio García                               nio garcia  1560062                   <NA>        82.0
10                               Jhené Aiko                               jhene aiko   857223                   <NA>        82.0
11                               Ñengo Flow                               nengo flow   293426                   <NA>        82.0
12                        Vicente Fernández                        vicente fernandez    23514                   <NA>        81.0
13                               Steve Lacy                               steve lacy  1467181                 249403        81.0
14                      Alejandro Fernández                      alejandro fernandez    38536                   <NA>        80.0
15                                     Maná                                     mana     1319                1086595        80.0
16                            Michael Bublé                            michael buble    77944                   <NA>        79.0
17                              Céline Dion                              celine dion      139                   <NA>        79.0
18                                   MARINA                                   marina   596594                2430288        79.0
19                       Los Ángeles Azules                       los angeles azules    54739                   <NA>        79.0
20                                   AURORA                                   aurora  1216723                 244616        78.0

In [75]:
from difflib import SequenceMatcher

# All kang artists not matched by ID
not_matched_by_id = df_kang_data_w_spotify[
    ~df_kang_data_w_spotify['id'].isin(df_artists['musicbrainz_artist_id'].dropna().astype(int))
].copy()
not_matched_by_id['name_norm'] = not_matched_by_id['name'].apply(strip_accents)

df_artists_names['name_norm'] = df_artists_names['name'].apply(strip_accents)

# Exact normalized matches
exact = not_matched_by_id.merge(df_artists_names, on='name_norm', how='inner')
print(f"Exact normalized matches: {len(exact)}")

# Near matches (similarity >= 0.85) for remaining
already_matched = set(exact['name_norm'])
remaining = not_matched_by_id[~not_matched_by_id['name_norm'].isin(already_matched)]
df_artist_names_list = df_artists_names['name_norm'].dropna().tolist()

near_matches = []
for _, row in remaining.iterrows():
    kang_name = row['name_norm']
    best_score = 0
    best_match = None
    for a_name in df_artist_names_list:
        score = SequenceMatcher(None, kang_name, a_name).ratio()
        if score > best_score:
            best_score = score
            best_match = a_name
    if best_score >= 0.85:
        near_matches.append({
            'kang_name': row['name'], 
            'df_match': best_match, 
            'score': round(best_score, 3),
            'kang_id': row['id']
        })

near_df = pd.DataFrame(near_matches).sort_values('score', ascending=False)
print(f"Near matches (similarity ≥ 0.85): {len(near_df)}")
print(near_df.to_string())

Exact normalized matches: 124
Near matches (similarity ≥ 0.85): 743
                               kang_name                             df_match  score  kang_id
457   Noel Gallagher’s High Flying Birds   noel gallagher's high flying birds  0.971   819312
361  The Clayton‐Hamilton Jazz Orchestra  the clayton/hamilton jazz orchestra  0.971   534967
245      RTÉ National Symphony Orchestra      the national symphony orchestra  0.968   564687
71                      Dharohar Project                      dharoha project  0.968   741945
681                      Andrew Williams                       andre williams  0.966  1999813
475                       Andreas Martin                        andrea martin  0.963    57173
250                        Northernlight                       northern light  0.963  1585928
416                        The Residents                       the presidents  0.963     9006
654           Sérgio Mendes & Brasil ’66           sergio mendes & brasil '66  0.962    31816
404            Manfred Mann’s Earth Band            manfred mann's earth band  0.960    12076
355                        Iain Matthews                         ian matthews  0.960    30721
13              The All‐American Rejects             the all-american rejects  0.958    58875
489             Trans‐Siberian Orchestra             trans-siberian orchestra  0.958    11727
308             Bachman–Turner Overdrive             bachman-turner overdrive  0.958     1672
400                         Michael Gray                          michael ray  0.957   186497
683                          James Young                         jaymes young  0.957  2127627
479                         Constantines                          constantine  0.957    48499
605                          Paula Kelly                           paul kelly  0.952   266880
443                Compton’s Most Wanted                compton's most wanted  0.952   118983
176                           DANGERDOOM                          danger doom  0.952   255478
510                           Danny Wild                          danny wilde  0.952   403829
524                 Terence Trent D’Arby                 terence trent d'arby  0.950    36030
390                 David Clayton‐Thomas                 david clayton-thomas  0.950   219919
258                “Brother” Jack McDuff                  brother jack mcduff  0.950     5381
125                 Fun Lovin’ Criminals                 fun lovin' criminals  0.950     9889
97                   Sophie Ellis‐Bextor                  sophie ellis-bextor  0.947    37524
565                           The Pheels                            the peels  0.947  1375982
405                           jeonghyeon                            jeongyeon  0.947  1921269
137                  Jean‐Yves Thibaudet                  jean-yves thibaudet  0.947    63321
691                           Structured                            structure  0.947  1363598
593                            Cathedral                           cathedrals  0.947     8524
19                   Soulja Boy Tell ’Em                  soulja boy tell 'em  0.947   457542
165                            Sixx:A.M.                           sixx: a.m.  0.947   455460
298                            Andy Bell                           randy bell  0.947   243702
77                    Olivia Newton‐John                   olivia newton-john  0.944    11078
4                     Lin‐Manuel Miranda                   lin-manuel miranda  0.944   650387
147                   Jean‐Pierre Rampal                   jean-pierre rampal  0.944     3895
226                             Jac Ross                            jack ross  0.941  1978429
350                             John Gay                            john gary  0.941   401796
323                             MICHELLE                            michel'le  0.941  2028323
8                      Mike WiLL Made‐It                    mike will made-it  0.941  1041633
209    Big Brother & the Holding Company  big brother and the holding company  0.941    38092
2                              Arcangelo                             arcangel  0.941  1211210
194                    Ol’ Dirty Bastard                    ol' dirty bastard  0.941    31507
562                             Lost Boy                            lost boyz  0.941  2156223
658                    Girls’ Generation                    girls' generation  0.941   535481
554                             Dane Ray                            diane ray  0.941  1958592
633                    Drive‐By Truckers                    drive-by truckers  0.941    21614
39                    Franco “El Gorila”                     franco el gorila  0.941   603684
626                             Republic                            republica  0.941  2020359
18                             Disciples                             disciple  0.941  1034075
464                            Qwestlife                             westlife  0.941  1622527
144                     Héctor el Father                   hector 'el father'  0.941   338382
23                     Far East Movement                    far*east movement  0.941   368108
532                             Alestorm                            halestorm  0.941   495996
96                     Jean‐Michel Jarre                    jean michel jarre  0.941     3283
143     Elvis Costello & The Attractions   elvis costello and the attractions  0.939    67633
256                     Jane’s Addiction                     jane's addiction  0.938     1577
407                     Herman’s Hermits                     herman's hermits  0.938     6518
344                     Flamin’ Groovies                     flaming groovies  0.938     4111
46                      Shaquille O’Neal                     shaquille o'neal  0.938    33486
434                     Eagle‐Eye Cherry                     eagle-eye cherry  0.938      505
293                             Miranda!                              miranda  0.933   199966
477                              Jacques                             jacquees  0.933  1223680
100                Everything Everything             everything is everything  0.933   612228
726                      At the Drive‐In                      at the drive-in  0.933     4199
667                              Freeman                             free-man  0.933   446671
661                             Lil Xian                              lil xan  0.933  2040167
604                             Don Raye                              don ray  0.933   164060
574                             Nathalie                              natalie  0.933   764514
526                             TheUnder                              thunder  0.933  1862533
508                      Ten Years Later                      ten years after  0.933  1170139
397                             Citizenn                              citizen  0.933   979634
283                      Shakin’ Stevens                      shakin' stevens  0.933    42320
195                      Sinéad O’Connor                      sinead o'connor  0.933      200
196                             Big Rich                              big ric  0.933   918700
219                      Gil Scott‐Heron                      gil scott-heron  0.933    15770
345                      Frehley’s Comet                      frehley's comet  0.933   158757
336      Martha Reeves and the Vandellas        martha reeves & the vandellas  0.933   747641
322                              LLusion                             illusion  0.933  1520715
304                              Airwave                             airwaves  0.933    51826
371                      Aoife O’Donovan                      aoife o'donovan  0.933   390496
742                             Sylvaine                              sylvain  0.933  1171667
5                        Destiny’s Child                      destiny's child  0.933      468
9                        Gigi D’Agostino                      gigi d'agostino  0.933    32111
49                              Bobby V.                              bobby v  0.933   232297
205          National Symphony Orchestra      the national symphony orchestra  0.931   777343
20                         iLoveMakonnen                      i love makonnen  0.929  1144798
259        Béla Fleck and the Flecktones          bela fleck & the flecktones  0.929     9563
679                       Da’ T.R.U.T.H.                       da' t.r.u.t.h.  0.929   164440
307                       Jennifer Pague                       jennifer paige  0.929  1847709
12                        Olivia O’Brien                       olivia o'brien  0.929  1360635
624          Tommy James & the Shondells        tommy james and the shondells  0.929    35678
441                      John Williamson                        john williams  0.929    31058
426                       George Clanton                       george clinton  0.929  1300259
234                       Quad City DJ’s                       quad city dj's  0.929     9124
738                       The Good Times                       the goodtimers  0.929  2158078
640                        Víctor Manuel                      victor manuelle  0.929    48100
198                       Pi’erre Bourne                       pi'erre bourne  0.929  1678039
236                       Jean‐Luc Ponty                       jean luc ponty  0.929    34563
242            Sydney Symphony Orchestra        the sydney symphony orchestra  0.926   359906
595                        Lowell Fulson                        lowell fulsom  0.923     3726
571                               ROCKET                              rockets  0.923  1739378
327                              Nielson                               nelson  0.923   922066
538                              Eclipse                               clipse  0.923   501437
534                              Aklesso                               alesso  0.923  1942361
292                       William Babell                         william bell  0.923   253687
155                        Justin Taylor                        austin taylor  0.923  1567492
0                          Guns N’ Roses                        guns n' roses  0.923     1440
596                              Yasmine                               yasmin  0.923    90943
599                              Visages                               visage  0.923  1880896
602                               DJ KOO                              dj kool  0.923   627552
379          Kid Creole and the Coconuts            kid creole & the coconuts  0.923    30906
673                               Misfit                              misfits  0.923  1440867
178                              MC Rene                               mc ren  0.923   122472
632                               Rebeka                              rebekah  0.923   893457
229                              Cherrie                               cherie  0.923  1347556
188                        Johnny Rivera                        johnny rivers  0.923    58388
223                               Pressa                              pressha  0.923  1457197
377                        Lale Andersen                        lale anderson  0.923    59217
202                               Franke                              frankee  0.923  1600133
112                               Father                              feather  0.923  1919461
468                        Dominic Lalli                        dominic balli  0.923   923939
391                        State of Mind                        state of mine  0.923   396054
35                         Colby O’Donis                        colby o'donis  0.923   412724
33                                Axwell                              maxwell  0.923   175937
88                         Opetaia Foaʻi                        opetaia foa'i  0.923   305190
389                              Olivera                               oliver  0.923  1269357
734                               Caesar                              caesars  0.923  2108689
393                  Christopher Willits                 christopher williams  0.923   198258
482                              DoubleV                               double  0.923   950579
108             Los Angeles Philharmonic         the los angeles philharmonic  0.923    49273
732                              Marinah                               marina  0.923  1644331
502                        Saul Williams                        paul williams  0.923    64825
105             Gladys Knight & The Pips           gladys knight and the pips  0.920    12313
686                         Dave Steward                         dave stewart  0.917  1667234
118                         Howlin’ Wolf                         howlin' wolf  0.917     6439
531                         The Bar‐Kays                         the bar-kays  0.917    20117
261            Siouxsie and the Banshees              siouxsie & the banshees  0.917     2180
306                          The Prophet                        thee prophets  0.917    88244
14                          Wu‐Tang Clan                         wu-tang clan  0.917     2504
664                        Danny Whitney                          danny white  0.917  1684015
657                         The Mowgli’s                         the mowgli's  0.917   896091
450                         ’Til Tuesday                         'til tuesday  0.917    38185
277               Glenn Miller Orchestra           the glenn miller orchestra  0.917    34754
75                Tommy Dorsey Orchestra           the tommy dorsey orchestra  0.917   591219
382                        Alexis Taylor                          alex taylor  0.917   350001
563               Devin Townsend Project           the devin townsend project  0.917   610168
332                         Generation X                         generation j  0.917    35364
720                          Amie Waters                        jamie walters  0.917  2042240
594                   Riccardo Cocciante                    richard cocciante  0.914    67071
139              Evelyn “Champagne” King              evelyn 'champagne' king  0.913    32122
282               Freddie & the Dreamers             freddie and the dreamers  0.913    59972
354        Kodály Philharmonic Orchestra         royal philharmonic orchestra  0.912  1498430
231                          John Wilson                          josh wilson  0.909   921448
496                               Lloyds                                lloyd  0.909  2013657
440                         Steve Harley                           steve hare  0.909    34769
566                                Alice                               malice  0.909    36730
627                                Gorge                               george  0.909   515850
487                          John Martyn                          john martin  0.909     4686
235             The Mothers of Invention                 mothers of invention  0.909   342367
561                               LINKER                                liner  0.909  2215927
452                               Jamala                                jamal  0.909   759807
546                                Hades                               shades  0.909   800058
559                               BAZZIX                                bazzi  0.909  1855546
211                               Indiga                                india  0.909   363166
455                                Sango                               shango  0.909  1063073
620                                Signo                               siggno  0.909   785371
555                          Joy Orbison                          roy orbison  0.909   646496
228                                Yasin                               yasmin  0.909  1848676
224                           John Adams                         johnny adams  0.909    51506
367                          Evan Parker                          ivan parker  0.909    77832
221                                Snypa                               snypaz  0.909  1511180
557                               John B                                jon b  0.909    90500
611                               Ashana                                shana  0.909  1286168
614                               Carmel                                camel  0.909    74113
525              Johnny Clegg and Savuka                johnny clegg & savuka  0.909    22863
58                                GRACEY                                grace  0.909  1886713
296                                Zomby                               zomboy  0.909   565387
59                                Carola                                carla  0.909    64249
580                          Mick Gordon                          mike gordon  0.909   842550
586                                Nigma                               enigma  0.909  2068210
290                               Chilla                                chill  0.909  1334160
588                           John Adams                         johnny adams  0.909  1493611
572                               Rakhim                                rakim  0.909  2016601
395                           The Intern                         the internet  0.909  1902133
280                               Braids                                braid  0.909   749133
398                          Vanilla Ace                          vanilla ice  0.909   932909
581                               Sllash                                slash  0.909  2135583
401                               Monthy                                monty  0.909  1533094
597                               ChaseR                                chase  0.909  1376392
598                               Raiden                                aiden  0.909   163857
324                               Lizzow                                lizzo  0.909  2192171
325                               Ali As                                alias  0.909   564223
43                           Jay Anthony                          ray anthony  0.909  1833564
385                          The Popples                          the poppies  0.909  2019513
260                          René Thomas                          gene thomas  0.909   340828
512                               Norlan                                nolan  0.909   767290
30                                Angèle                                angel  0.909  1566722
310                      Christopher Tin                   christopher atkins  0.909   303551
276                          101 Strings                          100 strings  0.909    57991
92                                 Larry                               larray  0.909  1917645
677                               Saxxon                                saxon  0.909  1074177
694                                Jerro                               jerrio  0.909  1929730
127                                Riton                               rixton  0.909   110347
145                                Reezy                               dreezy  0.909  1804744
728                               Myrone                                myron  0.909  1138393
703                          Steve Brand                          steve grand  0.909   552986
94                                Susana                                susan  0.909   312069
712                           HumaNature                         human nature  0.909  1581285
716                                Elena                               selena  0.909   549401

In [78]:
print("=== 124 EXACT NORMALIZED MATCHES ===")
print(exact[['name_x', 'name_y', 'id', 'musicbrainz_artist_id', 'popularity']].to_string())

print("\n=== NEAR MATCHES (score >= 0.95) ===")
print(near_df[near_df['score'] >= 0.95][['kang_name', 'df_match', 'score', 'kang_id']].to_string())

=== 124 EXACT NORMALIZED MATCHES ===
                                      name_x                                   name_y       id  musicbrainz_artist_id  popularity
0                                    Beyoncé                                  beyonce   422058                   <NA>        87.0
1                            Sebastián Yatra                          sebastian yatra  1290934                   <NA>        88.0
2                                     Tiësto                                   tiesto   191988                   <NA>        87.0
3                              Michael Bublé                            michael buble    77944                   <NA>        79.0
4    Banda Sinaloense MS de Sergio Lizárraga  banda sinaloense ms de sergio lizarraga   831916                   <NA>        84.0
5                        Alejandro Fernández                      alejandro fernandez    38536                   <NA>        80.0
6                                       Maná                                     mana     1319                1086595        80.0
7                                 Nio García                               nio garcia  1560062                   <NA>        82.0
8                                Céline Dion                              celine dion      139                   <NA>        79.0
9                                 Jhené Aiko                               jhene aiko   857223                   <NA>        82.0
10                             John Williams                            john williams       94                2788464        76.0
11                                   ROSALÍA                                  rosalia  1388488                2308830        83.0
12                                     Aminé                                    amine  1404279                3001020        76.0
13                                    MARINA                                   marina   596594                2430288        79.0
14                                  Måneskin                                 maneskin  1586989                   <NA>        83.0
15                         Vicente Fernández                        vicente fernandez    23514                   <NA>        81.0
16                                Pedro Capó                               pedro capo   780663                   <NA>        73.0
17                        Los Ángeles Azules                       los angeles azules    54739                   <NA>        79.0
18                               Mötley Crüe                              motley crue    36594                   <NA>        74.0
19                             Casper Mágico                            casper magico  1598916                   <NA>        75.0
20                                    Plan B                                   plan b   379514                 379522        58.0
21                               Emeli Sandé                              emeli sande   672447                   <NA>        69.0
22                                      EDEN                                     eden  1356579                3069181        68.0
23                                    AURORA                                   aurora  1216723                 244616        78.0
24                            Eladio Carrión                           eladio carrion  1587139                   <NA>        84.0
25                            Victoria Monét                           victoria monet   907526                   <NA>        66.0
26                                Ñengo Flow                               nengo flow   293426                   <NA>        82.0
27                                  Arcángel                                 arcangel   192940                   <NA>        87.0
28                                 J Álvarez                                j alvarez   829965                   <NA>        71.0
29                           Víctor Manuelle                          victor manuelle    46655                   <NA>        67.0
30                                    GIVĒON                                   giveon  1953368                   <NA>        83.0
31                                    Plan B                                   plan b   379520                 379522        78.0
32                                      Five                                     five      800                1928117        59.0
33                             Janelle Monáe                            janelle monae   406225                   <NA>        70.0
34                                    Thalía                                   thalia   116401                2497618        74.0
35                     Engelbert Humperdinck                    engelbert humperdinck    43566                 323769        63.0
36                               Miguel Bosé                              miguel bose    22919                   <NA>        72.0
37                                Kiana Ledé                               kiana lede  1600063                   <NA>        70.0
38                                       Eve                                      eve    11664                1819048        71.0
39                          Alejandra Guzmán                         alejandra guzman     2579                   <NA>        71.0
40                                André 3000                               andre 3000   243404                   <NA>        65.0
41                                       Mýa                                      mya     3106                2040581        46.0
42                                Elley Duhé                               elley duhe  1534760                   <NA>        77.0
43                                    Alemán                                   aleman  1745960                2312477        41.0
44                                      Nena                                     nena   242220                2534753        65.0
45                                     Jónsi                                    jonsi   665339                   <NA>        54.0
46                             Sérgio Mendes                            sergio mendes     2815                   <NA>        59.0
47                            Changing Faces                           changing faces    22444                1255916        40.0
48                                      LÉON                                     leon  1339591                1474644        69.0
49                               Kany García                              kany garcia   558899                   <NA>        73.0
50                                     Björk                                    bjork     1022                   <NA>        65.0
51                      Antônio Carlos Jobim                     antonio carlos jobim    23252                   <NA>        69.0
52                                Édith Piaf                               edith piaf     2021                   <NA>        64.0
53                         Tony! Toni! Toné!                        tony! toni! tone!    53815                   <NA>        58.0
54                                     Monty                                    monty  1257493                2859045        61.0
55                           Angélique Kidjo                          angelique kidjo    82981                   <NA>        52.0
56                               Michel Teló                              michel telo   727130                   <NA>        62.0
57                              André Previn                             andre previn     4510                   <NA>        64.0
58                                     Dream                                    dream  2116044                1937907        65.0
59                              Rocío Dúrcal                             rocio durcal   145197                   <NA>        72.0
60                                 Motörhead                                motorhead     3527                   <NA>        69.0
61                                     Sandy                                    sandy   581910                 296373        61.0
62                                     Sisqó                                    sisqo    11035                   <NA>        62.0
63                               Los del Río                              los del rio     9918                   <NA>        60.0
64                             Renée Fleming                            renee fleming   119255                   <NA>        52.0
65                                André Rieu                               andre rieu    35001                   <NA>        65.0
66                           Plácido Domingo                          placido domingo    23678                   <NA>        58.0
67                             Bomba Estéreo                            bomba estereo   638503                   <NA>        66.0
68                             Tego Calderón                            tego calderon    58267                   <NA>        74.0
69                                  Röyksopp                                 royksopp    52208                   <NA>        64.0
70                            Marilyn Manson                           marilyn manson   255235                    187        73.0
71                                Béla Fleck                               bela fleck    15860                   <NA>        48.0
72                              Chanté Moore                             chante moore      473                2862287        47.0
73                             José González                            jose gonzalez   119552                2460249        68.0
74                                      Kali                                     kali   862749                2848174        38.0
75                          Agnetha Fältskog                         agnetha faltskog    33544                   <NA>        48.0
76                              Martha Veléz                             martha velez   398595                   <NA>        10.0
77                                Steve Lacy                               steve lacy  1467181                 249403        81.0
78                             John Williams                            john williams   238569                2788464        53.0
79                                    Aurora                                   aurora   244623                 244616        30.0
80                                Eric Benét                               eric benet    30292                   <NA>        54.0
81                               Gábor Szabó                              gabor szabo    73628                   <NA>        51.0
82                                      Nena                                     nena     1894                2534753        65.0
83                                      Mina                                     mina    32092                1365950        61.0
84                            James Morrison                           james morrison    32583                 375655        29.0
85                                       Dio                                      dio     1443                 483466        65.0
86                                    Exposé                                   expose   179806                1283484        49.0
87                                Ultra Naté                               ultra nate    38874                   <NA>        54.0
88                                    Poliça                                   polica   849484                   <NA>        46.0
89                                    Brandy                                   brandy   141191                   9341         1.0
90                                 Mel Tormé                                mel torme    64218                   <NA>        55.0
91                              Nancy Wilson                             nancy wilson    32799                 286239        31.0
92                               Eydie Gormé                              eydie gorme    82951                   <NA>        61.0
93                                Raul Midón                               raul midon   198926                   <NA>        36.0
94                            Robert Johnson                           robert johnson   270862                 287815        21.0
95                            José Feliciano                           jose feliciano    47801                   <NA>        67.0
96                               Marié Digby                              marie digby   466335                   <NA>        45.0
97                                Juan Vélez                               juan velez   664916                2938534        21.0
98                             Cesária Évora                            cesaria evora     3195                   <NA>        58.0
99                                     Raven                                    raven     5597                2141937        31.0
100                                Sigur Rós                                sigur ros    11546                   <NA>        61.0
101                           Robert Johnson                           robert johnson     6442                 287815        49.0
102                                     EDEN                                     eden  1926821                3069181        44.0
103                                  Låpsley                                  lapsley  1120178                   <NA>        54.0
104                                Ivo Robić                                ivo robic   184318                   <NA>        28.0
105                                  Silentó                                  silento  1210752                   <NA>        54.0
106                                    dream                                    dream   259886                1937907        34.0
107                                     Kali                                     kali  1012758                2848174        18.0
108                                      Eve                                      eve  1450060                1819048        73.0
109                         Mongo Santamaría                         mongo santamaria     5300                   <NA>        49.0
110                            Natalie Grant                            natalie grant    32893                2124315        54.0
111                                   marina                                   marina   705232                2430288        31.0
112                                      EVE                                      eve  1981344                1819048        27.0
113                                     MINA                                     mina  1857234                1365950         0.0
114                              Queensrÿche                              queensryche     9095                   <NA>        59.0
115                                      Air                                      air   419866                2353616        12.0
116                                      Air                                      air      911                2353616        64.0
117                               José James                               jose james   500119                   <NA>        54.0
118                                    Chloé                                    chloe   163676                1852154        41.0
119                                    Monty                                    monty  1437178                2859045        15.0
120                                Yael Naïm                                yael naim   466431                   <NA>        56.0
121                                    Sandy                                    sandy   296391                 296373        38.0
122                             Télépopmusik                             telepopmusik    36009                   <NA>        52.0
123                                     Kali                                     kali   812834                2848174        60.0

=== NEAR MATCHES (score >= 0.95) ===
                               kang_name                             df_match  score  kang_id
457   Noel Gallagher’s High Flying Birds   noel gallagher's high flying birds  0.971   819312
361  The Clayton‐Hamilton Jazz Orchestra  the clayton/hamilton jazz orchestra  0.971   534967
245      RTÉ National Symphony Orchestra      the national symphony orchestra  0.968   564687
71                      Dharohar Project                      dharoha project  0.968   741945
681                      Andrew Williams                       andre williams  0.966  1999813
475                       Andreas Martin                        andrea martin  0.963    57173
250                        Northernlight                       northern light  0.963  1585928
416                        The Residents                       the presidents  0.963     9006
654           Sérgio Mendes & Brasil ’66           sergio mendes & brasil '66  0.962    31816
404            Manfred Mann’s Earth Band            manfred mann's earth band  0.960    12076
355                        Iain Matthews                         ian matthews  0.960    30721
13              The All‐American Rejects             the all-american rejects  0.958    58875
489             Trans‐Siberian Orchestra             trans-siberian orchestra  0.958    11727
308             Bachman–Turner Overdrive             bachman-turner overdrive  0.958     1672
400                         Michael Gray                          michael ray  0.957   186497
683                          James Young                         jaymes young  0.957  2127627
479                         Constantines                          constantine  0.957    48499
605                          Paula Kelly                           paul kelly  0.952   266880
443                Compton’s Most Wanted                compton's most wanted  0.952   118983
176                           DANGERDOOM                          danger doom  0.952   255478
510                           Danny Wild                          danny wilde  0.952   403829
524                 Terence Trent D’Arby                 terence trent d'arby  0.950    36030
390                 David Clayton‐Thomas                 david clayton-thomas  0.950   219919
258                “Brother” Jack McDuff                  brother jack mcduff  0.950     5381
125                 Fun Lovin’ Criminals                 fun lovin' criminals  0.950     9889

In [79]:
exact_null = exact[exact['musicbrainz_artist_id'].isna()]
exact_conflict = exact[exact['musicbrainz_artist_id'].notna() & 
                       (exact['musicbrainz_artist_id'].astype('Int64') != exact['id'].astype('Int64'))]

print(f"Safe fills (currently NaN): {len(exact_null)}")
print(f"Conflicts (have different ID already): {len(exact_conflict)}")
print("\nConflicts:")
print(exact_conflict[['name_x', 'name_y', 'id', 'musicbrainz_artist_id']].to_string())

Safe fills (currently NaN): 71
Conflicts (have different ID already): 53

Conflicts:
                    name_x                 name_y       id  musicbrainz_artist_id
6                     Maná                   mana     1319                1086595
10           John Williams          john williams       94                2788464
11                 ROSALÍA                rosalia  1388488                2308830
12                   Aminé                  amine  1404279                3001020
13                  MARINA                 marina   596594                2430288
20                  Plan B                 plan b   379514                 379522
22                    EDEN                   eden  1356579                3069181
23                  AURORA                 aurora  1216723                 244616
31                  Plan B                 plan b   379520                 379522
32                    Five                   five      800                1928117
34                  Thalía                 thalia   116401                2497618
35   Engelbert Humperdinck  engelbert humperdinck    43566                 323769
38                     Eve                    eve    11664                1819048
41                     Mýa                    mya     3106                2040581
43                  Alemán                 aleman  1745960                2312477
44                    Nena                   nena   242220                2534753
47          Changing Faces         changing faces    22444                1255916
48                    LÉON                   leon  1339591                1474644
54                   Monty                  monty  1257493                2859045
58                   Dream                  dream  2116044                1937907
61                   Sandy                  sandy   581910                 296373
70          Marilyn Manson         marilyn manson   255235                    187
72            Chanté Moore           chante moore      473                2862287
73           José González          jose gonzalez   119552                2460249
74                    Kali                   kali   862749                2848174
77              Steve Lacy             steve lacy  1467181                 249403
78           John Williams          john williams   238569                2788464
79                  Aurora                 aurora   244623                 244616
82                    Nena                   nena     1894                2534753
83                    Mina                   mina    32092                1365950
84          James Morrison         james morrison    32583                 375655
85                     Dio                    dio     1443                 483466
86                  Exposé                 expose   179806                1283484
89                  Brandy                 brandy   141191                   9341
91            Nancy Wilson           nancy wilson    32799                 286239
94          Robert Johnson         robert johnson   270862                 287815
97              Juan Vélez             juan velez   664916                2938534
99                   Raven                  raven     5597                2141937
101         Robert Johnson         robert johnson     6442                 287815
102                   EDEN                   eden  1926821                3069181
106                  dream                  dream   259886                1937907
107                   Kali                   kali  1012758                2848174
108                    Eve                    eve  1450060                1819048
110          Natalie Grant          natalie grant    32893                2124315
111                 marina                 marina   705232                2430288
112                    EVE                    eve  1981344                1819048
113                   MINA                   mina  1857234                1365950
115                    Air                    air   419866                2353616
116                    Air                    air      911                2353616
118                  Chloé                  chloe   163676                1852154
119                  Monty                  monty  1437178                2859045
121                  Sandy                  sandy   296391                 296373
123                   Kali                   kali   812834                2848174

In [80]:
# Flag kang names that appear multiple times (ambiguous)
kang_name_counts = df_kang_data_w_spotify.groupby(
    df_kang_data_w_spotify['name'].str.lower().str.strip()
)['id'].count()

exact_conflict['name_lower'] = exact_conflict['name_x'].str.lower().str.strip()
exact_conflict['kang_count'] = exact_conflict['name_lower'].map(kang_name_counts)

genuine = exact_conflict[exact_conflict['kang_count'] == 1]
dupes   = exact_conflict[exact_conflict['kang_count'] > 1]

print(f"Genuine single-artist conflicts: {len(genuine)}")
print(f"Duplicate-name conflicts (skip): {len(dupes)}")
print("\nGenuine conflicts to check:")
print(genuine[['name_x', 'id', 'musicbrainz_artist_id']].to_string())

Genuine single-artist conflicts: 12
Duplicate-name conflicts (skip): 41

Genuine conflicts to check:
            name_x       id  musicbrainz_artist_id
6             Maná     1319                1086595
11         ROSALÍA  1388488                2308830
12           Aminé  1404279                3001020
34          Thalía   116401                2497618
41             Mýa     3106                2040581
43          Alemán  1745960                2312477
48            LÉON  1339591                1474644
72    Chanté Moore      473                2862287
73   José González   119552                2460249
86          Exposé   179806                1283484
97      Juan Vélez   664916                2938534
118          Chloé   163676                1852154

/var/folders/1v/h2vyfq9j45n9_tmm_gg2s8tm0000gn/T/ipykernel_84425/1698888728.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exact_conflict['name_lower'] = exact_conflict['name_x'].str.lower().str.strip()
/var/folders/1v/h2vyfq9j45n9_tmm_gg2s8tm0000gn/T/ipykernel_84425/1698888728.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exact_conflict['kang_count'] = exact_conflict['name_lower'].map(kang_name_counts)

In [81]:
import subprocess
artist_path = '/Users/jamesemcnally/musicbrainz_data/mbdump/artist'

for _, row in genuine.iterrows():
    print(f"\n=== {row['name_x'].upper()} ===")
    for label, mbid in [('ours', int(row['musicbrainz_artist_id'])), ('kang', int(row['id']))]:
        result = subprocess.run(['grep', f'^{mbid}\t', artist_path], capture_output=True, text=True)
        if result.stdout:
            fields = result.stdout.strip().split('\t')
            print(f"  {label} (id={mbid}): name='{fields[2]}', comment='{fields[13]}'")
        else:
            print(f"  {label} (id={mbid}): NOT FOUND")

=== MANÁ ===
  ours (id=1086595): name='Mana', comment='Ron Rüegg, Thom Egli, Claudio Catatore & Mathis Roth'
  kang (id=1319): name='Maná', comment='Mexican rock group'

=== ROSALÍA ===
  ours (id=2308830): name='Rosalia', comment='appears on a Fito Páez tribute album'
  kang (id=1388488): name='ROSALÍA', comment='Spanish singer'

=== AMINÉ ===
  ours (id=3001020): name='amine', comment='yedits'
  kang (id=1404279): name='Aminé', comment='rapper from Portland, OR'

=== THALÍA ===
  ours (id=2497618): name='Thalia', comment='South Korean duo'
  kang (id=116401): name='Thalía', comment='Mexican singer and actress'

=== MÝA ===
  ours (id=2040581): name='MYA', comment='Argentine duo (Maxi y Agus)'
  kang (id=3106): name='Mýa', comment=''

=== ALEMÁN ===
  ours (id=2312477): name='Aleman', comment='Spanish rapper'
  kang (id=1745960): name='Alemán', comment='Mexican rapper'

=== LÉON ===
  ours (id=1474644): name='LEON', comment='Japanese Drummer'
  kang (id=1339591): name='LÉON', comment='Swedish singer'

=== CHANTÉ MOORE ===
  ours (id=2862287): name='Chante Moore', comment='appears on Damion Hall's track'
  kang (id=473): name='Chanté Moore', comment=''

=== JOSÉ GONZÁLEZ ===
  ours (id=2460249): name='Jose Gonzalez', comment='folk, track “Alborea”'
  kang (id=119552): name='José González', comment='Swedish singer-songwriter and guitarist'

=== EXPOSÉ ===
  ours (id=1283484): name='Expose', comment='early '80s act?'
  kang (id=179806): name='Exposé', comment='’80s dance-pop trio'

=== JUAN VÉLEZ ===
  ours (id=2938534): name='Juan Velez', comment='appears on Edgar Rene's track'
  kang (id=664916): name='Juan Vélez', comment='Winner of reality show Objectivo Fama'

=== CHLOÉ ===
  ours (id=1852154): name='Chloe', comment='how to be a popstar dancer'
  kang (id=163676): name='Chloé', comment='Chloé Thévenin, French DJ and producer'

In [82]:
fix_map = {
    'maná': 1319, 'rosalía': 1388488, 'aminé': 1404279, 'thalía': 116401,
    'mýa': 3106, 'alemán': 1745960, 'léon': 1339591, 'chanté moore': 473,
    'josé gonzález': 119552, 'exposé': 179806, 'juan vélez': 664916, 'chloé': 163676
}

df_artists['name_lower'] = df_artists['name'].str.lower().str.strip()

for name_lower, correct_id in fix_map.items():
    mask = df_artists['name_lower'].apply(strip_accents) == strip_accents(name_lower)
    df_artists.loc[mask, 'musicbrainz_artist_id'] = correct_id

df_artists = df_artists.drop(columns=['name_lower'])

# Now apply the 71 safe fills
fill_map = dict(zip(
    exact_null['name_x'].apply(strip_accents),
    exact_null['id']
))

df_artists['name_norm'] = df_artists['name'].apply(strip_accents)
df_artists.loc[
    df_artists['name_norm'].isin(fill_map) & df_artists['musicbrainz_artist_id'].isna(),
    'musicbrainz_artist_id'
] = df_artists.loc[
    df_artists['name_norm'].isin(fill_map) & df_artists['musicbrainz_artist_id'].isna(),
    'name_norm'
].map(fill_map)
df_artists = df_artists.drop(columns=['name_norm'])

print(f"Applied 12 ID corrections and up to 71 fills.")
print(f"Missing IDs remaining: {df_artists['musicbrainz_artist_id'].isna().sum()}")

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

Applied 12 ID corrections and up to 71 fills.
Missing IDs remaining: 2496
Saved.

In [83]:
# For each near-match with similarity >= 0.95, look up the kang ID in the local MusicBrainz
# dump to verify whether it corresponds to the correct artist before applying any updates.

import subprocess
artist_path = '/Users/jamesemcnally/musicbrainz_data/mbdump/artist'

high_conf = near_df[near_df['score'] >= 0.95].copy()

for _, row in high_conf.iterrows():
    kang_id = int(row['kang_id'])
    result = subprocess.run(['grep', f'^{kang_id}\t', artist_path], capture_output=True, text=True)
    if result.stdout:
        fields = result.stdout.strip().split('\t')
        mb_name = fields[2]
        mb_comment = fields[13]
    else:
        mb_name, mb_comment = 'NOT FOUND', ''
    
    print(f"kang: '{row['kang_name']}' | df match: '{row['df_match']}' | MB: '{mb_name}' | comment: '{mb_comment}'")

kang: 'Noel Gallagher’s High Flying Birds' | df match: 'noel gallagher's high flying birds' | MB: 'Noel Gallagher’s High Flying Birds' | comment: ''
kang: 'The Clayton‐Hamilton Jazz Orchestra' | df match: 'the clayton/hamilton jazz orchestra' | MB: 'The Clayton–Hamilton Jazz Orchestra' | comment: ''
kang: 'RTÉ National Symphony Orchestra' | df match: 'the national symphony orchestra' | MB: 'RTÉ National Symphony Orchestra' | comment: ''
kang: 'Dharohar Project' | df match: 'dharoha project' | MB: 'Dharohar Project' | comment: ''
kang: 'Andrew Williams' | df match: 'andre williams' | MB: 'Andrew Williams' | comment: 'member of Gravity Noir'
kang: 'Andreas Martin' | df match: 'andrea martin' | MB: 'Andreas Martin' | comment: 'German schlager singer'
kang: 'Northernlight' | df match: 'northern light' | MB: 'Northernlight' | comment: 'Belgian ensemble, cfr Edding Quartet'
kang: 'The Residents' | df match: 'the presidents' | MB: 'The Residents' | comment: 'avant‐garde experimental group'
kang: 'Sérgio Mendes & Brasil ’66' | df match: 'sergio mendes & brasil '66' | MB: 'Sérgio Mendes & Brasil ’66' | comment: ''
kang: 'Manfred Mann’s Earth Band' | df match: 'manfred mann's earth band' | MB: 'Manfred Mann’s Earth Band' | comment: ''
kang: 'Iain Matthews' | df match: 'ian matthews' | MB: 'Iain Matthews' | comment: 'member of Matthews’ Southern Comfort'
kang: 'The All‐American Rejects' | df match: 'the all-american rejects' | MB: 'The All‐American Rejects' | comment: 'US rock band'
kang: 'Trans‐Siberian Orchestra' | df match: 'trans-siberian orchestra' | MB: 'Trans‐Siberian Orchestra' | comment: ''
kang: 'Bachman–Turner Overdrive' | df match: 'bachman-turner overdrive' | MB: 'Bachman–Turner Overdrive' | comment: ''
kang: 'Michael Gray' | df match: 'michael ray' | MB: 'Michael Gray' | comment: 'UK house DJ/producer'
kang: 'James Young' | df match: 'jaymes young' | MB: 'James Young' | comment: 'has several albums with Chris Constantinou'
kang: 'Constantines' | df match: 'constantine' | MB: 'Constantines' | comment: ''
kang: 'Paula Kelly' | df match: 'paul kelly' | MB: 'Paula Kelly' | comment: 'big band jazz singer'
kang: 'Compton’s Most Wanted' | df match: 'compton's most wanted' | MB: 'Compton’s Most Wanted' | comment: ''
kang: 'DANGERDOOM' | df match: 'danger doom' | MB: 'DANGERDOOM' | comment: ''
kang: 'Danny Wild' | df match: 'danny wilde' | MB: 'Danny Wild' | comment: 'French electro/house/club DJ & producer'
kang: 'Terence Trent D’Arby' | df match: 'terence trent d'arby' | MB: 'Terence Trent D’Arby' | comment: 'now known as Sananda Maitreya'
kang: 'David Clayton‐Thomas' | df match: 'david clayton-thomas' | MB: 'David Clayton‐Thomas' | comment: ''
kang: '“Brother” Jack McDuff' | df match: 'brother jack mcduff' | MB: '“Brother” Jack McDuff' | comment: ''
kang: 'Fun Lovin’ Criminals' | df match: 'fun lovin' criminals' | MB: 'Fun Lovin’ Criminals' | comment: ''

In [84]:
# Apply kang IDs for all 14 verified near-matches.
# For Dharohar Project, also fix the typo in the name.

correct_near_matches = {
    "noel gallagher's high flying birds": 819312,
    "sergio mendes & brasil '66":         31816,
    "manfred mann's earth band":          12076,
    "the all-american rejects":           58875,
    "trans-siberian orchestra":           11727,
    "bachman-turner overdrive":           1672,
    "compton's most wanted":              118983,
    "danger doom":                        255478,
    "terence trent d'arby":               36030,
    "david clayton-thomas":               219919,
    "brother jack mcduff":                5381,
    "fun lovin' criminals":               9889,
    "ian matthews":                       30721,
    "dharoha project":                    741945,  # typo — also fix name below
}

df_artists['name_norm'] = df_artists['name'].apply(normalize_name)

for name_norm, correct_id in correct_near_matches.items():
    mask = df_artists['name_norm'] == normalize_name(name_norm)
    df_artists.loc[mask & df_artists['musicbrainz_artist_id'].isna(), 'musicbrainz_artist_id'] = correct_id

# Fix Dharohar Project typo
df_artists.loc[df_artists['name_norm'] == normalize_name('dharoha project'), 'name'] = 'dharohar project'

df_artists = df_artists.drop(columns=['name_norm'])

print(f"Missing IDs remaining: {df_artists['musicbrainz_artist_id'].isna().sum()}")
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

Missing IDs remaining: 2483
Saved.

In [85]:
# Check the top 1000 most popular artists in kang against df_artists by ID,
# then flag any that are missing or unmatched.

top1000 = df_kang_data_w_spotify.nlargest(1000, 'popularity')[['id', 'name', 'popularity']].copy()

df_artist_ids = set(df_artists['musicbrainz_artist_id'].dropna().astype(int))

top1000['in_df_artists'] = top1000['id'].isin(df_artist_ids)

in_df   = top1000[top1000['in_df_artists']]
not_in_df = top1000[~top1000['in_df_artists']]

print(f"Top 1000 kang artists by popularity")
print(f"  Found in df_artists by ID: {len(in_df)}")
print(f"  Not found:                 {len(not_in_df)}")
print("\nNot found:")
print(not_in_df[['name', 'id', 'popularity']].to_string())

Top 1000 kang artists by popularity
  Found in df_artists by ID: 727
  Not found:                 273

Not found:
                                         name       id  popularity
187                          Marília Mendonça  1309563        89.0
276                             Lenny Tavárez  1079251        88.0
137                                     JAY‐Z      167        87.0
363                                      Duki  1670724        87.0
431                              Arijit Singh   868677        87.0
885                             María Becerra  2009378        87.0
268                           Henrique Albino  1030105        85.0
381                                     Ninho  1252793        85.0
262                             Gusttavo Lima   804367        84.0
346                                       Jul  1083137        84.0
467                          Maiara & Maraisa  1311809        84.0
1425                                   Pritam   368737        84.0
1892                             Nicki Nicole  1839802        84.0
6948                            Santa Fe Klan  2090996        84.0
219                            Jorge & Mateus   577669        83.0
225                                     Dalex  1644516        83.0
270                                      Alok   713629        83.0
274                                     Morat  1503351        83.0
490                          Ludovico Einaudi    34802        83.0
505                                    Rels B  1505352        83.0
2051                                     Pnau    39366        83.0
2807                                Zé Felipe   665128        83.0
144                             Guns N’ Roses     1440        82.0
248                                     Ne‐Yo   304981        82.0
305                            Wisin & Yandel   157342        82.0
388                          Lost Frequencies  1179459        82.0
647                               Jay Wheeler  1974150        82.0
721                                    Aitana  1663900        82.0
1200                               Anne‐Marie  1247518        82.0
1670                                     Tini   917633        82.0
63                                     G‐Eazy   867864        81.0
121                  Bob Marley & The Wailers   232732        81.0
260                       Zé Neto & Cristiano  1318006        81.0
508                                    T‐Pain   294212        81.0
553                                C. Tangana   809281        81.0
2059                    Johann Sebastian Bach     2327        81.0
3197                           Shreya Ghoshal   198731        81.0
3409                                   Trueno  2018750        81.0
3412                               Lit Killah  1782325        81.0
5173                                     Xamã  1774552        81.0
5217                            PEDRO SAMPAIO  1839814        81.0
6618                           Tanishk Bagchi  1337899        81.0
7201                               Steve Lacy  1467181        81.0
14712                     Anirudh Ravichander   851111        81.0
172                                 blink‐182      241        80.0
236                              Paulo Londra  1637497        80.0
291                               Hans Zimmer      202        80.0
377                                     R3HAB   626805        80.0
390                               Danny Ocean  1689884        80.0
497                                      KHEA  1747885        80.0
530                                   El Alfa  1282361        80.0
16743                                Cavetown  1600180        80.0
21639                          Shiloh Dynasty  1626646        80.0
331                              Matheus Mota  1277539        79.0
425                                RAF Camora   777891        79.0
463                                Becky Hill   975013        79.0
475                    Os Barões da Pisadinha  2103723        79.0
477                                  Bonez MC  1243587        79.0
482                                   Imanbek  1975382        79.0
486                                    MARINA   596594        79.0
542                                    MEDUZA  1784564        79.0
556                             Sfera Ebbasta  1366235        79.0
600                               El Fantasma  1591256        79.0
643                           Fryderyk Chopin       83        79.0
745                        Natalia Lafourcade    78755        79.0
771                   Wolfgang Amadeus Mozart    11285        79.0
788                             Ludmilla Dabo  1162500        79.0
1143                                    Morad  2094779        79.0
1632                              Gabry Ponte    46521        79.0
2120                            Gloria Groove  1438142        79.0
3211                           Jubin Nautiyal  1170661        79.0
3588                           D-Block Europe  1646833        79.0
18184                                [Disney]      104        79.0
252                                   Piso 21  1425714        78.0
325                        Lin‐Manuel Miranda   650387        78.0
344                             Pablo Alborán   799435        78.0
428                               Mau y Ricky  1574933        78.0
435                                 Sam Feldt  1167607        78.0
448                                Jesse Cook   497122        78.0
464                                 Jax Jones  1099337        78.0
520                                  Brytiago  1489816        78.0
544                                     Damso  1296270        78.0
607                              Luan Santana   727129        78.0
649                               Danna Paola   645007        78.0
738                                  Dilsinho  1678838        78.0
801                                    Neffex  1583680        78.0
808                               Luísa Sonza  1616649        78.0
820                                Ghostemane  1502637        78.0
917                                    AURORA  1216723        78.0
918                           Vintage Culture  1279452        78.0
1050                                DJ Nelson   157557        78.0
1129                                   Plan B   379520        78.0
1477                              Dímelo Flow  1644514        78.0
2793                              Gué Pequeno   813145        78.0
2868                                     Naps  1509328        78.0
3022                                  OrelSan   598358        78.0
3192                                  Luciano  1570417        78.0
3419                                  L-Gante  2181535        78.0
3551                                Marracash   537018        78.0
5636                                    Matuê  1839422        78.0
6576                                     Vald  1060078        78.0
21960                              White 2115  1575941        78.0
203                               Felix Jaehn  1088095        77.0
294                               Tones and I  1834232        77.0
406                                     alt‐J   818141        77.0
410                               Soda Stereo    20861        77.0
414                                    Sigala  1260481        77.0
455                                       PNL  1208783        77.0
498                                   Stormzy  1138147        77.0
564                                    Noriel  1489813        77.0
633                                 Tom Odell   931159        77.0
640                               Stefan Wolf   118813        77.0
712                                 Alex Rose  1569763        77.0
827                                        IU   577425        77.0
1701                                    Cazzu  1677067        77.0
2124                             MC Cabelinho  1774535        77.0
3205                                  Badshah  1034926        77.0
3342                                     Gzuz  1243606        77.0
6266                              Alka Yagnik    95076        77.0
6973                                  TAEYEON  1143538        77.0
9075                                Yung Lean  1010605        77.0
13216                              Atif Aslam   289679        77.0
18718                                Eyedress  1092164        77.0
21460                                  Białas   855447        77.0
21749                    The Living Tombstone   881595        77.0
21959                                   Lanek  1575936        77.0
22208                                  Bedoes   960805        77.0
184                            Mumford & Sons   567175        76.0
256                               Capital Bra  1621012        76.0
279                                Ryan Lewis   856625        76.0
387                              Boyce Avenue   595413        76.0
397                             John Williams       94        76.0
454                                    Ufo361  1122395        76.0
525                                    Gimson  1860445        76.0
566                          Cali y El Dandee   868899        76.0
570                                   Melendi   163502        76.0
576                                      Sido   152721        76.0
632                                    Nekfeu   828457        76.0
684                           Bruno & Marrone    69148        76.0
702                               Mon Laferte  1289227        76.0
717                                     Ezhel  1236601        76.0
834                               Max Richter   152260        76.0
839                             Timmy Trumpet   856920        76.0
866                                       Cro   859384        76.0
877                                 The Score  1206099        76.0
887                                  Two Feet  1377277        76.0
1175                                   Angèle  1566722        76.0
1215                                   Shouse  2022732        76.0
1609                           Mariah Angeliq  2028914        76.0
1819                                     VIZE  1736638        76.0
2066                     Ludwig van Beethoven     1021        76.0
3413                             Nathy Peluso  1549790        76.0
3550                                  Mahmood   397681        76.0
3617                                 Ofenbach  1253088        76.0
3700                     Purple Disco Machine  1123224        76.0
5399                                    LUM!X  1840901        76.0
6263                             Udit Narayan   113239        76.0
10188                         Lata Mangeshkar     3806        76.0
10194                              Asees Kaur  1232939        76.0
10445                                     PLK  1789871        76.0
16047                                Toby Fox   861681        76.0
436                           Destiny’s Child      468        75.0
437                                 JP Cooper   913502        75.0
546                                     Samra  1717882        75.0
584                                  Goodboys  1808875        75.0
616                                 Halfcrash   159756        75.0
651                                       Zoé   320853        75.0
678                                     Niska  1270576        75.0
692                         Charlie Brown Jr.    39285        75.0
699                                 AJ Tracey  1247252        75.0
760                                   Greeicy  1556586        75.0
780                               Sofía Reyes  1167241        75.0
782                            Jowell & Randy   268788        75.0
884                                       SCH  1302355        75.0
930                            Official髭男dism  1366936        75.0
971                                Tion Wayne  1314088        75.0
1138                               Miky Woodz  1489817        75.0
1417                              Sasha Sloan  1279526        75.0
1444                                Lil Tracy  1472889        75.0
2946                                    C.R.O  1801292        75.0
3442                  Berliner Philharmoniker    64981        75.0
3576                                     OBOY  1838702        75.0
5503                            Russ Millions  2052448        75.0
6258                          Sunidhi Chauhan   113246        75.0
8387                             Night Lovell  1351238        75.0
8637                       Yuvan Shankar Raja   256372        75.0
10172                                    Gazo  2007280        75.0
10180                                B. Praak  1713910        75.0
14883                                  Dardan  1570808        75.0
16708                    Strange Fruits Music  2188287        75.0
21462                                    Mata  1926050        75.0
449                 Dimitri Vegas & Like Mike  1112124        74.0
484                                Juan Magán   327907        74.0
579                                        MØ   933539        74.0
661                                     Booba   155855        74.0
663                             Gente de Zona   693689        74.0
689                              Kevin Roldán  1257763        74.0
696                                   Guaynaa  1823875        74.0
735                                 Chia Chou    35536        74.0
756                            Olivia O’Brien  1360635        74.0
857                                     Dadju  1033018        74.0
888    La Adictiva Banda San José de Mesillas  1147225        74.0
1051                                     Inna   566619        74.0
1187                              Tom Grennan  1336733        74.0
2792                              Dulce María   753827        74.0
3208                            Darshan Raval  1290700        74.0
3278                                 grandson  1646087        74.0
3416                              Dread Mar-I   507275        74.0
3589                                    Riton   110347        74.0
3921                          Antonio Vivaldi    24465        74.0
4114                                 Koba LaD  1662313        74.0
4197                                  Dubdogz  1959796        74.0
5361                                Sub Urban  1866795        74.0
6235                                       KK   691256        74.0
7076                              Beach Bunny  1610431        74.0
8844                                     Nimo  1333558        74.0
11586                          Vishal-Shekhar    95105        74.0
21688                         Hippie Sabotage  1101713        74.0
512                              Aya Nakamura  1309920        73.0
528                            Rag’n’Bone Man  1321872        73.0
572                                  Astrid S  1232655        73.0
605                                  Kontra K   904328        73.0
621                                Apache 207  1847605        73.0
630                           Gigi D’Agostino    32111        73.0
799                            Oliver Heldens  1085653        73.0
823                              Álvaro Soler  1244667        73.0
824                            Gustavo Cerati    40676        73.0
840                                     BØRNS  1177894        73.0
845                             Simone Simone  1362611        73.0
907                       Los Enanitos Verdes    41061        73.0
919                                   Bunbury    22572        73.0
933                          Ricardo Montaner    35481        73.0
940                             Brooks & Dunn     2351        73.0
945                                 Micro TDH  1669173        73.0
953                       Soulja Boy Tell ’Em   457542        73.0
970                                     Aitch  1746665        73.0
1054                                    Fuego   813904        73.0
1140                                     Ñejo   148109        73.0
1443                                ZillaKami  1592507        73.0
1590                               Скриптонит  1325354        73.0
1693                          Sueco the Child  1898281        73.0
1700                               Rafa Pabön  1529531        73.0
1820                                    Leony  2020514        73.0
2064                           Claude Debussy    10341        73.0
2110                           Corpse Husband  2057118        73.0
2128                            Maite Perroni   968756        73.0
2209                         Evaluna Montaner  1574677        73.0
2582                                   Jamule  1775683        73.0
2588                                Dennis DJ   157093        73.0
2806                                 Ana Mena  1493271        73.0
2863                                  Digga D  1811791        73.0
3213                              Tulsi Kumar   392037        73.0
3583                                  Fonseca   193907        73.0
3674                                  SLANDER  1291378        73.0
3732                    Пётр Ильич Чайковский   122653        73.0
5216                                     Gaab  1774551        73.0
5463                           Marilyn Manson   255235        73.0
5542                            Pablo Chill-E  1839811        73.0
5688                                   Masego  1322399        73.0
6153                                    Anahí    99666        73.0
6277                                   kizaru  1538712        73.0
9062                                     SYML  1506031        73.0
9702                                      WOS  1770097        73.0
10192                          Diljit Dosanjh  1034925        73.0
12410                             Neeti Mohan   951353        73.0
12609                       Shankar Mahadevan    55833        73.0
13156                        Christian Chávez  1113254        73.0
13866                           Big Baby Tape  1683286        73.0
14816                                (G)I‐DLE  1653740        73.0
17019                                    Ruel  1563545        73.0
17263                                   Luude  1687475        73.0
18236                                     Eve  1450060        73.0
18382                                  LEE HI   939588        73.0

In [86]:
# Find Jay Z in kang and jay-z in df_artists, then verify and fix

jay_z_kang = df_kang_data_w_spotify[df_kang_data_w_spotify['name'].str.lower().str.strip().isin(['jay z', 'jay-z', 'jay‐z'])]
print("Kang entries:")
print(jay_z_kang[['id', 'name', 'popularity']].to_string())

jay_z_df = df_artists[df_artists['name'].str.lower().str.contains('jay.z', regex=True, na=False)]
print("\ndf_artists entries:")
print(jay_z_df[['name', 'musicbrainz_artist_id']].to_string())

Kang entries:
      id   name  popularity
137  167  JAY‐Z        87.0

df_artists entries:
                                  name  musicbrainz_artist_id
2134  changing faces (featuring jay-z)                   <NA>
5563                             jay z                2133824
5564                  jay z kanye west                   <NA>
5565                             jay-z                   <NA>
5566               jay-z + alicia keys                   <NA>
5567                jay-z + mr. hudson                   <NA>
5568               jay-z + swizz beatz                   <NA>
5569                 jay-z/linkin park                   <NA>
6391                  kanye west jay z                   <NA>
7935           memphis bleek (& jay-z)                   <NA>
8400     nas, jay-z & james fauntleroy                   <NA>

In [87]:
result = subprocess.run(['grep', f'^167\t', artist_path], capture_output=True, text=True)
print(result.stdout.strip())

167	f82bcf78-5b69-4622-a5ef-73800768d9ac	JAY‐Z	Jay‐Z	1969	12	4	\N	\N	\N	1	222	1	US rapper	0	2026-01-19 23:00:22.986872+00	f	10861	\N

In [88]:
# Fix both "jay z" (wrong ID) and "jay-z" (no ID) to point to JAY-Z id=167
df_artists.loc[df_artists['name'] == 'jay z', 'musicbrainz_artist_id'] = 167
df_artists.loc[df_artists['name'] == 'jay-z', 'musicbrainz_artist_id'] = 167

# Verify
print(df_artists[df_artists['name'].isin(['jay z', 'jay-z'])][['name', 'musicbrainz_artist_id']])

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

       name  musicbrainz_artist_id
5563  jay z                    167
5565  jay-z                    167
Saved.

In [90]:
# Rank df_artists by top_10_song_count (fallback: total_charting_songs) 
# and check whether their IDs exist and match in kang's df.

kang_id_map = df_kang_data_w_spotify.set_index('id')[['name', 'popularity', 'spotifyid', 'genres']].copy()

top500_df = df_artists.nlargest(500, ['top_10_song_count', 'top_10_album_count'])[
    ['name', 'musicbrainz_artist_id', 'top_10_song_count']
].copy()

top500_df['musicbrainz_artist_id_int'] = top500_df['musicbrainz_artist_id'].astype('Int64')

top500_df['in_kang']    = top500_df['musicbrainz_artist_id_int'].isin(kang_id_map.index)
top500_df['kang_name']  = top500_df['musicbrainz_artist_id_int'].map(kang_id_map['name'])
top500_df['kang_popularity'] = top500_df['musicbrainz_artist_id_int'].map(kang_id_map['popularity'])

no_id      = top500_df[top500_df['musicbrainz_artist_id'].isna()]
not_in_kang = top500_df[top500_df['musicbrainz_artist_id'].notna() & ~top500_df['in_kang']]
in_kang    = top500_df[top500_df['in_kang']]

print(f"Top 500 df_artists by top-10 song count:")
print(f"  Synced with kang (ID match): {len(in_kang)}")
print(f"  Have ID but not in kang:     {len(not_in_kang)}")
print(f"  No musicbrainz_artist_id:    {len(no_id)}")

print("\nHave ID but not in kang:")
print(not_in_kang[['name', 'musicbrainz_artist_id', 'top_10_song_count']].to_string())

print("\nNo ID at all:")
print(no_id[['name', 'top_10_song_count']].to_string())

Top 500 df_artists by top-10 song count:
  Synced with kang (ID match): 367
  Have ID but not in kang:     93
  No musicbrainz_artist_id:    40

Have ID but not in kang:
                                     name  musicbrainz_artist_id  top_10_song_count
5025                        his orchestra                2915183                 12
1471                          bobby brown                1294129                  9
9792                         ricky nelson                 386382                  9
271                            air supply                    181                  8
11828                 the dave clark five                  37411                  8
5356                              ja rule                    513                  7
9027                          paula abdul                   2577                  7
11475                   the 5th dimension                  22990                  7
11346                        taylor dayne                   2791                  7
12417                         the monkees                  14793                  6
5506                                janet                 616728                  6
12349               the mamas & the papas                  10938                  6
4948                          helen reddy                  21668                  6
9265                               poison                 317289                  6
1654                                bread                  12679                  6
1963                   captain & tennille                  67118                  6
530                             andy gibb                  33347                  6
12096                       the guess who                3060343                  6
1250                        billy preston                  74761                  6
1510                         bobby rydell                  69494                  6
4254                       frankie avalon                  42565                  6
10771                               sonny                1938947                  6
12675              the righteous brothers                 381874                  6
13287                           tommy roe                  38594                  6
14023                              xscape                  35883                  6
1453                            bob seger                   9272                  5
5754                            jim croce                  11072                  5
3416                           don henley                    997                  5
10685              sly & the family stone                  16186                  5
3077                        debbie gibson                   2701                  5
9782                     rick springfield                   9696                  5
8121                        milli vanilli                   9572                  5
9766                          rick astley                  32667                  5
11175                            survivor                1601408                  5
12953                         the turtles                1526260                  5
4445                         gary puckett                 213329                  5
9950                         roger miller                 440952                  5
12214                            the jets                2834262                  5
12863                      the stylistics                  37917                  5
5870                                  joe                2274249                  4
1092                         bette midler                   9262                  4
6499                          keith sweat                  11667                  4
11690                            the cars                   1434                  4
2649                                creed                 613335                  4
3937                                  eve                1819048                  4
2809                        dan fogelberg                    125                  4
4693                     gordon lightfoot                    430                  4
8501                          new edition                    122                  4
13948                     wilson phillips                    162                  4
209                           ace of base                  11214                  4
1513                        bobby sherman                  76097                  4
2141                        chappell roan                1616071                  4
12524                         the osmonds                 125255                  4
13151                             tiffany                2399834                  4
2959                        david cassidy                  58632                  4
3095                        dee dee sharp                  49871                  4
3509                             dr. hook                  22155                  4
3683                        eddie rabbitt                  47672                  4
3834        england dan & john ford coley                  99543                  4
4723                           grand funk                2631052                  4
5184                            ice spice                2391333                  4
5376                           jack scott                2603902                  4
5549                  jay & the americans                  53565                  4
6102                     johnny tillotson                  42228                  4
6255                         juice newton                   2635                  4
6411                          karyn white                  59391                  4
7694                         mark lindsay                  21670                  4
9575                          ray stevens                2049607                  4
9778                          rick nelson                  10439                  4
11022                      steve lawrence                1014543                  4
12650                          the rebels                2917022                  4
13003                          the vogues                1785241                  4
13332                        tony orlando                  70008                  4
5415                          jagged edge                 240037                  3
14179                          zach bryan                1914090                  3
1454   bob seger & the silver bullet band                  10271                  3
7805                      matchbox twenty                   1959                  3
10986                         steppenwolf                   1699                  3
1597                              bow wow                  11668                  3
5063                               hootie                1331210                  3
10082                               rufus                2222392                  3
11651                the brothers johnson                  40951                  3
1765            bruce hornsby & the range                 199997                  3
10281                       savage garden                    155                  3
10458                       shaun cassidy                  96591                  3
13781                             warrant                   2711                  3
682                  arrested development                    952                  3
2523                        color me badd                  44320                  3
3560                             dru hill                  11994                  3
5854          joan jett & the blackhearts                  10699                  3
6297                            jung kook                1169769                  3
7095         lil jon & the east side boyz                 114813                  3
8298                           mr. mister                  22396                  3

No ID at all:
                                    name  top_10_song_count
8750                  olivia newton-john                 15
11249                             t-pain                 15
11471                      the 4 seasons                 15
5118               huey lewis & the news                 12
8445                               ne-yo                 11
4979                    herman's hermits                 11
3189                     destiny's child                 10
11595                the black eyed peas                 10
6470                               ke$ha                 10
5394                           jackson 5                  8
11456       the "sound of frankie valli"                  8
4608          gladys knight and the pips                  7
9393                          puff daddy                  7
4434         gary lewis and the playboys                  7
12325                the lovin' spoonful                  7
13278      tommy james and the shondells                  7
4802                       guns n' roses                  6
15                               'n sync                  6
9345           prince and the revolution                  6
12499                         the o'jays                  6
12870                  the sunshine band                  6
7723              martha & the vandellas                  6
9138                  peter, paul & mary                  6
7500                         m.c. hammer                  5
8859                            p. diddy                  5
5440   james brown and the famous flames                  5
12966                      the union gap                  5
8159         missy 'misdemeanor' elliott                  4
9007           paul revere & the raiders                  4
129                           98 degrees                  4
4064                  ferrante & teicher                  4
13073                  the young rascals                  4
1538                bone thugs-n-harmony                  3
3312                        dixie chicks                  3
12845              the steve miller band                  3
11610                       the blowfish                  3
6340                                k-ci                  3
397                            all-4-one                  3
4576                  gilbert o'sullivan                  3
7211              lisa lisa and cult jam                  3

In [91]:
df_artists = df_artists[~df_artists['name'].isin(['his orchestra', 'joe'])]
print(f"df_artists shape after removal: {df_artists.shape}")
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

df_artists shape after removal: (14224, 53)
Saved.

In [94]:
print(f"Unambiguous matches: {len(unambig)}")
print(unambig[['name_x', 'id', 'top_10_song_count']].to_string())

print("\nNo match:")
print(no_match[['name', 'top_10_song_count']].to_string())

Unambiguous matches: 0
Empty DataFrame
Columns: [name_x, id, top_10_song_count]
Index: []

No match:
                                    name  top_10_song_count
8750                  olivia newton-john                 15
11249                             t-pain                 15
11471                      the 4 seasons                 15
5118               huey lewis & the news                 12
8445                               ne-yo                 11
4979                    herman's hermits                 11
3189                     destiny's child                 10
11595                the black eyed peas                 10
6470                               ke$ha                 10
5394                           jackson 5                  8
11456       the "sound of frankie valli"                  8
4608          gladys knight and the pips                  7
9393                          puff daddy                  7
4434         gary lewis and the playboys                  7
12325                the lovin' spoonful                  7
13278      tommy james and the shondells                  7
4802                       guns n' roses                  6
15                               'n sync                  6
9345           prince and the revolution                  6
12499                         the o'jays                  6
12870                  the sunshine band                  6
7723              martha & the vandellas                  6
9138                  peter, paul & mary                  6
7500                         m.c. hammer                  5
8859                            p. diddy                  5
5440   james brown and the famous flames                  5
12966                      the union gap                  5
8159         missy 'misdemeanor' elliott                  4
9007           paul revere & the raiders                  4
129                           98 degrees                  4
4064                  ferrante & teicher                  4
13073                  the young rascals                  4
1538                bone thugs-n-harmony                  3
3312                        dixie chicks                  3
12845              the steve miller band                  3
11610                       the blowfish                  3
6340                                k-ci                  3
397                            all-4-one                  3
4576                  gilbert o'sullivan                  3
7211              lisa lisa and cult jam                  3

In [97]:
import unicodedata

def normalize_name_v2(name):
    if not isinstance(name, str):
        return ''
    # Normalize unicode apostrophes/quotes to ASCII
    n = name.replace('\u2019', "'").replace('\u2018', "'").replace('\u201c', '"').replace('\u201d', '"').replace('\u2010', '-').replace('\u2013', '-').replace('\u2014', '-')
    n = n.lower().strip()
    n = re.sub(r"[\"'\.&,\-\(\)]", ' ', n)
    n = re.sub(r'\s+', ' ', n).strip()
    return n

# Test
print(normalize_name_v2("Destiny's Child"))
print(normalize_name_v2("Guns N\u2019 Roses"))

# Re-run matching with v2
kang_lookup['name_norm3'] = kang_lookup['name'].apply(normalize_name_v2)
no_id_copy['name_norm3'] = no_id_copy['name'].apply(normalize_name_v2)

matched3 = no_id_copy.merge(kang_lookup, on='name_norm3', how='inner')
counts3 = matched3.groupby('name_norm3')['id'].count().reset_index()
counts3.columns = ['name_norm3', 'match_count']
matched3 = matched3.merge(counts3, on='name_norm3')

unambig3 = matched3[matched3['match_count'] == 1]
print(f"\nUnambiguous matches: {len(unambig3)}")
print(unambig3[['name_x', 'name_y', 'id', 'top_10_song_count']].to_string())

destiny s child
guns n roses

Unambiguous matches: 7
                 name_x                name_y      id  top_10_song_count
0    olivia newton-john    Olivia Newton‐John   11078                 15
1                t-pain                T‐Pain  294212                 15
2                 ne-yo                 Ne‐Yo  304981                 11
3      herman's hermits      Herman’s Hermits    6518                 11
4       destiny's child       Destiny’s Child     468                 10
5         guns n' roses         Guns N’ Roses    1440                  6
6  bone thugs-n-harmony  Bone Thugs‐n‐Harmony   73815                  3

In [98]:
# Verify all 7 kang IDs against the MB dump before applying
for _, row in unambig3.iterrows():
    result = subprocess.run(['grep', f'^{int(row["id"])}\t', artist_path], capture_output=True, text=True)
    fields = result.stdout.strip().split('\t') if result.stdout else []
    mb_name = fields[2] if len(fields) > 2 else 'NOT FOUND'
    mb_comment = fields[13] if len(fields) > 13 else ''
    print(f"id={int(row['id'])}: MB='{mb_name}' | comment='{mb_comment}' | df='{row['name_x']}'")

id=11078: MB='Olivia Newton‐John' | comment='British‐Australian singer, actress and activist' | df='olivia newton-john'
id=294212: MB='T‐Pain' | comment='' | df='t-pain'
id=304981: MB='Ne‐Yo' | comment='' | df='ne-yo'
id=6518: MB='Herman’s Hermits' | comment='English beat rock band, formed in Manchester in 1964' | df='herman's hermits'
id=468: MB='Destiny’s Child' | comment='' | df='destiny's child'
id=1440: MB='Guns N’ Roses' | comment='American hard rock band from Los Angeles' | df='guns n' roses'
id=73815: MB='Bone Thugs‐n‐Harmony' | comment='' | df='bone thugs-n-harmony'

In [99]:
# Check top 1000 df_artists by top-10 song count against kang's df by ID match

top1000_df = df_artists.nlargest(1000, ['top_10_song_count', 'top_10_album_count'])[
    ['name', 'musicbrainz_artist_id', 'top_10_song_count']
].copy()

top1000_df['musicbrainz_artist_id_int'] = top1000_df['musicbrainz_artist_id'].astype('Int64')

kang_ids = set(df_kang_data_w_spotify['id'].dropna().astype(int))

top1000_df['in_kang'] = top1000_df['musicbrainz_artist_id_int'].isin(kang_ids)

in_kang     = top1000_df[top1000_df['in_kang']]
no_id       = top1000_df[top1000_df['musicbrainz_artist_id'].isna()]
has_id_not_in_kang = top1000_df[top1000_df['musicbrainz_artist_id'].notna() & ~top1000_df['in_kang']]

print(f"Top 1000 df_artists by top-10 song count:")
print(f"  Synced with kang:          {len(in_kang)}")
print(f"  Have ID but not in kang:   {len(has_id_not_in_kang)}")
print(f"  No musicbrainz_artist_id:  {len(no_id)}")

print("\nHave ID but not in kang:")
print(has_id_not_in_kang[['name', 'musicbrainz_artist_id', 'top_10_song_count']].to_string())

print("\nNo ID:")
print(no_id[['name', 'top_10_song_count']].to_string())

Top 1000 df_artists by top-10 song count:
  Synced with kang:          636
  Have ID but not in kang:   289
  No musicbrainz_artist_id:  75

Have ID but not in kang:
                                     name  musicbrainz_artist_id  top_10_song_count
1471                          bobby brown                1294129                  9
9792                         ricky nelson                 386382                  9
271                            air supply                    181                  8
11828                 the dave clark five                  37411                  8
5356                              ja rule                    513                  7
9027                          paula abdul                   2577                  7
11475                   the 5th dimension                  22990                  7
11346                        taylor dayne                   2791                  7
12417                         the monkees                  14793                  6
5506                                janet                 616728                  6
12349               the mamas & the papas                  10938                  6
4948                          helen reddy                  21668                  6
9265                               poison                 317289                  6
1654                                bread                  12679                  6
1963                   captain & tennille                  67118                  6
530                             andy gibb                  33347                  6
12096                       the guess who                3060343                  6
1250                        billy preston                  74761                  6
1510                         bobby rydell                  69494                  6
4254                       frankie avalon                  42565                  6
10771                               sonny                1938947                  6
12675              the righteous brothers                 381874                  6
13287                           tommy roe                  38594                  6
14023                              xscape                  35883                  6
1453                            bob seger                   9272                  5
5754                            jim croce                  11072                  5
3416                           don henley                    997                  5
10685              sly & the family stone                  16186                  5
3077                        debbie gibson                   2701                  5
9782                     rick springfield                   9696                  5
8121                        milli vanilli                   9572                  5
9766                          rick astley                  32667                  5
11175                            survivor                1601408                  5
12953                         the turtles                1526260                  5
4445                         gary puckett                 213329                  5
9950                         roger miller                 440952                  5
12214                            the jets                2834262                  5
12863                      the stylistics                  37917                  5
1092                         bette midler                   9262                  4
6499                          keith sweat                  11667                  4
11690                            the cars                   1434                  4
2649                                creed                 613335                  4
3937                                  eve                1819048                  4
2809                        dan fogelberg                    125                  4
4693                     gordon lightfoot                    430                  4
8501                          new edition                    122                  4
13948                     wilson phillips                    162                  4
209                           ace of base                  11214                  4
1513                        bobby sherman                  76097                  4
2141                        chappell roan                1616071                  4
12524                         the osmonds                 125255                  4
13151                             tiffany                2399834                  4
2959                        david cassidy                  58632                  4
3095                        dee dee sharp                  49871                  4
3509                             dr. hook                  22155                  4
3683                        eddie rabbitt                  47672                  4
3834        england dan & john ford coley                  99543                  4
4723                           grand funk                2631052                  4
5184                            ice spice                2391333                  4
5376                           jack scott                2603902                  4
5549                  jay & the americans                  53565                  4
6102                     johnny tillotson                  42228                  4
6255                         juice newton                   2635                  4
6411                          karyn white                  59391                  4
7694                         mark lindsay                  21670                  4
9575                          ray stevens                2049607                  4
9778                          rick nelson                  10439                  4
11022                      steve lawrence                1014543                  4
12650                          the rebels                2917022                  4
13003                          the vogues                1785241                  4
13332                        tony orlando                  70008                  4
5415                          jagged edge                 240037                  3
14179                          zach bryan                1914090                  3
1454   bob seger & the silver bullet band                  10271                  3
7805                      matchbox twenty                   1959                  3
10986                         steppenwolf                   1699                  3
1597                              bow wow                  11668                  3
5063                               hootie                1331210                  3
10082                               rufus                2222392                  3
11651                the brothers johnson                  40951                  3
1765            bruce hornsby & the range                 199997                  3
10281                       savage garden                    155                  3
10458                       shaun cassidy                  96591                  3
13781                             warrant                   2711                  3
682                  arrested development                    952                  3
2523                        color me badd                  44320                  3
3560                             dru hill                  11994                  3
5854          joan jett & the blackhearts                  10699                  3
6297                            jung kook                1169769                  3
7095         lil jon & the east side boyz                 114813                  3
8298                           mr. mister                  22396                  3
8590                              nilsson                2092865                  3
9047                       peaches & herb                  12763                  3
10421                                shai                1258565                  3
37                      1910 fruitgum co.                  24587                  3
226                             adam wade                 156553                  3
741                        atlantic starr                  20486                  3
842                             baby bash                 115052                  3
878                             badfinger                  14641                  3
980                      bay city rollers                  23686                  3
1566                            booker t.                 617728                  3
1657                              breathe                2589141                  3
1693                         brian hyland                  34116                  3
1847                            burl ives                     98                  3
2422                          classics iv                  44914                  3
3122                          del shannon                  16171                  3
3857                          eric burdon                   4222                  3
3858                          eric carmen                    819                  3
3977                               fabian                2973961                  3
4165                         floyd cramer                  33964                  3
4480                       gene mcdaniels                  50266                  3
4987                              hi-five                1897938                  3
5666                         jerry butler                 996842                  3
5912                              joe tex                   5188                  3
6080                        johnny horton                  33453                  3
7273                          lloyd price                  24108                  3
7277                                 lobo                2259466                  3
7368                         lou christie                  48805                  3
8707                          odia coates                 387877                  3
8863                            p.m. dawn                  10944                  3
9053                              pebbles                1337716                  3
9534                           rare earth                  35302                  3
9579                               raydio                  44972                  3
10514                       shirley ellis                  85535                  3
11200                               sweet                2835831                  3
11436                      tevin campbell                  35771                  3
11657                     the buckinghams                  52303                  3
11728                        the chiffons                  12098                  3
11788                        the cowsills                  65735                  3
11806                        the crystals                 838328                  3
11999                      the fleetwoods                  39988                  3
12363                     the marvelettes                  37928                  3
12390                            the mg's                 232275                  3
12520                          the orlons                 120664                  3
2431                           clay aiken                 102192                  2
2906                             daughtry                 404472                  2
871                           bad company                1126603                  2
2662                crosby, stills & nash                  12103                  2
4024                              fat joe                  32814                  2
12635                         the rascals                  24057                  2
301                            al stewart                 605463                  2
885                      bailey zimmerman                2292970                  2
1518                      bobby valentino                 390499                  2
2127                       chamillionaire                 243949                  2
2847                          danity kane                 381638                  2
2992                       david lee roth                   1940                  2
3967                              extreme                2109712                  2
7408                             loverboy                1536581                  2
10071                      ruben studdard                 114624                  2
10341                      seals & crofts                  38028                  2
10619                            skid row                 434475                  2
14155                            yung joc                 352167                  2
154                      a taste of honey                  34126                  2
300                            al martino                   8619                  2
595                  another bad creation                  37479                  2
636                                  aqua                2696528                  2
834                          b.t. express                2074441                  2
1028                       bell biv devoe                  33012                  2
1875                    c+c music factory                  37079                  2
3419                           don mclean                   2970                  2
3861            eric clapton and his band                2385712                  2
3929                               europe                1731346                  2
4084                 fine young cannibals                   1800                  2
4646                             glorilla                2354830                  2
4887                        harold melvin                 104901                  2
4933                             heatwave                1602481                  2
6051                       johnnie taylor                   3718                  2
8572                         night ranger                   2690                  2
8868                         pablo cruise                  62127                  2
9814                        rita coolidge                   4696                  2
9958                       roger williams                1250240                  2
11126                           sugar ray                    370                  2
11615                      the blue notes                1605293                  2
11670                           the byrds                   5794                  2
12302                       the lettermen                  76524                  2
12596                   the power station                  23932                  2
13577                       uncle kracker                   1961                  2
123                                   702                    479                  2
255                               after 7                  79833                  2
449                              ambrosia                 735549                  2
563                             animotion                  20308                  2
566                          anita bryant                  52697                  2
591                               annette                 808963                  2
649              archie bell & the drells                  32888                  2
795                                   awb                1870614                  2
804                                az yet                  36944                  2
872                           bad english                   2675                  2
952                            barry gibb                 125737                  2
1096                        betty everett                  39085                  2
1240                      billy j. kramer                  56981                  2
1358                               blaque                  38761                  2
1403                           blue swede                   3081                  2
1493                          bobby lewis                2303332                  2
2417                      clarence carter                   3722                  2
2473                      clyde mcphatter                  47864                  2
2556                       connie stevens                  69500                  2
2592     cornelius brothers & sister rose                  12775                  2
2779                         dale & grace                  51880                  2
2851                          danny chung                2007693                  2
3007                        david seville                  37902                  2
3156                          dennis yost                 123663                  2
3269                                 dino                2536943                  2
3371                           dobie gray                  30387                  2
3455                 donny & marie osmond                  84200                  2
3680                          eddie money                   1479                  2
4101                            firehouse                1457257                  2
4298                        freddy cannon                  33938                  2
4614                          glass tiger                  15954                  2
4625                           glenn frey                 576576                  2
4854       hamilton, joe frank & reynolds                  21657                  2
4860     hank ballard and the midnighters                 104711                  2
4915                         hayley mills                  45541                  2
5256                  information society                   2358                  2
5384                     jackie deshannon                  16290                  2
5770                         jim stafford                  37968                  2
5793                        jimmy clanton                  16173                  2
5800                           jimmy dean                2898410                  2
5813                          jimmy jones                2960662                  2
5824                         jimmy ruffin                  21264                  2
5927            joey dee & the starliters                  87544                  2
6095                       johnny preston                   8593                  2
6134                           jon secada                   2763                  2
6227                                  jr.                2775350                  2
6228           jr. walker & the all stars                  42507                  2
6272                        julian lennon                   8152                  2
6967                           lee dorsey                  42591                  2
7099                             lil mama                 435271                  2
7181                          linda scott                  95043                  2
7585                          major lance                  84962                  2
7731                              martika                  47106                  2
7753                         marv johnson                  49209                  2
7852                          maxi priest                  35570                  2
7854                   maxine nightingale                  30419                  2
7915                              melanie                2714967                  2
8187                                   mo                2840038                  2

In [100]:
# Apply the 7 kang ID matches found via normalize_name_v2
fill_map_v2 = dict(zip(
    unambig3['name_x'].apply(normalize_name_v2),
    unambig3['id']
))

df_artists['name_norm_v2'] = df_artists['name'].apply(normalize_name_v2)
df_artists.loc[
    df_artists['name_norm_v2'].isin(fill_map_v2) & df_artists['musicbrainz_artist_id'].isna(),
    'musicbrainz_artist_id'
] = df_artists.loc[
    df_artists['name_norm_v2'].isin(fill_map_v2) & df_artists['musicbrainz_artist_id'].isna(),
    'name_norm_v2'
].map(fill_map_v2)

df_artists = df_artists.drop(columns=['name_norm_v2'])
print(f"Applied 7 fills. Missing IDs remaining: {df_artists['musicbrainz_artist_id'].isna().sum()}")

Applied 7 fills. Missing IDs remaining: 2474

In [101]:
# For each remaining no-ID artist in the top 1000, search the MB dump by name.
# Only flag unambiguous matches (exactly one result).

still_no_id = df_artists[
    df_artists['musicbrainz_artist_id'].isna() &
    df_artists['name'].isin(top1000_df['name'])
]['name'].tolist()

mb_results = {}
for name in still_no_id:
    result = subprocess.run(
        ['grep', '-i', f'\t{name}\t', artist_path],
        capture_output=True, text=True
    )
    lines = [l for l in result.stdout.strip().split('\n') if l]
    if len(lines) == 1:
        fields = lines[0].split('\t')
        mb_results[name] = {'id': fields[0], 'mb_name': fields[2], 'comment': fields[13]}
    elif len(lines) > 1:
        mb_results[name] = {'id': None, 'mb_name': f'{len(lines)} matches (ambiguous)', 'comment': ''}

print(f"\nMB lookup results for {len(still_no_id)} artists:")
for name, info in mb_results.items():
    print(f"  '{name}' → id={info['id']}, mb_name='{info['mb_name']}', comment='{info['comment']}'")

KeyboardInterrupt:

In [ ]:
df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print(f"Saved. Shape: {df_artists.shape}")
print(f"Missing musicbrainz_artist_id: {df_artists['musicbrainz_artist_id'].isna().sum()}")

In [102]:
# Re-sync spotify_id, spotify_genres from kang using the now-corrected musicbrainz_artist_ids

kang_sync = df_kang_data_w_spotify[['id', 'spotifyid', 'genres']].copy()
kang_sync['id'] = kang_sync['id'].astype('Int64')
df_artists['musicbrainz_artist_id'] = df_artists['musicbrainz_artist_id'].astype('Int64')

# Update spotify_id and spotify_genres where kang has a match
df_artists = df_artists.merge(
    kang_sync.rename(columns={'spotifyid': 'spotify_id_new', 'genres': 'spotify_genres_new'}),
    left_on='musicbrainz_artist_id', right_on='id', how='left'
).drop(columns=['id'])

# Fill in blanks / overwrite with fresher kang data
df_artists['spotify_id'] = df_artists['spotify_id_new'].combine_first(df_artists['spotify_id'])
df_artists['spotify_genres'] = df_artists['spotify_genres_new'].combine_first(df_artists['spotify_genres'])
df_artists = df_artists.drop(columns=['spotify_id_new', 'spotify_genres_new'])

print(f"spotify_id filled:     {df_artists['spotify_id'].notna().sum()}")
print(f"spotify_genres filled: {df_artists['spotify_genres'].notna().sum()}")

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

spotify_id filled:     3560
spotify_genres filled: 3560
Saved.

In [103]:
# Re-run spotify genre categorization on the updated spotify_genres column

df_artists['spotify_major_genre_categories'] = df_artists['spotify_genres'].apply(categorize_spotify_genres)

total = df_artists['spotify_genres'].notna().sum()
matched = df_artists['spotify_major_genre_categories'].notna().sum()
print(f"Artists with Spotify genres:      {total:,}")
print(f"Successfully categorized:         {matched:,} ({matched/total*100:.1f}%)")

print("\nDistribution:")
all_cats = []
for cats in df_artists['spotify_major_genre_categories'].dropna():
    all_cats.extend([c.strip() for c in cats.split(',')])
print(pd.Series(all_cats).value_counts().to_string())

# Check remaining unmatched genres
import ast
unmatched = []
for val in df_artists['spotify_genres'].dropna():
    try:
        genres = ast.literal_eval(val)
    except:
        genres = [g.strip() for g in val.split(',')]
    for g in genres:
        if g.strip().lower() not in musicbrainz_to_major_genre:
            unmatched.append(g.strip().lower())

print(f"\nTop unmatched Spotify genres ({len(set(unmatched))} unique):")
print(pd.Series(unmatched).value_counts().head(30).to_string())

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("\nSaved.")

Artists with Spotify genres:      3,560
Successfully categorized:         3,018 (84.8%)

Distribution:
Pop                           1180
Rock                          1074
Hip Hop/Rap                    587
R&B/Soul/Funk                  423
Electronic/Dance               376
Folk                           233
Country/Americana              206
Jazz                           204
Metal                          196
Easy Listening/Vocal           196
Punk/Hardcore                  142
Experimental/Avant-Garde       128
Latin                          113
Blues                           67
Reggae/Caribbean                37
Gospel/Christian/Religious      22
World Music                     11
Classical                       10

Top unmatched Spotify genres (1001 unique):
indietronica                  38
post-disco                    37
ccm                           36
canadian pop                  32
latin hip hop                 31
dance rock                    31
indie soul                    30
christian music               30
melancholia                   30
vapor trap                    29
alt z                         29
worship                       29
modern blues                  27
viral pop                     26
west coast rap                25
modern country rock           24
houston rap                   23
chicago rap                   23
reggae fusion                 23
christian alternative rock    23
british invasion              23
uk pop                        23
acoustic pop                  22
boy band                      22
jazz saxophone                21
cali rap                      21
melodic metalcore             21
country dawn                  21
hollywood                     21
miami hip hop                 20

Saved.

In [106]:
# Create combined_major_genre_categories as the union of MB and Spotify categories,
# sorted alphabetically with no duplicates.

def combine_genres(mb, sp):
    mb_set = set(c.strip() for c in mb.split(',')) if isinstance(mb, str) else set()
    sp_set = set(c.strip() for c in sp.split(',')) if isinstance(sp, str) else set()
    combined = mb_set | sp_set
    return ', '.join(sorted(combined)) if combined else None

df_artists['combined_major_genre_categories'] = df_artists.apply(
    lambda r: combine_genres(
        r['musicbrainz_major_genre_categories'],
        r['spotify_major_genre_categories']
    ), axis=1
)

filled = df_artists['combined_major_genre_categories'].notna().sum()
print(f"Artists with combined genres: {filled:,} ({filled/len(df_artists)*100:.1f}%)")

print("\nDistribution:")
all_cats = []
for cats in df_artists['combined_major_genre_categories'].dropna():
    all_cats.extend([c.strip() for c in cats.split(',')])
print(pd.Series(all_cats).value_counts().to_string())

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("\nSaved.")

Artists with combined genres: 8,623 (60.6%)

Distribution:
Rock                          3882
Pop                           3146
R&B/Soul/Funk                 1629
Hip Hop/Rap                   1574
Electronic/Dance              1513
Metal                         1103
Punk/Hardcore                  985
Folk                           949
Jazz                           935
Country/Americana              867
Easy Listening/Vocal           452
Experimental/Avant-Garde       439
Gospel/Christian/Religious     348
Latin                          331
Blues                          328
Classical                      218
Reggae/Caribbean               201
World Music                    106

Saved.

In [ ]:
# Look up the correct UUID (musicbrainz_mbid) for each integer musicbrainz_artist_id
# using the local MusicBrainz artist dump, then sync df_artists.

import pandas as pd

artist_path = '/Users/jamesemcnally/musicbrainz_data/mbdump/artist'

# Load only id and gid columns from the MB dump (fast — just first 2 fields per line)
print("Loading MB artist id→uuid mapping...")
mb_id_to_uuid = {}
with open(artist_path, 'r', encoding='utf-8') as f:
    for line in f:
        parts = line.split('\t')
        if len(parts) >= 2:
            try:
                mb_id_to_uuid[int(parts[0])] = parts[1]
            except ValueError:
                continue

print(f"Loaded {len(mb_id_to_uuid):,} MB artists")

# Map integer IDs in df_artists to correct UUIDs
df_artists['musicbrainz_artist_id_int'] = pd.to_numeric(
    df_artists['musicbrainz_artist_id'], errors='coerce'
).astype('Int64')

df_artists['musicbrainz_mbid'] = df_artists['musicbrainz_artist_id_int'].map(
    lambda x: mb_id_to_uuid.get(x) if pd.notna(x) else None
)

df_artists = df_artists.drop(columns=['musicbrainz_artist_id_int'])

filled = df_artists['musicbrainz_mbid'].notna().sum()
print(f"musicbrainz_mbid filled: {filled:,} / {len(df_artists):,}")

df_artists.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv', index=False)
print("Saved.")

In [ ]:
# Sync corrected MusicBrainz artist IDs from df_artists into df_songs and df_albums,
# and rename performer_normalized → name in both.
#
# df_artists uses 'name' as the key (renamed from performer_normalized earlier).
# df_songs and df_albums still use 'performer_normalized' — we match on that.

import pandas as pd

df_artists = pd.read_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv')
df_songs   = pd.read_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_songs.csv')
df_albums  = pd.read_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_albums.csv')

# Build name → corrected ID map from df_artists
correct_id_map = df_artists.set_index('name')['musicbrainz_artist_id'].dropna().to_dict()

# Apply to df_songs
df_songs['musicbrainz_artist_id'] = df_songs['performer_normalized'].map(correct_id_map)
df_songs = df_songs.rename(columns={'performer_normalized': 'name'})

# Apply to df_albums
df_albums['musicbrainz_artist_id'] = df_albums['performer_normalized'].map(correct_id_map)
df_albums = df_albums.rename(columns={'performer_normalized': 'name'})

# Summary
print(f"df_songs  — IDs filled: {df_songs['musicbrainz_artist_id'].notna().sum()} / {len(df_songs)}")
print(f"df_albums — IDs filled: {df_albums['musicbrainz_artist_id'].notna().sum()} / {len(df_albums)}")

# Make 'name' the second column in both dataframes
def move_to_second(df):
    cols = df.columns.tolist()
    cols.insert(1, cols.pop(cols.index('name')))
    return df[cols]

df_songs  = move_to_second(df_songs)
df_albums = move_to_second(df_albums)

# Save
df_songs.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_songs.csv', index=False)
df_albums.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_albums.csv', index=False)
print("Saved.")