In [1]:
# Load df_artists and df_songs from project CSVs
import pandas as pd

base = '/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/'

df_artists = pd.read_csv(base + 'df_artists.csv')
df_songs   = pd.read_csv(base + 'df_songs.csv')

print(f'df_artists: {df_artists.shape}')
print(f'df_songs:   {df_songs.shape}')

df_artists: (13609, 54)
df_songs:   (38383, 43)

In [4]:
# Diagnostic: flag each issue type in df_artists to understand scope
import re

flags = {
    'starts_with_ampersand':  df_artists['name'].str.match(r'^&'),
    'collab_x':               df_artists['name'].str.contains(r'\bx\b', regex=True),
    'collab_slash':           df_artists['name'].str.contains(r'/', regex=False),
    'collab_comma':           df_artists['name'].str.contains(r', ', regex=False),
    'collab_or':              df_artists['name'].str.contains(r'\bor\b', regex=True),
    'collab_presents':        df_artists['name'].str.contains(r'\bpresents\b', regex=True),
    'collab_feat':            df_artists['name'].str.contains(r'\bfeat\b|\bft\b|\bfeaturing\b', regex=True),
    'parenthetical':          df_artists['name'].str.contains(r'\(', regex=True),
    'curly_quotes':           df_artists['name'].str.contains(r'[""'']', regex=True),
    'dollar_sign':            df_artists['name'].str.contains(r'\$', regex=False),
    'orchestra':              df_artists['name'].str.contains(r'\borchestra\b|\bband\b|\bhis \b|\bher \b', regex=True),
}

for label, mask in flags.items():
    n = mask.sum()
    print(f'{label:<30} {n:>5} rows')
    if n <= 5:
        print('  ', df_artists.loc[mask, 'name'].tolist())

starts_with_ampersand              6 rows
collab_x                          80 rows
collab_slash                     185 rows
collab_comma                     118 rows
collab_or                         26 rows
collab_presents                   37 rows
collab_feat                       66 rows
parenthetical                    131 rows
curly_quotes                      39 rows
dollar_sign                        0 rows
   []
orchestra                        366 rows

In [6]:
# Strip all quote characters for duplicate comparison
def normalize_for_dedup(s):
    s = re.sub(r'[""«»""\'\'‛`]', '', s)  # remove all quote variants
    s = re.sub(r'\s+', ' ', s).strip()
    return s

df_artists['name_dedup'] = df_artists['name'].apply(normalize_for_dedup)

dupes = df_artists[df_artists.duplicated('name_dedup', keep=False)].sort_values('name_dedup')
print(f'Duplicate pairs after stripping all quotes: {len(dupes)}')
print(dupes[['name', 'name_dedup']].to_string())

Duplicate pairs after stripping all quotes: 32
                             name                 name_dedup
1215       billy "crash" craddock       billy crash craddock
1217       billy 'crash' craddock       billy crash craddock
1462        bobby "boris" pickett        bobby boris pickett
1463        bobby 'boris' pickett        bobby boris pickett
2789     damian "jr. gong" marley     damian jr. gong marley
2790     damian 'jr. gong' marley     damian jr. gong marley
5782             jimmy "bo" horne             jimmy bo horne
5783             jimmy 'bo' horne             jimmy bo horne
6473                       keb mo                     keb mo
6474                     keb' mo'                     keb mo
6609         kierra 'kiki' sheard         kierra kiki sheard
6608         kierra "kiki" sheard         kierra kiki sheard
7132                  lil' boosie                 lil boosie
7084                   lil boosie                 lil boosie
7147                    lil' troy                   lil troy
7119                     lil troy                   lil troy
7122                    lil wayne                  lil wayne
7148                   lil' wayne                  lil wayne
7890         me'shell ndegeocello        meshell ndegeocello
7959          meshell ndegeocello        meshell ndegeocello
8400              nat "king" cole              nat king cole
8402                nat king cole              nat king cole
9735     richard "dimples" fields     richard dimples fields
9737     richard 'dimples' fields     richard dimples fields
10719         sniff 'n' the tears          sniff n the tears
10720           sniff n the tears          sniff n the tears
11916  the edwin hawkins' singers  the edwin hawkins singers
11915   the edwin hawkins singers  the edwin hawkins singers
12801         the sopwith 'camel'          the sopwith camel
12800         the sopwith "camel"          the sopwith camel
17            'weird al' yankovic          weird al yankovic
4             "weird al" yankovic          weird al yankovic

In [12]:
# Revised pick_best — no reference to name_dedup inside the function
KEEP_OVERRIDES = {"me'shell ndegeocello", "sniff 'n' the tears"}

def pick_best(group):
    for preferred in KEEP_OVERRIDES:
        match = group[group['name'] == preferred]
        if len(match):
            return match.index[0]
    return group['total_charting_songs'].idxmax()

dup_rows  = df_artists[df_artists.duplicated('name_dedup', keep=False)]
keep_idxs = dup_rows.groupby('name_dedup', group_keys=False).apply(pick_best).values
drop_idxs = dup_rows.index.difference(keep_idxs)

print(f'Dropping {len(drop_idxs)} rows. Keeping:')
print(df_artists.loc[keep_idxs, ['name', 'total_charting_songs']].to_string())

Dropping 16 rows. Keeping:
                            name  total_charting_songs
1215      billy "crash" craddock                     3
1462       bobby "boris" pickett                     2
2789    damian "jr. gong" marley                     1
5782            jimmy "bo" horne                     1
6473                      keb mo                     0
6608        kierra "kiki" sheard                     1
7084                  lil boosie                     2
7147                   lil' troy                     1
7122                   lil wayne                   180
7890        me'shell ndegeocello                     1
8402               nat king cole                    30
9735    richard "dimples" fields                     1
10719        sniff 'n' the tears                     1
11915  the edwin hawkins singers                     1
12800        the sopwith "camel"                     2
4            "weird al" yankovic                    11

/var/folders/1v/h2vyfq9j45n9_tmm_gg2s8tm0000gn/T/ipykernel_29612/2905915789.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  keep_idxs = dup_rows.groupby('name_dedup', group_keys=False).apply(pick_best).values

In [13]:
# Commit deduplication
df_artists = df_artists.drop(index=drop_idxs).drop(columns=['name_dedup', 'name_normalized'])
print(f'df_artists after dedup: {df_artists.shape}')

df_artists after dedup: (14208, 54)

In [15]:
# High-confidence drops with exception for known false positives
KEEP_EXCEPTIONS = {'little feat'}

drop_mask = (
    (
        df_artists['name'].str.match(r'^&')
      | df_artists['name'].str.contains(r'\bfeat\b|\bft\.?\b|\bfeaturing\b', regex=True)
      | df_artists['name'].str.contains(r' x ', regex=False)
    )
    & ~df_artists['name'].isin(KEEP_EXCEPTIONS)
)

print(f'Rows to drop: {drop_mask.sum()}')
print(df_artists.loc[drop_mask, 'name'].to_string())

Rows to drop: 132
7                                       $uicideboy$ x germ
8                                         & cardi b or nas
9                                            & jack harlow
10                                           & johnny cash
11                                              & mystikal
12                                               & sam dew
13                            & youngboy never broke again
40                           2 chainz x gucci mane x quavo
112                                50 cent feat. mobb deep
647                                        arcangel x sech
661                           ariana grande feat. doja cat
788                                   aventura x bad bunny
853                      babyface (featuring toni braxton)
1127                      big daddy kane feat. spinderella
1344                       blackstreet (featuring dr. dre)
1912                calle 24 x chino pacas x fuerza regida
2134                      changing faces (featuring jay-z)
2262                                         chloe x halle
2277                            chris brown feat. ludacris
2509                                        coldplay x bts
2658                     crofts (featuring carolyn willis)
2712                                 cxm: s.coups x mingyu
2764                               dababy x stunna 4 vegas
2900                         das efx (featuring mobb deep)
2919                                  dave east x styles p
3296                            dis `n' dat feat. 95 south
3331                                  dj khaled feat. akon
3362                                        dk x seungkwan
3370                          do or die (featuring twista)
3620                               e-40 (featuring leviti)
3621                               e-40 (featuring suga t)
3716                            egg cream feat. andy adams
3727                                  el alfa x peso pluma
3774                                ellie goulding x diplo
3841               enrique iglesias feat. wisin or tinashe
4047                                     feid x young miko
4377                                   g-eazy x bebe rexha
4378                                      g-eazy x carnage
4595              giorgio moroder (featuring paul engeman)
4629             glenn medeiros (featuring the stylistics)
5227                           immature (featuring smooth)
5545                              jawsh 685 x jason derulo
5702                   jesse johnson (featuring sly stone)
6255                             juice wrld x benny blanco
6256                               juice wrld x marshmello
6301                                 junior h x peso pluma
6405                                       karol g x maldy
6406                                karol g x romeo santos
6407                                     karol g x shakira
6499                     keith sweat (featuring kut klose)
6500                  keith sweat (featuring ronald isley)
6518                             kelsea ballerini x halsey
6587                                   khalid x disclosure
6588                                         khalid x safe
6759                                       ksi x lil wayne
6783                                   kygo x selena gomez
6803                              l.b.c. crew feat. tray d
6804             l.f.o. (lyte funky ones) (featuring kayo)
7099                                     lil mosey x gunna
7139                                lil' kim feat. da brat
7177              linda ronstadt (featuring aaron neville)
7284             logic & ty dolla $ign feat. x ambassadors
7286                   lola brooke x latto x yung miami or
7450                         luis r conriquez x neton vega
7522                    machine gun kelly x camila cabello
7720                               marshmello x jelly roll
7733                           martin garrix x troye sivan
7794          master p feat. fiend, silkk the shocker, mia
7864                        maze featuring frankie beverly
8106                           mike will made-it x rihanna
8218                               moneybagg yo x glorilla
8233                         montell jordan feat. master p
8258     mormon tabernacle choir/orchestra at temple sq...
8427                                 natti natasha x ozuna
8496                            new boyz feat. chris brown
8556                                  nicky jam x j balvin
8602     nio garcia x anuel aa x myke towers x brray x ...
8730                       ol skool [featuring keith sweat
8779                     or-n-more (featuring father m.c.)
8846                                       ozuna x cardi b
8847     ozuna x daddy yankee x j balvin x farruko x an...
8848                         ozuna x karol g x myke towers
8849                                 ozuna x manuel turizo
8904                               parmalee x blanco brown
8947               patrick swayze (featuring wendy fraser)
8978                        paul davis feat. susan collins
9092                  peso pluma x jasiel nunez x junior h
9151                    pharrell williams x camila cabello
9225                         pitbull x el chombo x karol g
9310                   pras michel feat. ol' dirty bastard
9392                           puff daddy (featuring mase)
9443             quincy jones (feat. the brothers johnson)
9444                   quincy jones feat. babyface & tamia
9451                   r. kelly or bow wow (featuring t.i.
9645                     regard x troye sivan x tate mcrae
9925                    rod stewart x miguel x mark ronson
10131                             ryan castro x pe$o pluma
10143                                 rza feat. method man
10296                        scandal featuring patty smyth
10300                              scarface feat. ice cube
10345                         sean paul feat. keyshia cole
10405                 shabba ranks (featuring johnny gill)
10406                 shabba ranks (featuring maxi priest)
10416                            shaggy (featuring marsha)
10418                 shaggy feat. ricardo "rikrok" ducent
10429                         shakira feat. alejandro sanz
10558                                 silk city x dua lipa
10647    slash featuring myles kennedy and the conspira...
10734                                            sob x rbe
10797               soul ii soul (featuring caron wheeler)
10867                spiral starecase featuring: pat upton
10907                 stacy earl (featuring the wild pair)
11110                               subway (featuring 702)
11222                           swv (featuring puff daddy)
11681            the cantina band (featuring lou christie)
11956               the family (feat. the notorious b.i.g.
12326                               the lox [featuring dmx
12404      the miracles (featuring bill "smokey" robinson)
12471    the new life community choir featuring john p....
12530              the ovations (featuring louis williams)
12591             the poppy family (featuring susan jacks)
13293                                  tomorrow x together
13423                         trevor daniel x selena gomez
13503                         twenty one pilots x mutemath
13597                              upchurch x adam calhoun
13608                                     usher x zaytoven
13664                      veronica (featuring craig mack)
13880                    whitney houston feat. faith evans
14025                              xxxtentacion x lil pump
14036               yahritza y su esencia x grupo frontera
14084                               yng lvcas x peso pluma
14089                                  yo gotti x dj drama

In [16]:
df_artists = df_artists[~drop_mask].copy()
print(f'df_artists after dropping collabs/features: {df_artists.shape}')

df_artists after dropping collabs/features: (14076, 54)

In [17]:
# Preview 'presents' entries
presents_mask = df_artists['name'].str.contains(r'\bpresents\b', regex=True)
print(f'{presents_mask.sum()} rows:')
print(df_artists.loc[presents_mask, 'name'].to_string())

37 rows:
169         a.b. quintanilla iii presents kumbia all starz
170             a.b. quintanilla iii presents kumbia kings
599                            ant banks presents t.w.d.y.
1283     bishop eddie l. long presents new birth total ...
1285     bishop noel jones presents the city of refuge ...
1287            bishop paul s. morton presents the fgbcfmc
1722              broken social scene presents: kevin drew
1876                c+c music factory presents zelma davis
1923                            cam'ron presents dukedagod
1924                        cam'ron presents the diplomats
2459                           clipse presents: re-up gang
2799                         damizza presents shade sheist
3282                          diplo presents thomas wesley
3283                      diplomats presents freekey zekey
3284                         diplomats presents: hell rell
3321     dj drama presents: wyclef jean aka toussaint s...
3332                           dj khaled presents ace hood
3353                             dj skee presents the game
3436         donald lawrence presents the tri-city singers
4359                     funkmaster flex presents khadejia
4636      gloria gaither presents their homecoming friends
5287                           irv gotti presents the inc.
6037                    john w. anderson presents kasandra
6685                            kirk franklin presents 1nc
7527                              mack 10 presents da hood
7777                            mase presents harlem world
10042                  roy hargrove presents the rh factor
10301                     scarface presents... the product
10524                     shoreline mafia presents ohgeesy
10676                 slim thug presents boss hogg outlawz
10707      smokie norful presents: victory cathedral choir
10724                    snoop dogg presents tha eastsidaz
11260                                t.i. presents the p$c
11358                      tech n9ne presents krizz kaliko
11359                      tech n9ne presents stevie stone
11867                     the diplomats presents jr writer
14122                        young jeezy presents u.s.d.a.

In [18]:
# Drop 'presents' entries
df_artists = df_artists[~presents_mask].copy()
print(f'df_artists after dropping presents: {df_artists.shape}')

df_artists after dropping presents: (14039, 54)

In [19]:
# Preview comma-separated entries (likely multi-artist listings)
comma_mask = df_artists['name'].str.contains(r', ', regex=False)
print(f'{comma_mask.sum()} rows:')
print(df_artists.loc[comma_mask, 'name'].to_string())

117 rows:
51                          21 savage & tyler, the creator
52                     21 savage, travis scott & yak gotti
160                        a$ap rocky & tyler, the creator
278                                 akon, lil wayne & niia
536      andy nyman, courtney-mae briggs, jeff goldblum...
662      ariana grande, ethan slater, marissa bode & cy...
704                         artists of then, now & forever
727                                 ashton, gardner & dyke
838                 baaba maal, the very best & beatenberg
963      bas, jid, guapdad 4000, reese laflare, jace, m...
976                   battle, von stade, marsalis (previn)
1053               benedictines of mary, queen of apostles
1174                         bilal, anna wise & snoop dogg
1175                         bilal, anna wise & thundercat
1277                        birdman, jay sean, & lil wayne
1305                               black country, new road
1308                   black eyed peas, ozuna + j.rey soul
1382                                  blood, sweat & tears
1502                                    bobby pedrick, jr.
1982                                     carl dobkins, jr.
2026                  carreras, domingo, pavarotti (mehta)
2093              cedric gervais, wiz khalifa & mally mall
2278                           chris brown, skeme & lyquin
2373                             chunk! no, captain chunk!
2604                             cotton, lloyd & christian
2662                                 crosby, stills & nash
2663                          crosby, stills, nash & young
2770           daddy yankee, nina sky, gem star & big mato
2824                           dancer, prancer and nervous
2916                  dave dee, dozy, beaky, mick and tich
2942     david & nicole binion, joshua dufrene & colin ...
3178            descemer bueno, zion & lennox or sean paul
3251               diddy, nelly, jagged edge & avery storm
3270                                    dino, desi & billy
3526                         drake, kanye west + the-dream
3554                                   drop dead, gorgeous
3575                              duece poppito, trina, co
3639                                    earth, wind & fire
3655                               ecstasy, passion & pain
3804                                emerson, lake & palmer
3805                                emerson, lake & powell
3870     eric nally, melle mel, kool moe dee & grandmas...
3994                               faith, hope and charity
4781                                grover washington, jr.
4835                       hagar, schon, aaronson, shrieve
4853                        hamilton, joe frank & dennison
4854                        hamilton, joe frank & reynolds
4871                                    hank williams, jr.
4892                                    harry connick, jr.
4893       harry connick, jr./2006 broadway cast recording
5033                        hitta j3, youngthreat & peysoh
5035                               hodges, james and smith
5126             hugo montenegro, his orchestra and chorus
5277                                       invent, animate
5297                                  isley, jasper, isley
5340                                j. cole, lute & dababy
5356             ja rule, ashanti, charli baltimore & vita
5749                              jim belushi, dan aykroyd
6041                                  john wesley ryles, i
6251                   juelz santana, freekey zekey & toya
6399              kari jobe, shane & shane & jeremy riddle
6401                                      karl hammel, jr.
6408                                  karol g, feid & dfzm
6784                              kyjuan, ali & murphy lee
6852                             landau eugene murphy, jr.
7125                        lil wayne & tyler, the creator
7127     lil wayne, birdman, future, mack maine, nicki ...
7200                                           lipps, inc.
7246                little simz, burna boy, elyanna & tini
7268     ll cool j, howard hewett, jody watley & jeffre...
7316                    loon, mario winans & tammy ruggeri
7439            ludacris, too short, big kap & chyna whyte
7795                 master p, destiny's child, o'dell, mo
7796     master p, nate dogg, butch cassidy & tha easts...
7883                              mcguinn, clark & hillman
8204                                mohombi, faydee, costi
8398                         nas, jay-z & james fauntleroy
8444                               ne-yo, afrojack & nayer
8487                        nervo, the knocks & alisa ueno
8721                                           oh, sleeper
8811                                      oscar toney, jr.
8836     ovy on the drums, j balvin, maluma, ryan castr...
9019                                 paul wall, ali & gipp
9136                                    peter, paul & mary
9145                               phantom, rocker & slick
9152                            pharrell, pusha t & casino
9174                                phillips, craig & dean
9362                         prodigy, illa ghee & nina sky
9370                     project pat, young d & superpower
9575                                  ray, goodman & brown
9601     reba mcentire, hillary scott, chris tomlin & k...
9693                      rev. dr. martin luther king, jr.
9694                          rev. martin luther king, jr.
9852                                    robert downey, jr.
9929               roddy ricch, gunna & london on da track
10220                                     sammy davis, jr.
10944     stars on 54: ultra nate, amber, jocelyn enriquez
10995                      steve aoki, chris lake & tujamo
11261          t.i., b.o.b, kendrick lamar & kris stephens
11337                                 tateeze, boo & gotti
11374        teddy riley, nutta butta, markell & jesse wes
11717                                 the checkmates, ltd.
12075                        the good, the bad & the queen
12235    the jordanaires, jubilee four & carol lombard ...
12741                  the scotts, travis scott & kid cudi
12813                     the souther, hillman, furay band
13087    theophilus london, allan kingdom & paul mccartney
13121            three hanks: hank williams, sr., jr., iii
13389                                        traffic, etc.
13390                            tragedy, capone, infinite
13542                                   tyler, the creator
13760             wallie the sensei, siete7x & roddy ricch
13800    waylon jennings, willie nelson, jessi colter, ...
13840                                  west, bruce & laing
13858                                    whenever, if ever
13972                                           woe, is me
14161             yungsta, fat pat, lil' will, hawk, big t

In [20]:
# Keep comma entries that are legitimate single-artist names; drop multi-artist collabs
COMMA_KEEP = {
    # Jr./Sr./I suffixes
    'bobby pedrick, jr.', 'carl dobkins, jr.', 'grover washington, jr.',
    'hank williams, jr.', 'harry connick, jr.', 'karl hammel, jr.',
    'oscar toney, jr.', 'sammy davis, jr.', 'rev. dr. martin luther king, jr.',
    'rev. martin luther king, jr.', 'landau eugene murphy, jr.',
    'robert downey, jr.', 'john wesley ryles, i',
    # Band names with commas
    'tyler, the creator', 'blood, sweat & tears', 'earth, wind & fire',
    'emerson, lake & palmer', 'emerson, lake & powell',
    'crosby, stills & nash', 'crosby, stills, nash & young',
    'peter, paul & mary', 'ray, goodman & brown',
    'hamilton, joe frank & dennison', 'hamilton, joe frank & reynolds',
    'dino, desi & billy', 'lipps, inc.', 'isley, jasper, isley',
    'ecstasy, passion & pain', 'faith, hope and charity',
    'dancer, prancer and nervous', 'west, bruce & laing',
    'black country, new road', 'mcguinn, clark & hillman',
    'phantom, rocker & slick', 'hagar, schon, aaronson, shrieve',
    'ashton, gardner & dyke', 'phillips, craig & dean',
    'invent, animate', 'drop dead, gorgeous', 'oh, sleeper',
    'woe, is me', 'whenever, if ever', 'chunk! no, captain chunk!',
    'benedictines of mary, queen of apostles',
    'hodges, james and smith', 'cotton, lloyd and christian',
    'three hanks: hank williams, sr., jr., iii',
}

comma_mask = df_artists['name'].str.contains(r', ', regex=False)
comma_drop = comma_mask & ~df_artists['name'].isin(COMMA_KEEP)

print(f'Dropping {comma_drop.sum()} rows, keeping {(comma_mask & df_artists["name"].isin(COMMA_KEEP)).sum()}')
print('\nDropping:')
print(df_artists.loc[comma_drop, 'name'].to_string())
print('\nKeeping:')
print(df_artists.loc[comma_mask & df_artists['name'].isin(COMMA_KEEP), 'name'].to_string())

Dropping 71 rows, keeping 46

Dropping:
51                          21 savage & tyler, the creator
52                     21 savage, travis scott & yak gotti
160                        a$ap rocky & tyler, the creator
278                                 akon, lil wayne & niia
536      andy nyman, courtney-mae briggs, jeff goldblum...
662      ariana grande, ethan slater, marissa bode & cy...
704                         artists of then, now & forever
838                 baaba maal, the very best & beatenberg
963      bas, jid, guapdad 4000, reese laflare, jace, m...
976                   battle, von stade, marsalis (previn)
1174                         bilal, anna wise & snoop dogg
1175                         bilal, anna wise & thundercat
1277                        birdman, jay sean, & lil wayne
1308                   black eyed peas, ozuna + j.rey soul
2026                  carreras, domingo, pavarotti (mehta)
2093              cedric gervais, wiz khalifa & mally mall
2278                           chris brown, skeme & lyquin
2604                             cotton, lloyd & christian
2770           daddy yankee, nina sky, gem star & big mato
2916                  dave dee, dozy, beaky, mick and tich
2942     david & nicole binion, joshua dufrene & colin ...
3178            descemer bueno, zion & lennox or sean paul
3251               diddy, nelly, jagged edge & avery storm
3526                         drake, kanye west + the-dream
3575                              duece poppito, trina, co
3870     eric nally, melle mel, kool moe dee & grandmas...
4893       harry connick, jr./2006 broadway cast recording
5033                        hitta j3, youngthreat & peysoh
5126             hugo montenegro, his orchestra and chorus
5340                                j. cole, lute & dababy
5356             ja rule, ashanti, charli baltimore & vita
5749                              jim belushi, dan aykroyd
6251                   juelz santana, freekey zekey & toya
6399              kari jobe, shane & shane & jeremy riddle
6408                                  karol g, feid & dfzm
6784                              kyjuan, ali & murphy lee
7125                        lil wayne & tyler, the creator
7127     lil wayne, birdman, future, mack maine, nicki ...
7246                little simz, burna boy, elyanna & tini
7268     ll cool j, howard hewett, jody watley & jeffre...
7316                    loon, mario winans & tammy ruggeri
7439            ludacris, too short, big kap & chyna whyte
7795                 master p, destiny's child, o'dell, mo
7796     master p, nate dogg, butch cassidy & tha easts...
8204                                mohombi, faydee, costi
8398                         nas, jay-z & james fauntleroy
8444                               ne-yo, afrojack & nayer
8487                        nervo, the knocks & alisa ueno
8836     ovy on the drums, j balvin, maluma, ryan castr...
9019                                 paul wall, ali & gipp
9152                            pharrell, pusha t & casino
9362                         prodigy, illa ghee & nina sky
9370                     project pat, young d & superpower
9601     reba mcentire, hillary scott, chris tomlin & k...
9929               roddy ricch, gunna & london on da track
10944     stars on 54: ultra nate, amber, jocelyn enriquez
10995                      steve aoki, chris lake & tujamo
11261          t.i., b.o.b, kendrick lamar & kris stephens
11337                                 tateeze, boo & gotti
11374        teddy riley, nutta butta, markell & jesse wes
11717                                 the checkmates, ltd.
12075                        the good, the bad & the queen
12235    the jordanaires, jubilee four & carol lombard ...
12741                  the scotts, travis scott & kid cudi
12813                     the souther, hillman, furay band
13087    theophilus london, allan kingdom & paul mccartney
13389                                        traffic, etc.
13390                            tragedy, capone, infinite
13760             wallie the sensei, siete7x & roddy ricch
13800    waylon jennings, willie nelson, jessi colter, ...
14161             yungsta, fat pat, lil' will, hawk, big t

Keeping:
727                         ashton, gardner & dyke
1053       benedictines of mary, queen of apostles
1305                       black country, new road
1382                          blood, sweat & tears
1502                            bobby pedrick, jr.
1982                             carl dobkins, jr.
2373                     chunk! no, captain chunk!
2662                         crosby, stills & nash
2663                  crosby, stills, nash & young
2824                   dancer, prancer and nervous
3270                            dino, desi & billy
3554                           drop dead, gorgeous
3639                            earth, wind & fire
3655                       ecstasy, passion & pain
3804                        emerson, lake & palmer
3805                        emerson, lake & powell
3994                       faith, hope and charity
4781                        grover washington, jr.
4835               hagar, schon, aaronson, shrieve
4853                hamilton, joe frank & dennison
4854                hamilton, joe frank & reynolds
4871                            hank williams, jr.
4892                            harry connick, jr.
5035                       hodges, james and smith
5277                               invent, animate
5297                          isley, jasper, isley
6041                          john wesley ryles, i
6401                              karl hammel, jr.
6852                     landau eugene murphy, jr.
7200                                   lipps, inc.
7883                      mcguinn, clark & hillman
8721                                   oh, sleeper
8811                              oscar toney, jr.
9136                            peter, paul & mary
9145                       phantom, rocker & slick
9174                        phillips, craig & dean
9575                          ray, goodman & brown
9693              rev. dr. martin luther king, jr.
9694                  rev. martin luther king, jr.
9852                            robert downey, jr.
10220                             sammy davis, jr.
13121    three hanks: hank williams, sr., jr., iii
13542                           tyler, the creator
13840                          west, bruce & laing
13858                            whenever, if ever
13972                                   woe, is me

In [22]:
# Commit comma drops
df_artists = df_artists[~comma_drop].copy()
print(f'df_artists after dropping comma collabs: {df_artists.shape}')

df_artists after dropping comma collabs: (13968, 54)

In [23]:
# Preview 'or' entries
or_mask = df_artists['name'].str.contains(r'\bor\b', regex=True)
print(f'{or_mask.sum()} rows:')
print(df_artists.loc[or_mask, 'name'].to_string())

19 rows:
339                            alex band or chad kroeger
1230                    billy currington or mark mcgrath
3050                                       dead or alive
3369                                           do or die
3728                            el cata or dizzee rascal
4080                                     fight or flight
5161                          iamsu & skipper or 50 cent
5203                              iggy azalea or pitbull
6913                   lauren alaina or mackenzie porter
7123     lil wayne & french montana or too $hort or tyga
7126                                   lil wayne or t.i.
8553             nicki minaj or chimamanda ngozi adichie
9252                             plies or oj da juiceman
9277                              pooh shiesty or dababy
10499                      sheryl crow or allison moorer
11191                           swae lee or rae sremmurd
11300                                   tamia or ashanti
13142                            tiara thomas or rihanna
13908                               will.i.am or juicy j

In [24]:
# Drop 'or' collab entries, keep legitimate band names
OR_KEEP = {'dead or alive', 'do or die', 'fight or flight'}

or_mask = df_artists['name'].str.contains(r'\bor\b', regex=True)
or_drop = or_mask & ~df_artists['name'].isin(OR_KEEP)

print(f'Dropping {or_drop.sum()}, keeping {or_mask.sum() - or_drop.sum()}')
df_artists = df_artists[~or_drop].copy()
print(f'df_artists: {df_artists.shape}')

Dropping 16, keeping 3
df_artists: (13952, 54)

In [25]:
# Preview slash entries
slash_mask = df_artists['name'].str.contains('/', regex=False)
print(f'{slash_mask.sum()} rows:')
print(df_artists.loc[slash_mask, 'name'].to_string())

183 rows:
48                                                   20/20
59                       2cellos/london symphony orchestra
202                                                  ac/dc
264                          agnetha faltskog/peter cetera
280                                          akwid / jae-p
291               al dimeola/john mclaughlin/paco de lucia
307               alan jackson/george strait/jimmy buffett
337                                    alesso / katy perry
481                              ana barbara/jennifer pena
610               anthony kearns/ronan tynan/finbar wright
657                        aretha franklin/whitney houston
936                          barbra streisand/donna summer
1043                                 ben folds/nick hornby
1071             berlin philharmonic/mstislav rostropovich
1226                         billy cobham/george duke band
1434                                    bob dylan/the band
1439                               bob james/david sanborn
1440                                  bob james/earl klugh
1511                           bobby rydell/chubby checker
1541                                boney james/rick braun
1582                     boris karloff / thurl ravenscroft
1646                branford marsalis quartet/t. blanchard
1724                   bronco / los bukis / los temerarios
1725                                      bronco/los bukis
1778                         bryan adams/rod stewart/sting
1779                               bryan adams/tina turner
1877                         c+c music factory/f. williams
1906                                       calexico / iron
2000             carlos santana/mahavishnu john mclaughlin
2038                                       case/lang/veirs
2102                 celine dion/cher/dixie chicks/shakira
2218                         cheryl barnes/hair soundtrack
2388                                 cipha sounds/mr. choc
2511                         cole swindell / lainey wilson
2617                          courtney barnett / kurt vile
2621                                        coverdale/page
2725                                    czarface / mf doom
2810                            dan fogelberg/tim weisberg
2928     dave koz/gerald albright/mindi abair/richard e...
2955                         david bowie/pat metheny group
2964                              david crosby/graham nash
3097                               dee gees / foo fighters
3131                            deliverance/eric weissberg
3306                     disturbed/chevelle/taproot/unloco
3335                            dj lil' cee/trevor simpson
3340                           dj muggs vs. gza/the genius
3348                             dj premier/bumpy knuckles
3355                              dj skribble / vic latino
3394                                 domingo/ross/carreras
3462                               donovan/jeff beck group
3632                  earl scruggs/doc watson/ricky skaggs
3650                                               ebn/ozn
3786                             elton john / leon russell
3838                                            eno / hyde
4193                                        foreigner/styx
4328                                  friends/eric clapton
4342                     fu-schnickens w/ shaquille o'neal
4491                                            genius/gza
4499                              george benson/earl klugh
4521                             george michael/elton john
4549                                    gershwin/wodehouse
4622                             glen campbell/anne murray
4637                             gloria gaither/t.d. jakes
4644                               gloria walker/chevelles
4827                                            gza/genius
4829                                    h-town/al b. sure!
5124                                         hughes/thrall
5133                                               huntr/x
5134                                         huntr/x: ejae
5169                                ian hunter/mick ronson
5229                    immortal technique/dj green latern
5264                                           inoj/lathun
5556       jay farrar/will johnson/anders parker/yim yames
5568                                     jay-z/linkin park
5616                            jeff wayne/various artists
5647                        jennifer warnes/chris thompson
5765                              jim morrison / the doors
5780                            jimmie walker/esther rolle
5887           joe hisaishi / royal philharmonic orchestra
5902                   joe satriani/eric johnson/steve vai
5940                      john & yoko/the plastic ono band
5967                   john fogerty/the blue ridge rangers
5988                                john lennon / yoko ono
5990                          john lennon/plastic ono band
5991     john lennon/plastic ono band yoko ono/plastic ...
6000             john mcdermott/anthony kearns/ronan tynan
6043                       john williams/"jaws" soundtrack
6044               john williams/the boston pops orchestra
6045                 john williams/yo-yo ma/itzhak perlman
6065                             johnny cash/willie nelson
6087                        johnny mathis/deniece williams
6176            jose carreras/natalie cole/placido domingo
6177     jose carreras/placido domingo/luciano pavarott...
6199       joshua bell/academy of st. martin in the fields
6200                               joshua bell/jeremy denk
6233                           juan gabriel / rocio durcal
6263      julia fischer/academy of st martin in the fields
6277                            julie driscoll/brian auger
6356                                                  k/da
6359                             kacey cisyk/original cast
6491                         keith jarrett / charlie haden
6492            keith jarrett/gary peacock/jack dejohnette
7061                      lft church choir/hezekiah walker
7111                                lil scrappy/trillville
7185                  lindsey buckingham / christine mcvie
7357                              los temerarios/los bukis
7374                                    lou reed/john cale
7401                                             love/hate
7505                                             m/a/r/r/s
7617                      mannheim steamroller/c.w. mccall
7618     mannheim steamroller/czech philharmonic orchestra
7619     mannheim streamroller/czech philharmonic orche...
7756                           marvin hamlisch/"the sting"
7950                            merle haggard/george jones
7967                                        meth/ghost/rae
8027                michael zager's moon band/peabo bryson
8033           michelle amato/sarah moore/michelle lindahl
8206                                 mojo nixon/skid roper
8256     mormon tabernacle choir/orchestra at temple sq...
8257     mormon tabernacle choir/orchestra at temple sq...
8337      music from bill cosby show/grover washington,jr.
8465                              neil young / crazy horse
8466                                neil young/crazy horse
8467                   neil young/international harvesters
8503     new found glory/international superheroes of h...
8567                                       nielsen/pearson
8749           olivia newton-john/electric light orchestra
8784           orchestra at temple square (jessop/wilberg)
8819              otis redding/the jimi hendrix experience
8852                            ozzy osbourne/randy rhoads
8929     pat metheny/chris potter/ben williams/antonio ...
8970                                 paul anka/odia coates
8991                       paul kantner/jefferson starship
8997                             paul mccartney/carl davis
9011                                paul simon/phoebe snow
9041                            peabo bryson/roberta flack
9100                             pete rock / smif-n-wessun
9120                               peter gabriel/kate bush
9233             placido domingo/ying huang/michael bolton
9350                                   prince/bria valente
9507                                           rancid/nofx
9634                                     redman/method man
9706                                rex smith/rachel sweet
9873                          robert plant / alison krauss
9983                           ronald isley/burt bacharach
9986                                   roni size/reprazent
10085                                     rufus/chaka khan
10123                            ry cooder / manuel galban
10573                              simon stokes/nighthawks
10575    simone dinnerstein/kammerorchester/staatskapel...
10817                       soundtrack/'weird' al yankovic
10917                            stan getz/astrud gilberto
10918                               stan getz/charlie byrd
10924                           stanley clarke/george duke
10938                                  starlito / don trip
11129                             sugarloaf/jerry corbetta
11360                                tech n9ne/dj whoo kid
11494                             the alchemist / curren$y
11577                           the benoit/freeman project
11748                  the clayton/hamilton jazz orchestra
11992          the flaming lips/stardeath and white dwarfs
12186                         the isley brothers / santana
12312          the london symphony orchestra/john williams
12620                    the raelets/ray charles orchestra
12736                            the sanford/townsend band
12892                              the tarney/spencer band
12923                 the tonight show band/doc severinsen
13313    tony bennett/charlotte church/placido domingo/...
13314                            tony bennett/dave brubeck
13641                      vanessa williams/brian mcknight
13924                                     williams/perlman
13935                        willie nelson / merle haggard
13936            willie nelson / merle haggard / ray price
14001                                  wu-tang/mathematics
14082                 ymusic/nashville symphony (guerrero)
14093                 yo-yo ma / chris thile / edgar meyer
14094                             yo-yo ma / kathryn stott
14095                              yo-yo ma/bobby mcferrin
14096                   yo-yo ma/edgar meyer/mark o'connor
14097       yo-yo ma/stuart duncan/edgar meyer/chris thile
14098    yo-yo ma/the silk road ensemble/chicago sympho...
14185                                        zappa/mothers
14190                                  zayn / taylor swift

In [26]:
SLASH_KEEP = {
    # Band names with slash
    'ac/dc', '20/20', 'ebn/ozn', 'k/da', 'love/hate', 'm/a/r/r/s',
    'gza/genius', 'genius/gza', 'roni size/reprazent', 'zappa/mothers',
    # Artist + regular backing band
    'neil young/crazy horse', 'neil young / crazy horse',
    'neil young/international harvesters',
    'john lennon/plastic ono band', 'john & yoko/the plastic ono band',
    'john lennon / yoko ono',
    'jim morrison / the doors', 'john fogerty/the blue ridge rangers',
    'paul kantner/jefferson starship', 'rufus/chaka khan',
    'ozzy osbourne/randy rhoads', 'sugarloaf/jerry corbetta',
    'the tonight show band/doc severinsen', 'the raelets/ray charles orchestra',
    # Established long-running duos/groups
    'mojo nixon/skid roper', 'redman/method man', 'coverdale/page',
    'bob james/david sanborn', 'bob james/earl klugh',
    'stanley clarke/george duke', 'george benson/earl klugh',
    'david crosby/graham nash', 'dan fogelberg/tim weisberg',
    'courtney barnett / kurt vile', 'case/lang/veirs',
    'ian hunter/mick ronson', 'peabo bryson/roberta flack',
    'starlito / don trip', 'the benoit/freeman project',
    'the sanford/townsend band', 'the tarney/spencer band',
    'the clayton/hamilton jazz orchestra', 'hughes/thrall',
    'czarface / mf doom', 'al dimeola/john mclaughlin/paco de lucia',
    'keith jarrett/gary peacock/jack dejohnette',
    'julie driscoll/brian auger', 'bob dylan/the band',
    # Added
    'dee gees / foo fighters',
    'harry connick, jr./2006 broadway cast recording',
}

slash_mask = df_artists['name'].str.contains('/', regex=False)
slash_drop = slash_mask & ~df_artists['name'].isin(SLASH_KEEP)

print(f'Dropping {slash_drop.sum()}, keeping {(slash_mask & df_artists["name"].isin(SLASH_KEEP)).sum()}')
print('\nDropping:')
print(df_artists.loc[slash_drop, 'name'].to_string())
print('\nKeeping:')
print(df_artists.loc[slash_mask & df_artists['name'].isin(SLASH_KEEP), 'name'].to_string())

Dropping 134, keeping 49

Dropping:
59                       2cellos/london symphony orchestra
264                          agnetha faltskog/peter cetera
280                                          akwid / jae-p
307               alan jackson/george strait/jimmy buffett
337                                    alesso / katy perry
481                              ana barbara/jennifer pena
610               anthony kearns/ronan tynan/finbar wright
657                        aretha franklin/whitney houston
936                          barbra streisand/donna summer
1043                                 ben folds/nick hornby
1071             berlin philharmonic/mstislav rostropovich
1226                         billy cobham/george duke band
1511                           bobby rydell/chubby checker
1541                                boney james/rick braun
1582                     boris karloff / thurl ravenscroft
1646                branford marsalis quartet/t. blanchard
1724                   bronco / los bukis / los temerarios
1725                                      bronco/los bukis
1778                         bryan adams/rod stewart/sting
1779                               bryan adams/tina turner
1877                         c+c music factory/f. williams
1906                                       calexico / iron
2000             carlos santana/mahavishnu john mclaughlin
2102                 celine dion/cher/dixie chicks/shakira
2218                         cheryl barnes/hair soundtrack
2388                                 cipha sounds/mr. choc
2511                         cole swindell / lainey wilson
2928     dave koz/gerald albright/mindi abair/richard e...
2955                         david bowie/pat metheny group
3131                            deliverance/eric weissberg
3306                     disturbed/chevelle/taproot/unloco
3335                            dj lil' cee/trevor simpson
3340                           dj muggs vs. gza/the genius
3348                             dj premier/bumpy knuckles
3355                              dj skribble / vic latino
3394                                 domingo/ross/carreras
3462                               donovan/jeff beck group
3632                  earl scruggs/doc watson/ricky skaggs
3786                             elton john / leon russell
3838                                            eno / hyde
4193                                        foreigner/styx
4328                                  friends/eric clapton
4342                     fu-schnickens w/ shaquille o'neal
4521                             george michael/elton john
4549                                    gershwin/wodehouse
4622                             glen campbell/anne murray
4637                             gloria gaither/t.d. jakes
4644                               gloria walker/chevelles
4829                                    h-town/al b. sure!
5133                                               huntr/x
5134                                         huntr/x: ejae
5229                    immortal technique/dj green latern
5264                                           inoj/lathun
5556       jay farrar/will johnson/anders parker/yim yames
5568                                     jay-z/linkin park
5616                            jeff wayne/various artists
5647                        jennifer warnes/chris thompson
5780                            jimmie walker/esther rolle
5887           joe hisaishi / royal philharmonic orchestra
5902                   joe satriani/eric johnson/steve vai
5991     john lennon/plastic ono band yoko ono/plastic ...
6000             john mcdermott/anthony kearns/ronan tynan
6043                       john williams/"jaws" soundtrack
6044               john williams/the boston pops orchestra
6045                 john williams/yo-yo ma/itzhak perlman
6065                             johnny cash/willie nelson
6087                        johnny mathis/deniece williams
6176            jose carreras/natalie cole/placido domingo
6177     jose carreras/placido domingo/luciano pavarott...
6199       joshua bell/academy of st. martin in the fields
6200                               joshua bell/jeremy denk
6233                           juan gabriel / rocio durcal
6263      julia fischer/academy of st martin in the fields
6359                             kacey cisyk/original cast
6491                         keith jarrett / charlie haden
7061                      lft church choir/hezekiah walker
7111                                lil scrappy/trillville
7185                  lindsey buckingham / christine mcvie
7357                              los temerarios/los bukis
7374                                    lou reed/john cale
7617                      mannheim steamroller/c.w. mccall
7618     mannheim steamroller/czech philharmonic orchestra
7619     mannheim streamroller/czech philharmonic orche...
7756                           marvin hamlisch/"the sting"
7950                            merle haggard/george jones
7967                                        meth/ghost/rae
8027                michael zager's moon band/peabo bryson
8033           michelle amato/sarah moore/michelle lindahl
8256     mormon tabernacle choir/orchestra at temple sq...
8257     mormon tabernacle choir/orchestra at temple sq...
8337      music from bill cosby show/grover washington,jr.
8503     new found glory/international superheroes of h...
8567                                       nielsen/pearson
8749           olivia newton-john/electric light orchestra
8784           orchestra at temple square (jessop/wilberg)
8819              otis redding/the jimi hendrix experience
8929     pat metheny/chris potter/ben williams/antonio ...
8970                                 paul anka/odia coates
8997                             paul mccartney/carl davis
9011                                paul simon/phoebe snow
9100                             pete rock / smif-n-wessun
9120                               peter gabriel/kate bush
9233             placido domingo/ying huang/michael bolton
9350                                   prince/bria valente
9507                                           rancid/nofx
9706                                rex smith/rachel sweet
9873                          robert plant / alison krauss
9983                           ronald isley/burt bacharach
10123                            ry cooder / manuel galban
10573                              simon stokes/nighthawks
10575    simone dinnerstein/kammerorchester/staatskapel...
10817                       soundtrack/'weird' al yankovic
10917                            stan getz/astrud gilberto
10918                               stan getz/charlie byrd
11360                                tech n9ne/dj whoo kid
11494                             the alchemist / curren$y
11992          the flaming lips/stardeath and white dwarfs
12186                         the isley brothers / santana
12312          the london symphony orchestra/john williams
13313    tony bennett/charlotte church/placido domingo/...
13314                            tony bennett/dave brubeck
13641                      vanessa williams/brian mcknight
13924                                     williams/perlman
13935                        willie nelson / merle haggard
13936            willie nelson / merle haggard / ray price
14001                                  wu-tang/mathematics
14082                 ymusic/nashville symphony (guerrero)
14093                 yo-yo ma / chris thile / edgar meyer
14094                             yo-yo ma / kathryn stott
14095                              yo-yo ma/bobby mcferrin
14096                   yo-yo ma/edgar meyer/mark o'connor
14097       yo-yo ma/stuart duncan/edgar meyer/chris thile
14098    yo-yo ma/the silk road ensemble/chicago sympho...
14190                                  zayn / taylor swift

Keeping:
48                                            20/20
202                                           ac/dc
291        al dimeola/john mclaughlin/paco de lucia
1434                             bob dylan/the band
1439                        bob james/david sanborn
1440                           bob james/earl klugh
2038                                case/lang/veirs
2617                   courtney barnett / kurt vile
2621                                 coverdale/page
2725                             czarface / mf doom
2810                     dan fogelberg/tim weisberg
2964                       david crosby/graham nash
3097                        dee gees / foo fighters
3650                                        ebn/ozn
4491                                     genius/gza
4499                       george benson/earl klugh
4827                                     gza/genius
5124                                  hughes/thrall
5169                         ian hunter/mick ronson
5765                       jim morrison / the doors
5940               john & yoko/the plastic ono band
5967            john fogerty/the blue ridge rangers
5988                         john lennon / yoko ono
5990                   john lennon/plastic ono band
6277                     julie driscoll/brian auger
6356                                           k/da
6492     keith jarrett/gary peacock/jack dejohnette
7401                                      love/hate
7505                                      m/a/r/r/s
8206                          mojo nixon/skid roper
8465                       neil young / crazy horse
8466                         neil young/crazy horse
8467            neil young/international harvesters
8852                     ozzy osbourne/randy rhoads
8991                paul kantner/jefferson starship
9041                     peabo bryson/roberta flack
9634                              redman/method man
9986                            roni size/reprazent
10085                              rufus/chaka khan
10924                    stanley clarke/george duke
10938                           starlito / don trip
11129                      sugarloaf/jerry corbetta
11577                    the benoit/freeman project
11748           the clayton/hamilton jazz orchestra
12620             the raelets/ray charles orchestra
12736                     the sanford/townsend band
12892                       the tarney/spencer band
12923          the tonight show band/doc severinsen
14185                                 zappa/mothers

In [27]:
# Commit slash drops
df_artists = df_artists[~slash_drop].copy()
print(f'df_artists after slash drops: {df_artists.shape}')

df_artists after slash drops: (13818, 54)

In [28]:
# Preview parenthetical entries
paren_mask = df_artists['name'].str.contains(r'\(', regex=True)
print(f'{paren_mask.sum()} rows:')
print(df_artists.loc[paren_mask, 'name'].to_string())

91 rows:
0                                        !!! (chk chk chk)
18                                                   (+44)
19                                                (g)i-dle
20                                              (hed) p.e.
21                                      (hed) planet earth
22                             (the preacher) bobby womack
96                                     4*town (from disney
134                                      ? (question mark)
281                                al (he's the king) hirt
469                             amil (of major coinz) & ja
473                  amsterdam baroque orchestra (koopman)
568                                    anita cochran (duet
823                               b.c.g. (b.c. generation)
830                              b.m.u. (black men united)
899                               band (ohio untouchables)
1072                       berliner symphoniker (marturet)
1130                       big dee irwin (with little eva)
1683                                bri (briana babineaux)
1815                            buddy guy (with g.e. smith
1929                      camerata antonio lucio (francis)
2027                   carreras-domingo-pavarotti (levine)
2281                    chris christian (with amy holland)
2358                   chubby checker (with dee dee sharp)
2814                                        dan hill (duet
3274                                        dion (di muci)
3389                                    dolly parton (duet
3681                     eddie money (with valerie carter)
3888                                    ernie (jim henson)
3975                           f.l.y. (fast life yungstaz)
4089                                           fiona (duet
4513                                   george lamond (duet
4539                                   gerald levert (duet
5051                                    hollywood(mauceri)
5160                       i.a.p. co. (the italian asphalt
5180                              ice cream man (master p)
5589                       jean stapleton (as the bunkers)
5592                            jeanette (baby) washington
5645                                   jennifer rush (duet
6050                 johnnie taylor (the soul philosopher)
6158                             jono (choir of 40 voices)
6297               junge suddeutsche philharmonia (guller)
6498                                     keith sweat (duet
6536                    kenny g. (vocal by lenny williams)
6555                                   kermit (jim henson)
6593                                           kiara (duet
6992                        leningrad soloists (ganitvarg)
7218                                       lita ford (duet
7293                           london phil. orch. (palmer)
7295                            london symphony (williams)
7297                    london symphony orchestra (foster)
7298                    london symphony orchestra (horner)
7299                  london symphony orchestra (williams)
7300                         london voices (john williams)
7504                         m.v.p. (most valuable playas)
7690                   mark knopfler (original soundtrack)
7933                               memphis bleek (& jay-z)
8280                            mount westmore (snoop dogg
8294                         mr. marcelo (from the ghetto)
9010              paul simon (with the dixie hummingbirds)
9026                                     paula abdul (duet
9033                                      pavarotti (metha
9052                            pebbles (with salt-n-pepa)
9113                                    peter cetera (duet
9278                                    pooh-man (mc pooh)
9304                           powersource (solo...sharon)
9308                                   pras (with ky-mani)
9473     raekwon guest starring tony starks (ghost face...
9965                roma sinfonietta orchestra (morricone)
10093    rundfunkorchester des sudweatfutnks baden-bade...
10506                                  shirley (& company)
10559                               silk sonic (bruno mars
10632                                         sky (arista)
10633                                            sky (rca)
11205                    sweet sensation (with romeo j.d.)
11234                                         sylvia (r&b)
11523                the artist (formerly known as prince)
11557                            the barbusters (joan jett
11901                              the dukes (& duchesses)
12130                      the hippies (formerly the tams)
12306              the london classical orchestra (wilson)
12307               the london festival orchestra (knight)
12311    the london symphony orchestra & the english ch...
12722                           the ruffin brothers (jimmy
12784                      the singing nun (soeur sourire)
12879                       the swell season (glen hansard
12975                          the valentinos (the lovers)
13230                               together? (soundtrack)
13549                                tyrese (aka black-ty)
13787                                        was (not was)
13796                                         wax (rapper)
14002                               wyatt (earp) mcpherson

In [30]:
# Drop parenthetical entries that are duet credits, conductor qualifiers, or role qualifiers
# Keep entries where parentheses are part of the artist name
PAREN_KEEP = {
    '!!! (chk chk chk)', '(+44)', '(g)i-dle', '(hed) p.e.',
    '(hed) planet earth', '? (question mark)', 'b.m.u. (black men united)',
    'f.l.y. (fast life yungstaz)', 'm.v.p. (most valuable playas)',
    'was (not was)', 'ernie (jim henson)', 'kermit (jim henson)',
    'ice cream man (master p)', 'pooh-man (mc pooh)', 'tyrese (aka black-ty)',
    'bri (briana babineaux)', 'sky (arista)', 'shirley (& company)',
    'b.c.g. (b.c. generation)', 'the valentinos (the lovers)',
    'the hippies (formerly the tams)', '4*town (from disney',
    'mount westmore (snoop dogg', 'silk sonic (bruno mars',
    'the swell season (glen hansard', 'the barbusters (joan jett',
    'the ruffin brothers (jimmy', 'i.a.p. co. (the italian asphalt',
    'mr. marcelo (from the ghetto)',
}

paren_mask = df_artists['name'].str.contains(r'\(', regex=True)
paren_drop = paren_mask & ~df_artists['name'].isin(PAREN_KEEP)

print(f'Dropping {paren_drop.sum()}, keeping {(paren_mask & df_artists["name"].isin(PAREN_KEEP)).sum()}')
print('\nDropping:')
print(df_artists.loc[paren_drop, 'name'].to_string())
print('\nKeeping:')
print(df_artists.loc[paren_mask & df_artists['name'].isin(PAREN_KEEP), 'name'].to_string())

df_artists = df_artists[~paren_drop].copy()
print(f'\ndf_artists after parenthetical drops: {df_artists.shape}')

Dropping 62, keeping 29

Dropping:
22                             (the preacher) bobby womack
281                                al (he's the king) hirt
469                             amil (of major coinz) & ja
473                  amsterdam baroque orchestra (koopman)
568                                    anita cochran (duet
899                               band (ohio untouchables)
1072                       berliner symphoniker (marturet)
1130                       big dee irwin (with little eva)
1815                            buddy guy (with g.e. smith
1929                      camerata antonio lucio (francis)
2027                   carreras-domingo-pavarotti (levine)
2281                    chris christian (with amy holland)
2358                   chubby checker (with dee dee sharp)
2814                                        dan hill (duet
3274                                        dion (di muci)
3389                                    dolly parton (duet
3681                     eddie money (with valerie carter)
4089                                           fiona (duet
4513                                   george lamond (duet
4539                                   gerald levert (duet
5051                                    hollywood(mauceri)
5589                       jean stapleton (as the bunkers)
5592                            jeanette (baby) washington
5645                                   jennifer rush (duet
6050                 johnnie taylor (the soul philosopher)
6158                             jono (choir of 40 voices)
6297               junge suddeutsche philharmonia (guller)
6498                                     keith sweat (duet
6536                    kenny g. (vocal by lenny williams)
6593                                           kiara (duet
6992                        leningrad soloists (ganitvarg)
7218                                       lita ford (duet
7293                           london phil. orch. (palmer)
7295                            london symphony (williams)
7297                    london symphony orchestra (foster)
7298                    london symphony orchestra (horner)
7299                  london symphony orchestra (williams)
7300                         london voices (john williams)
7690                   mark knopfler (original soundtrack)
7933                               memphis bleek (& jay-z)
9010              paul simon (with the dixie hummingbirds)
9026                                     paula abdul (duet
9033                                      pavarotti (metha
9052                            pebbles (with salt-n-pepa)
9113                                    peter cetera (duet
9304                           powersource (solo...sharon)
9308                                   pras (with ky-mani)
9473     raekwon guest starring tony starks (ghost face...
9965                roma sinfonietta orchestra (morricone)
10093    rundfunkorchester des sudweatfutnks baden-bade...
10633                                            sky (rca)
11205                    sweet sensation (with romeo j.d.)
11234                                         sylvia (r&b)
11523                the artist (formerly known as prince)
11901                              the dukes (& duchesses)
12306              the london classical orchestra (wilson)
12307               the london festival orchestra (knight)
12311    the london symphony orchestra & the english ch...
12784                      the singing nun (soeur sourire)
13230                               together? (soundtrack)
13796                                         wax (rapper)
14002                               wyatt (earp) mcpherson

Keeping:
0                      !!! (chk chk chk)
18                                 (+44)
19                              (g)i-dle
20                            (hed) p.e.
21                    (hed) planet earth
96                   4*town (from disney
134                    ? (question mark)
823             b.c.g. (b.c. generation)
830            b.m.u. (black men united)
1683              bri (briana babineaux)
3888                  ernie (jim henson)
3975         f.l.y. (fast life yungstaz)
5160     i.a.p. co. (the italian asphalt
5180            ice cream man (master p)
6555                 kermit (jim henson)
7504       m.v.p. (most valuable playas)
8280          mount westmore (snoop dogg
8294       mr. marcelo (from the ghetto)
9278                  pooh-man (mc pooh)
10506                shirley (& company)
10559             silk sonic (bruno mars
10632                       sky (arista)
11557          the barbusters (joan jett
12130    the hippies (formerly the tams)
12722         the ruffin brothers (jimmy
12879     the swell season (glen hansard
12975        the valentinos (the lovers)
13549              tyrese (aka black-ty)
13787                      was (not was)

df_artists after parenthetical drops: (13756, 54)

In [32]:
# Rescue the singing nun from the original CSV
original = pd.read_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv')
singing_nun = original[original['name'] == 'the singing nun (soeur sourire)'].copy()
singing_nun['name'] = 'the singing nun'
df_artists = pd.concat([df_artists, singing_nun], ignore_index=True)
print(f'df_artists after re-adding singing nun: {df_artists.shape}')
print(df_artists[df_artists['name'] == 'the singing nun'][['name', 'total_charting_songs', 'first_song_year']])

df_artists after re-adding singing nun: (13757, 54)
                  name  total_charting_songs  first_song_year
13756  the singing nun                     1           1963.0

In [33]:
# Preview orchestra/ensemble entries
orch_mask = df_artists['name'].str.contains(r'\borchestra\b|\bband\b|\bhis \b|\bher \b', regex=True)
print(f'{orch_mask.sum()} rows:')
print(df_artists.loc[orch_mask, 'name'].to_string())

338 rows:
136                                      a ragamuffin band
213                                               adc band
263                            al caiola and his orchestra
369                                        all sports band
381                                   allman brothers band
409              amanda palmer & the grand theft orchestra
634                       arkansas junior high school band
637                                       armada orchestra
652                           art mooney and his orchestra
752                                     average white band
785          b.b.king and the royal philharmonic orchestra
827                                      bad boy's da band
847                                      baja marimba band
853                                      ballas hough band
859                                                   band
860                                            band aid 30
861                                           band mcnally
862                                           band of gold
863                                         band of horses
864                                         band of skulls
865                                band of the black watch
866                                               band-aid
1022                             bent fabric and his piano
1032                                 bernie lowe orchestra
1034                      bert kaempfert and his orchestra
1070                                       biddu orchestra
1088                              big jay mcneely and band
1143                             bill haley and his comets
1210                        billy vaughn and his orchestra
1375                                    bob dylan/the band
1395                    bob seger & the silver bullet band
1424                           bobby gregg and his friends
1495                                        bonzo dog band
1512                      boots brown and his blockbusters
1514                          boots randolph and his combo
1517                                  bootsy's rubber band
1529                                 boston pops orchestra
1530                  boston pops orchestra arthur fiedler
1701                 bruce springsteen & the e street band
1702               bruce springsteen and the e street band
1793              buster poindexter & his banshees of blue
1875                         cannonball adderley orchestra
1887                    captain beefheart & his magic band
1888                    captain beefheart & the magic band
1961                                    casey donahew band
2079                                  charlie daniels band
2084                                     charlie hall band
2187                              chris barber's jazz band
2361                                     climax blues band
2440               commander cody & his lost planet airmen
2467               conor oberst and the mystic valley band
2480                               cookie and his cupcakes
2486                                  cooper brothers band
2627                     cyril stapleton and his orchestra
2766                        danny zella and his zell rocks
2828                                    dave matthews band
2851                       david carroll and his orchestra
2859                                    david crowder band
2932                                             dazz band
3042               dennis coffey & the detroit guitar band
3077                                      desperation band
3239                                              dlr band
3276                don costa and his orchestra and chorus
3287                                     don harrison band
3374                  dr. buzzard's original savannah band
3442                          duane eddy his twangy guitar
3476                                   dwight twilley band
3568                         edmundo ros and his orchestra
3607                              electric light orchestra
3616                                        eli young band
3718                             eric clapton and his band
3726                                      eric martin band
3778                                     euclid beach band
3846                                            faith band
3906                               felix slatkin orchestra
3974                              five man electrical band
4082                         francis lai and his orchestra
4086                                frank barber orchestra
4089                   frank devol and his rainbow strings
4118                                   frankie miller band
4153                                     freddy jones band
4213                                            furay band
4245                                    gaither vocal band
4552                                      graeme edge band
4590                                        greg kihn band
4797                          henri rene and his orchestra
4801                       henry mancini concert orchestra
4802                                       henry paul band
4852                           his buckingham road quintet
4853                                            his clowns
4854                                     his cowboy outfit
4855                                his electric eclectics
4856                                           his friends
4857                                            his guitar
4858                          his johann strauss orchestra
4859                                 his musette orchestra
4860                                             his orch.
4861                                            his pianos
4862                              his talking steel guitar
4863                            his whispering organ sound
4998                          ian hunter and the rant band
5066                                 incredible bongo band
5067                                incredible string band
5195                                jack laforge his piano
5280                                       james last band
5292                                james walsh gypsy band
5309            jamo thomas & his party brothers orchestra
5487                                     jerry garcia band
5497                 jerry lee lewis and his pumping piano
5597                            jimmy beck & his orchestra
5604                         jimmy clanton and his rockets
5695                         joe harnell and his orchestra
5709                                joe rene and orchestra
5749                      john & yoko/the plastic ono band
5752                          john barry and his orchestra
5758                 john cafferty & the beaver brown band
5768                  john davis and the monster orchestra
5798                          john lennon plastic ono band
5799                          john lennon/plastic ono band
5834                  john scott trotter and his orchestra
5902                                  johnny van zant band
5904                    johnny wakelin & the kinshasa band
5934                              jon thomas and orchestra
5982                                      josh abbott band
6095                                             junk band
6149                               kai winding & orchestra
6247                                              kbc band
6258                                     keef hartley band
6297     ken darby singers & john scott trotter & his o...
6303                            kenny ball and his jazzmen
6324                             kenny wayne shepherd band
6433                    king sunny ade & his african beats
6632        larry elgart and his manhattan swing orchestra
6649                                    larsen-feiten band
6650                                    larson-fetten band
6694                           lawrence welk his orchestra
6723                                lee allen and his band
6943                               link wray & his ray men
6994                                     little river band
7038                         london philharmonic orchestra
7039                             london symphony orchestra
7045                  lonnie donegan and his skiffle group
7132                     love childs afro cuban blues band
7136                              love unlimited orchestra
7213                        lyle lovett and his large band
7307                                  mahavishnu orchestra
7308                  mahavishnu orchestra john mclaughlin
7335                                  manchester orchestra
7346                             manfred mann's earth band
7350                          manny kellem - his orchestra
7419                                     mark lanegan band
7446                                  marshall tucker band
7458                        martin denny and his orchestra
7475            marty stuart and his fabulous superlatives
7564                                       max demian band
7720     michael kamen conducting the san francisco sym...
7729             michael nesmith & the first national band
7738                                  michael stanley band
7817                               mike theodore orchestra
7888                      mitchell ayers and his orchestra
7889                      mitchell ayres and his orchestra
7931                                 mongo santamaria band
7942                                     montana orchestra
7947                         monty kelly and his orchestra
7965     mormon tabernacle choir and orchestra at templ...
8304                                nitty gritty dirt band
8419                                    ohio marching band
8475                                             orchestra
8476                 orchestra conducted by gordon jenkins
8510                          otis williams and his charms
8596                                          passion band
8598                                  passion worship band
8608                                        pat mcgee band
8617                                      pat travers band
8630                    patrick williams and his orchestra
8657                        paul chaplain and his emeralds
8668                 paul humphrey & his cool aid chemists
8703                                       paula cole band
8787                                   peter frampton band
8905                                      plastic ono band
8963                                    pousette-dart band
8978                           preservation hall jazz band
9172                                     randy rogers band
9204               ray charles + the count basie orchestra
9207                             ray conniff his orchestra
9230                     raymond lefevre and his orchestra
9293                              reg owen & his orchestra
9348                       reverend peyton's big damn band
9359                                     rhett walker band
9394                      richard hayman and his orchestra
9404                                     richie furay band
9418                        rick dees & his cast of idiots
9424                 rick nelson and the stone canyon band
9492                                      robbie seay band
9494                                  robbin thompson band
9498                                      robert cray band
9514                               robert maxwell his harp
9521                     robert randolph & the family band
9608                                          rollins band
9639                         ronnie love and his orchestra
9666                               rossington collins band
9693                          royal philharmonic orchestra
9694     royal philharmonic orchestra conducted by loui...
9819                                     salsoul orchestra
9863                          sammy kaye and his orchestra
9912                                   saturday night band
10213                sir chauncey and his exciting strings
10413                                       soul orchestra
10469                                         spencer band
10545                                  starland vocal band
10634                                     steve morse band
10667                                      stone city band
10800                                           sweat band
10859                                     t.h.p. orchestra
10972                                 tedeschi trucks band
11051                            the 101 strings orchestra
11072    the abnuceals emuukha electric symphony orchestra
11094                             the allman brothers band
11123                               the atlanta disco band
11132                the baby einstein music box orchestra
11138                                the baja marimba band
11143                                             the band
11144                                      the band camino
11145                          the band of the black watch
11146                                       the band perry
11173                                        the beta band
11175                                  the biddu orchestra
11176                                         the big band
11221                                        the boys band
11222                                 the boys in the band
11233                           the brian setzer orchestra
11249                                       the budos band
11258                           the butterfield blues band
11297                           the champs' boys orchestra
11305                             the charlie daniels band
11325                              the chris stainton band
11327                                 the chuck brown band
11330                                   the citizen's band
11339                  the clayton/hamilton jazz orchestra
11341                              the cleveland orchestra
11344                                the climax blues band
11371                             the count basie big band
11410                             the danny joe brown band
11418                                the dave edmunds band
11433                                 the del mccoury band
11441                                the derek trucks band
11442                                 the desert rose band
11450                                the dickey betts band
11455                                     the dillman band
11458                                        the dirt band
11459                           the dirty dozen brass band
11471                                the don harrison band
11476                                   the doolittle band
11508                         the electric light orchestra
11514                                  the elton john band
11550                                     the fatback band
11635                                         the gap band
11653                           the glenn miller orchestra
11655                                     the glitter band
11675                                the gregg allman band
11683                  the hamilton philharmonic orchestra
11703                                  the henry paul band
11753                            the incredible bongo band
11766                             the invisible man's band
11774                                    the j. geils band
11792                                 the jeff healey band
11798                                 the jim carroll band
11802                                  the joe chemay band
11806                                   the john hall band
11808                              the johnny average band
11831                        the kenny wayne shepherd band
11837                                    the kiki dee band
11872                              the laurie berkner band
11889                    the london philharmonic orchestra
11891                        the london symphony orchestra
11907                                         the mac band
11920                             the mahavishnu orchestra
11930                                 the marc tanner band
11938                             the marshall tucker band
11968                             the michael stanley band
11969                               the michael zager band
11970                           the michel georgiades band
12023                              the naked brothers band
12027                           the nashville tribute band
12029                      the national symphony orchestra
12033                          the nelson riddle orchestra
12051                              the new vaudeville band
12061                           the nitty gritty dirt band
12078                             the octavarium orchestra
12082                                   the one truth band
12084             the orchestra & chorus of gordon jenkins
12085                             the orchestra of ireland
12123                      the paul butterfield blues band
12138                                   the phantom's band
12146    the pipes and drums and the military band of t...
12151                                 the plastic ono band
12152                         the plastic ono nuclear band
12167                               the pousette dart band
12194                    the raelets/ray charles orchestra
12213                            the ray charles orchestra
12257                             the robbin thompson band
12259                                 the robert cray band
12281                                  the rossington band
12282                          the rossington collins band
12288             the royal philharmonic concert orchestra
12289                     the royal philharmonic orchestra
12303                                      the s.o.s. band
12305                                the salsoul orchestra
12310                            the sanford/townsend band
12325                                    the sessions band
12366                                        the snl band)
12403                  the starlight orchestra and singers
12412                               the steve gibbons band
12413                                the steve miller band
12438                                    the sunshine band
12454                        the sydney symphony orchestra
12456                               the synconic orchestra
12462                              the tarney/spencer band
12485                                the tim weisberg band
12491                           the tommy dorsey orchestra
12492    the tommy dorsey orchestra starring warren cov...
12493                 the tonight show band/doc severinsen
12523                       the twisted brown trucker band
12588                               the walter murphy band
12597                   the watts 103rd street rhythm band
12603                                    the whatnaut band
12626                                      the wonder band
12956                             trans-siberian orchestra
12978                                      treat her right
13061                                    twelve girls band
13149                                 universal robot band
13152                             unknown mortal orchestra
13221                                 vertical church band
13323                   walter murphy & the big apple band
13337                                   warren haynes band
13497                             wilton place street band
13609                               yellow magic orchestra
13706                                       zac brown band

In [34]:
# Step 1: Drop artifact fragments and generic entries
orch_drop = df_artists['name'].isin({
    'his buckingham road quintet', 'his clowns', 'his cowboy outfit',
    'his electric eclectics', 'his friends', 'his guitar',
    'his johann strauss orchestra', 'his musette orchestra', 'his orch.',
    'his pianos', 'his talking steel guitar', 'his whispering organ sound',
    'orchestra', 'orchestra conducted by gordon jenkins',
})
df_artists = df_artists[~orch_drop].copy()
print(f'df_artists after artifact drops: {df_artists.shape}')

df_artists after artifact drops: (13743, 54)

In [35]:
# Step 2: Find duplicates caused by leading "the"
def strip_leading_the(s):
    return re.sub(r'^the ', '', s).strip()

df_artists['name_no_the'] = df_artists['name'].apply(strip_leading_the)

the_dupes = df_artists[df_artists.duplicated('name_no_the', keep=False)].sort_values('name_no_the')
print(f'Duplicate pairs with/without "the": {len(the_dupes)}')
print(the_dupes[['name', 'name_no_the', 'total_charting_songs']].to_string())

Duplicate pairs with/without "the": 260
                                       name                       name_no_the  total_charting_songs
97                             5 stairsteps                      5 stairsteps                     2
11067                      the 5 stairsteps                      5 stairsteps                     2
217                        addrisi brothers                  addrisi brothers                     6
11077                  the addrisi brothers                  addrisi brothers                     0
299                               alchemist                         alchemist                     0
11088                         the alchemist                         alchemist                     1
11094              the allman brothers band              allman brothers band                    10
381                    allman brothers band              allman brothers band                     0
11115                      the art of noise                      art of noise                     2
655                            art of noise                      art of noise                     1
11124            the atlanta rhythm section            atlanta rhythm section                     0
704                  atlanta rhythm section            atlanta rhythm section                    14
847                       baja marimba band                 baja marimba band                     3
11138                 the baja marimba band                 baja marimba band                     1
859                                    band                              band                     1
11143                              the band                              band                     8
865                 band of the black watch           band of the black watch                     0
11145           the band of the black watch           band of the black watch                     1
11148                          the bar-kays                          bar-kays                     4
881                                bar-kays                          bar-kays                     5
958                           beau brummels                     beau brummels                     1
11161                     the beau brummels                     beau brummels                     5
1070                        biddu orchestra                   biddu orchestra                     2
11175                   the biddu orchestra                   biddu orchestra                     0
11186                   the black eyed peas                   black eyed peas                    16
1250                        black eyed peas                   black eyed peas                     2
1672                        brooklyn bridge                   brooklyn bridge                     3
11238                   the brooklyn bridge                   brooklyn bridge                     4
11240                the brotherhood of man                brotherhood of man                     3
1684                     brotherhood of man                brotherhood of man                     1
11251                           the buggles                           buggles                     1
1759                                buggles                           buggles                     0
11255                          the bus boys                          bus boys                     0
1786                               bus boys                          bus boys                     1
1886                     captain & tennille                captain & tennille                    13
11276                the captain & tennille                captain & tennille                     1
11283                           the casinos                           casinos                     1
1973                                casinos                           casinos                     1
1992                             cathedrals                        cathedrals                     0
11290                        the cathedrals                        cathedrals                     0
2044                      chambers brothers                 chambers brothers                     2
11295                 the chambers brothers                 chambers brothers                     3
11305              the charlie daniels band              charlie daniels band                     7
2079                   charlie daniels band              charlie daniels band                     0
11323                 the chopper city boyz                 chopper city boyz                     0
2182                      chopper city boyz                 chopper city boyz                     0
11344                 the climax blues band                 climax blues band                     0
2361                      climax blues band                 climax blues band                     4
11393                   the crystal mansion                   crystal mansion                     1
2590                        crystal mansion                   crystal mansion                     1
11431                   the defranco family                   defranco family                     2
3003                        defranco family                   defranco family                     0
11461                       the dirty heads                       dirty heads                     1
3176                            dirty heads                       dirty heads                     0
11471                 the don harrison band                 don harrison band                     1
3287                      don harrison band                 don harrison band                     0
3333                        doobie brothers                   doobie brothers                     0
11475                   the doobie brothers                   doobie brothers                    27
3408                            dreamlovers                       dreamlovers                     1
11483                       the dreamlovers                       dreamlovers                     1
3425                       dropkick murphys                  dropkick murphys                     0
11487                  the dropkick murphys                  dropkick murphys                     0
11489                            the dukays                            dukays                     1
3448                                 dukays                            dukays                     1
3484                      dynamic superiors                 dynamic superiors                     1
11493                 the dynamic superiors                 dynamic superiors                     0
3607               electric light orchestra          electric light orchestra                    24
11508          the electric light orchestra          electric light orchestra                     1
11535                  the fabulous poodles                  fabulous poodles                     0
3837                       fabulous poodles                  fabulous poodles                     1
3866                         fantastic four                    fantastic four                     4
11544                    the fantastic four                    fantastic four                     1
11562                         the fireballs                         fireballs                     7
3949                              fireballs                         fireballs                     1
3952                              fireflies                         fireflies                     1
11563                         the fireflies                         fireflies                     1
3961                            first class                       first class                     2
11566                       the first class                       first class                     1
11568                              the five                              five                     1
3968                                   five                              five                     3
3976                        five stairsteps                   five stairsteps                     4
11574                   the five stairsteps                   five stairsteps                     7
3982                                  flame                             flame                     0
11576                             the flame                             flame                     1
3984                              flamingos                         flamingos                     1
11579                         the flamingos                         flamingos                    10
4162                          free movement                     free movement                     1
11619                     the free movement                     free movement                     1
11626                            the fugees                            fugees                     1
4198                                 fugees                            fugees                     2
4222                                   fuzz                              fuzz                     0
11630                              the fuzz                              fuzz                     3
4253                                   game                              game                     3
11633                              the game                              game                    14
4518                          goo goo dolls                     goo goo dolls                    12
11659                     the goo goo dolls                     goo goo dolls                     0
4573                          grateful dead                     grateful dead                     4
11669                     the grateful dead                     grateful dead                     2
11692                             the hawks                             hawks                     1
4745                                  hawks                             hawks                     1
11697                             the heart                             heart                     1
4762                                  heart                             heart                    29
11703                   the henry paul band                   henry paul band                     0
4802                        henry paul band                   henry paul band                     1
11734                     the house of love                     house of love                     0
4927                          house of love                     house of love                     0
5048                               illusion                          illusion                     0
11748                          the illusion                          illusion                     3
5066                  incredible bongo band             incredible bongo band                     0
11753             the incredible bongo band             incredible bongo band                     1
11754                      the independents                      independents                     4
5070                           independents                      independents                     1
5216                              jackson 5                         jackson 5                    19
11777                         the jackson 5                         jackson 5                     0
5221                               jacksons                          jacksons                     0
11778                          the jacksons                          jacksons                    13
5273                             james gang                        james gang                     2
11784                        the james gang                        james gang                     2
5586                jimi hendrix experience           jimi hendrix experience                     0
11799           the jimi hendrix experience           jimi hendrix experience                     4
11826                       the kalin twins                       kalin twins                     2
6160                            kalin twins                       kalin twins                     2
6324              kenny wayne shepherd band         kenny wayne shepherd band                     0
11831         the kenny wayne shepherd band         kenny wayne shepherd band                     1
11833                         the kid laroi                         kid laroi                    23
6374                              kid laroi                         kid laroi                     1
6750                           lemon pipers                      lemon pipers                     1
11877                      the lemon pipers                      lemon pipers                     2
7038          london philharmonic orchestra     london philharmonic orchestra                     0
11889     the london philharmonic orchestra     london philharmonic orchestra                     0
7039              london symphony orchestra         london symphony orchestra                     1
11891         the london symphony orchestra         london symphony orchestra                     0
7301                         magic lanterns                    magic lanterns                     1
11913                    the magic lanterns                    magic lanterns                     1
11920              the mahavishnu orchestra              mahavishnu orchestra                     0
7307                   mahavishnu orchestra              mahavishnu orchestra                     0
7358                               mar-keys                          mar-keys                     3
11928                          the mar-keys                          mar-keys                     1
7439                              marmalade                         marmalade                     1
11936                         the marmalade                         marmalade                     2
11938              the marshall tucker band              marshall tucker band                     7
7446                   marshall tucker band              marshall tucker band                     0
7653                          memphis horns                     memphis horns                     0
11959                     the memphis horns                     memphis horns                     0
11963                            the meters                            meters                     7
7683                                 meters                            meters                     0
11964                  the metropole orkest                  metropole orkest                     0
7690                       metropole orkest                  metropole orkest                     0
7738                   michael stanley band              michael stanley band                     7
11968              the michael stanley band              michael stanley band                     0
11973              the mighty clouds of joy              mighty clouds of joy                     0
7783                   mighty clouds of joy              mighty clouds of joy                     1
11989                           the moments                           moments                     8
7922                                moments                           moments                     4
7964                mormon tabernacle choir           mormon tabernacle choir                     0
11999           the mormon tabernacle choir           mormon tabernacle choir                     1
12021                             the nails                             nails                     0
8083                                  nails                             nails                     0
12034                 the neon philharmonic                 neon philharmonic                     1
8186                      neon philharmonic                 neon philharmonic                     1
12040                         the new birth                         new birth                     6
8194                              new birth                         new birth                     2
12041       the new broadway cast recording       new broadway cast recording                     0
8197            new broadway cast recording       new broadway cast recording                     0
8198                         new colony six                    new colony six                     4
12044                    the new colony six                    new colony six                     6
8268                          nightcrawlers                     nightcrawlers                     1
12058                     the nightcrawlers                     nightcrawlers                     1
12061            the nitty gritty dirt band            nitty gritty dirt band                     3
8304                 nitty gritty dirt band            nitty gritty dirt band                     4
12064                  the notorious b.i.g.                  notorious b.i.g.                    12
8363                       notorious b.i.g.                  notorious b.i.g.                     2
12089  the original broadway cast recording  original broadway cast recording                     0
8482       original broadway cast recording  original broadway cast recording                     0
12090           the original cast recording           original cast recording                     0
8484                original cast recording           original cast recording                     0
8520                                outlaws                           outlaws                     3
12103                           the outlaws                           outlaws                     1
8521                                outlawz                           outlawz                     0
12104                           the outlawz                           outlawz                     1
8581                          paris sisters                     paris sisters                     1
12114                     the paris sisters                     paris sisters                     4
8743                        people's choice                   people's choice                     2
12130                   the people's choice                   people's choice                     1
8746                     peppermint rainbow                peppermint rainbow                     1
12131                the peppermint rainbow                peppermint rainbow                     1
12151                  the plastic ono band                  plastic ono band                     1
8905                       plastic ono band                  plastic ono band                     2
12179                           the prodigy                           prodigy                     2
9019                                prodigy                           prodigy                     0
9043                       psychedelic furs                  psychedelic furs                     4
12182                  the psychedelic furs                  psychedelic furs                     0
12191                          the radiants                          radiants                     2
9120                               radiants                          radiants                     2
9126                               raeletts                          raeletts                     1
12195                          the raeletts                          raeletts                     1
9152                                ramones                           ramones                     2
12204                           the ramones                           ramones                     1

In [36]:
# Keep the variant with more charting songs for each with/without-"the" pair, then commit
def pick_best_the(group):
    return group['total_charting_songs'].idxmax()

the_dup_rows = df_artists[df_artists.duplicated('name_no_the', keep=False)]
keep_idxs = the_dup_rows.groupby('name_no_the', group_keys=False).apply(
    pick_best_the, include_groups=False
).values
drop_idxs = the_dup_rows.index.difference(keep_idxs)

print(f'Dropping {len(drop_idxs)} rows')
df_artists = df_artists.drop(index=drop_idxs).drop(columns=['name_no_the'])
print(f'df_artists after "the" dedup: {df_artists.shape}')

Dropping 130 rows
df_artists after "the" dedup: (13613, 54)

In [38]:
# Merge Five Stairsteps variants — keep the one with most songs
stairsteps_drop = df_artists['name'].isin({'5 stairsteps', 'the stairsteps'})
df_artists = df_artists[~stairsteps_drop].copy()
print(f'df_artists after stairsteps fix: {df_artists.shape}')

df_artists after stairsteps fix: (13611, 54)

In [39]:
# Check which variant was kept for each pair
all_dup_names = {
    '5 stairsteps', 'the 5 stairsteps', 'addrisi brothers', 'the addrisi brothers',
    'alchemist', 'the alchemist', 'allman brothers band', 'the allman brothers band',
    'art of noise', 'the art of noise', 'atlanta rhythm section', 'the atlanta rhythm section',
    'baja marimba band', 'the baja marimba band', 'band', 'the band',
    'band of the black watch', 'the band of the black watch', 'bar-kays', 'the bar-kays',
    'beau brummels', 'the beau brummels', 'biddu orchestra', 'the biddu orchestra',
    'black eyed peas', 'the black eyed peas', 'brooklyn bridge', 'the brooklyn bridge',
    'brotherhood of man', 'the brotherhood of man', 'buggles', 'the buggles',
    'bus boys', 'the bus boys', 'captain & tennille', 'the captain & tennille',
    'casinos', 'the casinos', 'cathedrals', 'the cathedrals',
    'chambers brothers', 'the chambers brothers', 'charlie daniels band', 'the charlie daniels band',
    'chopper city boyz', 'the chopper city boyz', 'climax blues band', 'the climax blues band',
    'crystal mansion', 'the crystal mansion', 'defranco family', 'the defranco family',
    'dirty heads', 'the dirty heads', 'don harrison band', 'the don harrison band',
    'doobie brothers', 'the doobie brothers', 'dreamlovers', 'the dreamlovers',
    'dropkick murphys', 'the dropkick murphys', 'dukays', 'the dukays',
    'dynamic superiors', 'the dynamic superiors', 'electric light orchestra', 'the electric light orchestra',
    'fabulous poodles', 'the fabulous poodles', 'fantastic four', 'the fantastic four',
    'fireballs', 'the fireballs', 'fireflies', 'the fireflies',
    'first class', 'the first class', 'five', 'the five',
    'five stairsteps', 'the five stairsteps', 'flame', 'the flame',
    'flamingos', 'the flamingos', 'free movement', 'the free movement',
    'fugees', 'the fugees', 'fuzz', 'the fuzz',
    'game', 'the game', 'goo goo dolls', 'the goo goo dolls',
    'grateful dead', 'the grateful dead', 'hawks', 'the hawks',
    'heart', 'the heart', 'henry paul band', 'the henry paul band',
    'house of love', 'the house of love', 'illusion', 'the illusion',
    'incredible bongo band', 'the incredible bongo band', 'independents', 'the independents',
    'jackson 5', 'the jackson 5', 'jacksons', 'the jacksons',
    'james gang', 'the james gang', 'jimi hendrix experience', 'the jimi hendrix experience',
    'kalin twins', 'the kalin twins', 'kenny wayne shepherd band', 'the kenny wayne shepherd band',
    'kid laroi', 'the kid laroi', 'lemon pipers', 'the lemon pipers',
    'london philharmonic orchestra', 'the london philharmonic orchestra',
    'london symphony orchestra', 'the london symphony orchestra',
    'magic lanterns', 'the magic lanterns', 'mahavishnu orchestra', 'the mahavishnu orchestra',
    'mar-keys', 'the mar-keys', 'marmalade', 'the marmalade',
    'marshall tucker band', 'the marshall tucker band', 'memphis horns', 'the memphis horns',
    'meters', 'the meters', 'metropole orkest', 'the metropole orkest',
    'michael stanley band', 'the michael stanley band', 'mighty clouds of joy', 'the mighty clouds of joy',
    'moments', 'the moments', 'mormon tabernacle choir', 'the mormon tabernacle choir',
    'nails', 'the nails', 'neon philharmonic', 'the neon philharmonic',
    'new birth', 'the new birth', 'new broadway cast recording', 'the new broadway cast recording',
    'new colony six', 'the new colony six', 'nightcrawlers', 'the nightcrawlers',
    'nitty gritty dirt band', 'the nitty gritty dirt band', 'notorious b.i.g.', 'the notorious b.i.g.',
    'original broadway cast recording', 'the original broadway cast recording',
    'original cast recording', 'the original cast recording',
    'outlaws', 'the outlaws', 'outlawz', 'the outlawz',
    'paris sisters', 'the paris sisters', "people's choice", "the people's choice",
    'peppermint rainbow', 'the peppermint rainbow', 'plastic ono band', 'the plastic ono band',
    'prodigy', 'the prodigy', 'psychedelic furs', 'the psychedelic furs',
    'radiants', 'the radiants', 'raeletts', 'the raeletts',
    'ramones', 'the ramones', 'raspberries', 'the raspberries',
    'ray bryant combo', 'the ray bryant combo', 'ren', 'the ren',
    'robbin thompson band', 'the robbin thompson band', 'robert cray band', 'the robert cray band',
    'rolling stones', 'the rolling stones', 'rose', 'the rose',
    'rossington collins band', 'the rossington collins band',
    'royal philharmonic orchestra', 'the royal philharmonic orchestra',
    'salsoul orchestra', 'the salsoul orchestra', 'san remo golden strings', 'the san remo golden strings',
    'secrets', 'the secrets', 'shades of blue', 'the shades of blue',
    'shadows of knight', 'the shadows of knight', 'sherbs', 'the sherbs',
    'smashing pumpkins', 'the smashing pumpkins', 'sons of champlin', 'the sons of champlin',
    'soul sisters', 'the soul sisters', 'spinners', 'the spinners',
    'st. lunatics', 'the st. lunatics', 'status quo', 'the status quo',
    'streets', 'the streets', 'supremes', 'the supremes',
    'swans', 'the swans', 'sweet', 'the sweet',
    "swingin' medallions", "the swingin' medallions", 'temptations', 'the temptations',
    'undisputed truth', 'the undisputed truth', 'van dykes', 'the van dykes',
    'vanilla fudge', 'the vanilla fudge', 'whatnauts', 'the whatnauts',
}

kept = df_artists[df_artists['name'].isin(all_dup_names)][
    ['name', 'total_charting_songs']
].sort_values('name')
print(f'Kept {len(kept)} names (expected ~130):')
print(kept.to_string())

Kept 129 names (expected ~130):
                                   name  total_charting_songs
217                    addrisi brothers                     6
704              atlanta rhythm section                    14
847                   baja marimba band                     3
881                            bar-kays                     5
1070                    biddu orchestra                     2
1786                           bus boys                     1
1886                 captain & tennille                    13
1973                            casinos                     1
1992                         cathedrals                     0
2182                  chopper city boyz                     0
2361                  climax blues band                     4
2590                    crystal mansion                     1
3408                        dreamlovers                     1
3425                   dropkick murphys                     0
3448                             dukays                     1
3484                  dynamic superiors                     1
3607           electric light orchestra                    24
3837                   fabulous poodles                     1
3866                     fantastic four                     4
3952                          fireflies                     1
3961                        first class                     2
3968                               five                     3
4162                      free movement                     1
4198                             fugees                     2
4518                      goo goo dolls                    12
4573                      grateful dead                     4
4745                              hawks                     1
4762                              heart                    29
4802                    henry paul band                     1
4927                      house of love                     0
5216                          jackson 5                    19
5273                         james gang                     2
6160                        kalin twins                     2
7038      london philharmonic orchestra                     0
7039          london symphony orchestra                     1
7301                     magic lanterns                     1
7307               mahavishnu orchestra                     0
7358                           mar-keys                     3
7653                      memphis horns                     0
7690                   metropole orkest                     0
7738               michael stanley band                     7
7783               mighty clouds of joy                     1
8083                              nails                     0
8186                  neon philharmonic                     1
8197        new broadway cast recording                     0
8268                      nightcrawlers                     1
8304             nitty gritty dirt band                     4
8482   original broadway cast recording                     0
8484            original cast recording                     0
8520                            outlaws                     3
8743                    people's choice                     2
8746                 peppermint rainbow                     1
8905                   plastic ono band                     2
9043                   psychedelic furs                     4
9120                           radiants                     2
9126                           raeletts                     1
9152                            ramones                     2
9186                        raspberries                     7
9201                   ray bryant combo                     1
9321                                ren                     0
9494               robbin thompson band                     1
9659                               rose                     4
9666            rossington collins band                     1
9693       royal philharmonic orchestra                     1
9870            san remo golden strings                     1
10040                    shades of blue                     2
10121                            sherbs                     1
10396                  sons of champlin                     1
10414                      soul sisters                     2
10510                      st. lunatics                     1
10694                           streets                     1
10804                             sweet                     6
10818               swingin' medallions                     1
11088                     the alchemist                     1
11094          the allman brothers band                    10
11115                  the art of noise                     2
11143                          the band                     8
11145       the band of the black watch                     1
11161                 the beau brummels                     5
11186               the black eyed peas                    16
11238               the brooklyn bridge                     4
11240            the brotherhood of man                     3
11251                       the buggles                     1
11295             the chambers brothers                     3
11305          the charlie daniels band                     7
11431               the defranco family                     2
11461                   the dirty heads                     1
11471             the don harrison band                     1
11475               the doobie brothers                    27
11562                     the fireballs                     7
11574               the five stairsteps                     7
11576                         the flame                     1
11579                     the flamingos                    10
11630                          the fuzz                     3
11633                          the game                    14
11748                      the illusion                     3
11753         the incredible bongo band                     1
11754                  the independents                     4
11778                      the jacksons                    13
11799       the jimi hendrix experience                     4
11831     the kenny wayne shepherd band                     1
11833                     the kid laroi                    23
11877                  the lemon pipers                     2
11936                     the marmalade                     2
11938          the marshall tucker band                     7
11963                        the meters                     7
11989                       the moments                     8
11999       the mormon tabernacle choir                     1
12040                     the new birth                     6
12044                the new colony six                     6
12064              the notorious b.i.g.                    12
12104                       the outlawz                     1
12114                 the paris sisters                     4
12179                       the prodigy                     2
12259              the robert cray band                     3
12270                the rolling stones                    57
12305             the salsoul orchestra                     5
12320                       the secrets                     1
12332             the shadows of knight                     3
12360             the smashing pumpkins                     8
12391                      the spinners                    29
12408                    the status quo                     2
12441                      the supremes                    43
12445                         the swans                     1
12470                   the temptations                    51
12531              the undisputed truth                     5
12547                     the van dykes                     2
13200                     vanilla fudge                     3
13406                         whatnauts                     2

In [40]:
# Verify no remaining the/non-the duplicates slipped through, and find the missing pair
# Rebuilds name_no_the temporarily to check for any leftover collisions
def strip_leading_the(s):
    return re.sub(r'^the ', '', str(s)).strip()

df_artists['_tmp_no_the'] = df_artists['name'].apply(strip_leading_the)
remaining_dups = df_artists[df_artists.duplicated('_tmp_no_the', keep=False)]
print(f'Remaining the/non-the duplicates after dedup: {len(remaining_dups)}')
if len(remaining_dups):
    print(remaining_dups[['name', '_tmp_no_the', 'total_charting_songs']].sort_values('_tmp_no_the').to_string())

# Cross-check: find any pair from all_dup_names where NEITHER variant appears in df_artists
pair_keys = {}
for n in all_dup_names:
    key = strip_leading_the(n)
    pair_keys.setdefault(key, []).append(n)

in_df = set(df_artists['name'])
missing_pairs = []
for key, variants in pair_keys.items():
    if not any(v in in_df for v in variants):
        missing_pairs.append((key, variants))

print(f'\nPairs in all_dup_names with no surviving row in df_artists: {len(missing_pairs)}')
for key, variants in missing_pairs:
    print(f'  key={key!r}  variants={variants}')

df_artists = df_artists.drop(columns=['_tmp_no_the'])

Remaining the/non-the duplicates after dedup: 0

Pairs in all_dup_names with no surviving row in df_artists: 1
  key='5 stairsteps'  variants=['5 stairsteps', 'the 5 stairsteps']

In [42]:
# Drop known spelling-variant duplicates where the correct spelling is already present
TYPO_DROPS = {
    '30 secnds to mars',   # correct: '30 seconds to mars'
}

typo_mask = df_artists['name'].isin(TYPO_DROPS)
print(f'Dropping {typo_mask.sum()} typo variant(s):')
print(df_artists.loc[typo_mask, ['name', 'total_charting_songs']].to_string())
df_artists = df_artists[~typo_mask].copy()
print(f'df_artists: {df_artists.shape}')

Dropping 1 typo variant(s):
                 name  total_charting_songs
61  30 secnds to mars                     0
df_artists: (13610, 54)

In [43]:
# Drop names with '(' but no ')' — artifacts from comma-splitting
# e.g. "artist (qualifier, detail)" was split at the comma → "artist (qualifier" with no closing paren
# Intentionally truncated entries (already in PAREN_KEEP below) are excluded here
UNMATCHED_PAREN_KEEP = {
    '4*town (from disney',
    'mount westmore (snoop dogg',
    'silk sonic (bruno mars',
    'the swell season (glen hansard',
    'the barbusters (joan jett',
    'the ruffin brothers (jimmy',
    'i.a.p. co. (the italian asphalt',
}

unmatched_mask = (
    df_artists['name'].str.contains(r'\(', regex=True)
    & ~df_artists['name'].str.contains(r'\)', regex=True)
    & ~df_artists['name'].isin(UNMATCHED_PAREN_KEEP)
)

print(f'Dropping {unmatched_mask.sum()} unmatched-paren artifact(s):')
print(df_artists.loc[unmatched_mask, 'name'].to_string())
df_artists = df_artists[~unmatched_mask].copy()
print(f'df_artists: {df_artists.shape}')

Dropping 0 unmatched-paren artifact(s):
Series([], )
df_artists: (13610, 54)

In [46]:
# Load the saved df_artists_clean CSV and use it to restore the dropped rows.
# Update the path below to wherever your file is saved.
saved_path = base + 'df_artists_clean.csv'   # ← update if different

saved = pd.read_csv(saved_path)

# Keep only rows from the saved version that are missing from current df_artists
current_names = set(df_artists['name'])
missing = saved[~saved['name'].isin(current_names)]

# Align columns and concat
rows_to_add = missing[[c for c in df_artists.columns if c in missing.columns]].copy()
df_artists = (
    pd.concat([df_artists, rows_to_add], ignore_index=True)
    .sort_values('name')
    .reset_index(drop=True)
)
print(f'Reinstated {len(rows_to_add)} rows')
print(f'df_artists: {df_artists.shape}')

Reinstated 518 rows
df_artists: (13611, 54)

In [47]:
# Verify the reinstatement — check shape, spot-check known names, and flag any remaining issues

# 1. Shape
print(f'df_artists shape: {df_artists.shape}')

# 2. Spot-check a handful of names that should be back
spot_check = [
    'florence + the machine', 'kool & the gang', 'sly & the family stone',
    'tom petty & the heartbreakers', 'huey lewis & the news',
    'eric b. & rakim', 'dan + shay', 'she & him',
    'bruce springsteen & the e street band', 'echo & the bunnymen',
]
found = df_artists['name'].isin(spot_check)
print(f'\nSpot-check ({found.sum()}/{len(spot_check)} found):')
for name in spot_check:
    status = '✓' if name in df_artists['name'].values else '✗ MISSING'
    print(f'  {status}  {name}')

# 3. Confirm the two entries that SHOULD still be gone
should_be_gone = ['2pac & johnny p', '2pac + outlawz']
print(f'\nShould be absent:')
for name in should_be_gone:
    status = '✗ STILL PRESENT' if name in df_artists['name'].values else '✓ absent'
    print(f'  {status}  {name}')

# 4. Duplicate check
dupes = df_artists[df_artists.duplicated('name', keep=False)]
print(f'\nDuplicate names: {dupes["name"].nunique()} groups')
if len(dupes):
    print(dupes[['name']].drop_duplicates().to_string())

df_artists shape: (13611, 54)

Spot-check (10/10 found):
  ✓  florence + the machine
  ✓  kool & the gang
  ✓  sly & the family stone
  ✓  tom petty & the heartbreakers
  ✓  huey lewis & the news
  ✓  eric b. & rakim
  ✓  dan + shay
  ✓  she & him
  ✓  bruce springsteen & the e street band
  ✓  echo & the bunnymen

Should be absent:
  ✗ STILL PRESENT  2pac & johnny p
  ✗ STILL PRESENT  2pac + outlawz

Duplicate names: 0 groups

In [48]:
# Targeted drop of confirmed one-off collaboration credits
# Add any others you identify to this set
CONFIRMED_COLLAB_DROPS = {
    '2pac & johnny p',
    '2pac + outlawz',
}

drop_mask = df_artists['name'].isin(CONFIRMED_COLLAB_DROPS)
print(f'Dropping {drop_mask.sum()}:')
print(df_artists.loc[drop_mask, 'name'].tolist())
df_artists = df_artists[~drop_mask].copy()
print(f'df_artists: {df_artists.shape}')

Dropping 2:
['2pac & johnny p', '2pac + outlawz']
df_artists: (13609, 54)

In [7]:
# dropping additional unnecessary columns

# Drop specified columns from df_artists
cols_to_drop = [
    'first_album_year',
    'total_charting_songs',
    'total_charting_albums',
    '#1_hit_song_count',
    '#1_hit_album_count',
    'top_10_song_count',
    'top_10_album_count',
    'highest_charting_song_name',
    'highest_charting_song_position',
    'first_charting_song_name',
    'highest_charting_album_name',
    'highest_charting_album_position',
    'first_charting_album_name',
    'first_charting_album_position',
    'first_charting_album_duration',
    'first_year_top_10_songs',
    'first_year_num1_songs',
    'first_year_on_chart_albums',
    'first_year_top_10_albums',
    'first_year_num1_albums',
    'aggregate_labels',
    'first_top_10_song_#_of_connected_artists_to_labels_single_year',
    'first_top_10_song_#_of_connected_artists_to_labels_past_5_years',
    'first_top_10_song_total_power_of_connected_artists_to_labels_single_year',
    'first_top_10_song_total_power_of_connected_artists_to_labels_past_5_years',
    'first_top_10_song_#_of_connected_artists_to_big3_single_year',
    'first_top_10_song_#_of_connected_artists_to_big3_past_5_years',
    'first_top_10_song_total_power_of_connected_artists_to_big3_single_year',
    'first_top_10_song_total_power_of_connected_artists_to_big3_past_5_years',
    'first_top_10_hit_song_genre_tags',
    'first_top_10_hit_album_genre_tags',
    'top_10_1hit_wonder_song',
    'top_10_1hit_wonder_album',
    'top_10_hitmaker_songs',
    'top_10_hitmaker_albums',
]

df_artists = df_artists.drop(columns=cols_to_drop)
print(f"Remaining columns ({len(df_artists.columns)}): {df_artists.columns.tolist()}")

Remaining columns (19): ['name', 'musicbrainz_artist_id', 'musicbrainz_mbid', 'spotify_id', 'performer_pre_normalized', 'first_song_year', 'years_active_on_charts', 'first_charting_song_position', 'first_charting_song_duration', 'genre_tags_musicbrainz', 'first_year_on_chart_songs', 'genre_tags_through_first_top_10_hit', 'major_genre_categories_through_first_top_10_hit', '#_of_major_genre_categories_through_first_top_10_hit', 'musicbrainz_major_genre_categories', 'musicbrainz_#_of_genres', 'spotify_genres', 'spotify_major_genre_categories', 'combined_major_genre_categories']

# Start here

In [24]:
# Add 5 artist-level columns to df_artists derived from df_songs.
# Joins on musicbrainz_mbid (df_artists) ↔ musicbrainz_artist_id (df_songs),
# with artist name as fallback. Safe to re-run.

# --- Drop existing versions of new columns ---
all_new_cols = [
    'first_top_20_hit_year',
    'first_charting_song_year',
    'last_charting_song_year',
    'years_through_first_top_20_hit',
    '#_of_charting_songs_through_first_top_20_hit',
]
df_artists = df_artists.drop(columns=[c for c in all_new_cols if c in df_artists.columns])

agg_cols = [
    'first_top_20_hit_year',
    'first_charting_song_year',
    'last_charting_song_year',
    '#_of_charting_songs_through_first_top_20_hit',
]

# --- Compute aggregates from df_songs grouped by musicbrainz_artist_id (UUID) ---
top20 = df_songs[df_songs['peak_pos'] <= 20]

first_top20_yr = (
    top20.groupby('musicbrainz_artist_id', dropna=True)['first_charting_year']
    .min().rename('first_top_20_hit_year').reset_index()
)
charting_range = (
    df_songs.groupby('musicbrainz_artist_id', dropna=True)['first_charting_year']
    .agg(first_charting_song_year='min', last_charting_song_year='max')
    .reset_index()
)
aggs_by_id = charting_range.merge(first_top20_yr, on='musicbrainz_artist_id', how='left')
songs_aug = df_songs.merge(first_top20_yr, on='musicbrainz_artist_id', how='left')
counts_by_id = (
    songs_aug[songs_aug['first_charting_year'] <= songs_aug['first_top_20_hit_year']]
    .groupby('musicbrainz_artist_id').size()
    .rename('#_of_charting_songs_through_first_top_20_hit').reset_index()
)
aggs_by_id = aggs_by_id.merge(counts_by_id, on='musicbrainz_artist_id', how='left')

# --- Compute aggregates grouped by artist name (for fallback) ---
first_top20_yr_name = (
    top20.groupby('name', dropna=True)['first_charting_year']
    .min().rename('first_top_20_hit_year').reset_index()
)
charting_range_name = (
    df_songs.groupby('name', dropna=True)['first_charting_year']
    .agg(first_charting_song_year='min', last_charting_song_year='max')
    .reset_index()
)
aggs_by_name = charting_range_name.merge(first_top20_yr_name, on='name', how='left')
songs_aug_name = df_songs.merge(first_top20_yr_name, on='name', how='left')
counts_by_name = (
    songs_aug_name[songs_aug_name['first_charting_year'] <= songs_aug_name['first_top_20_hit_year']]
    .groupby('name').size()
    .rename('#_of_charting_songs_through_first_top_20_hit').reset_index()
)
aggs_by_name = aggs_by_name.merge(counts_by_name, on='name', how='left')

# --- Step 1: Merge by musicbrainz_mbid (df_artists) ↔ musicbrainz_artist_id (df_songs) ---
df_artists = df_artists.merge(
    aggs_by_id,
    left_on='musicbrainz_mbid',
    right_on='musicbrainz_artist_id',
    how='left'
).drop(columns=['musicbrainz_artist_id_y']).rename(columns={'musicbrainz_artist_id_x': 'musicbrainz_artist_id'})

# --- Step 2: Fill unmatched rows via name .map() ---
no_match_mask = df_artists['first_top_20_hit_year'].isna()
name_lookup = aggs_by_name.set_index('name')

for col in agg_cols:
    df_artists.loc[no_match_mask, col] = df_artists.loc[no_match_mask, 'name'].map(name_lookup[col])

# --- Step 3: Derived column ---
df_artists['years_through_first_top_20_hit'] = (
    df_artists['first_top_20_hit_year'] - df_artists['first_charting_song_year'] + 1
)

# --- Step 4: Reorder ---
existing = [c for c in df_artists.columns if c not in all_new_cols]
insert_at = existing.index('performer_pre_normalized') + 1
col_order = existing[:insert_at] + all_new_cols + existing[insert_at:]
df_artists = df_artists[col_order]

print(f"df_artists shape: {df_artists.shape}")
print(f"Matched by MBID: {(~no_match_mask).sum():,} | Matched by name: {df_artists.loc[no_match_mask, 'first_top_20_hit_year'].notna().sum():,} | No match: {df_artists['first_top_20_hit_year'].isna().sum():,}")
df_artists[['name', 'musicbrainz_mbid'] + all_new_cols].head(10)

df_artists shape: (13609, 24)
Matched by MBID: 2,853 | Matched by name: 396 | No match: 10,360

,name,musicbrainz_mbid,first_top_20_hit_year,first_charting_song_year,last_charting_song_year,years_through_first_top_20_hit,#_of_charting_songs_through_first_top_20_hit
0,!!! (chk chk chk),NaN,NaN,NaN,NaN,NaN,NaN
1,"""groove"" holmes",NaN,NaN,1966.0,1966.0,NaN,NaN
2,"""little"" jimmy dickens",NaN,1965.0,1965.0,1965.0,1.0,1.0
3,"""pookie"" hudson",29dc9009-015f-47c4-bd17-ed2af6d2ae0c,NaN,1963.0,1963.0,NaN,NaN
4,"""weird al"" yankovic",NaN,1984.0,1983.0,2014.0,2.0,4.0
5,$not,d993169f-2033-4810-bae8-564d4aab89cd,NaN,2021.0,2022.0,NaN,NaN
6,$uicideboy$,ef326b3d-61f0-4379-aca0-21237d696d63,NaN,2024.0,2026.0,NaN,NaN
7,'68,2bf3db78-1032-4111-9e1f-650b556bc2dd,NaN,NaN,NaN,NaN,NaN
8,'n sync,NaN,1998.0,1998.0,2002.0,1.0,3.0
9,'til tuesday,NaN,1985.0,1985.0,1989.0,1.0,2.0

In [25]:
# Cast year and count columns to nullable integer (supports NaN)
int_cols = [
    'first_top_20_hit_year',
    'first_charting_song_year',
    'last_charting_song_year',
    'years_through_first_top_20_hit',
    '#_of_charting_songs_through_first_top_20_hit',
]

for col in int_cols:
    df_artists[col] = df_artists[col].astype('Int64')

df_artists[int_cols].dtypes

first_top_20_hit_year                           Int64
first_charting_song_year                        Int64
last_charting_song_year                         Int64
years_through_first_top_20_hit                  Int64
#_of_charting_songs_through_first_top_20_hit    Int64
dtype: object

In [26]:
df_artists.head()

,name,musicbrainz_artist_id,musicbrainz_mbid,spotify_id,performer_pre_normalized,first_top_20_hit_year,first_charting_song_year,last_charting_song_year,years_through_first_top_20_hit,#_of_charting_songs_through_first_top_20_hit,first_song_year,years_active_on_charts,first_charting_song_position,first_charting_song_duration,genre_tags_musicbrainz,first_year_on_chart_songs,genre_tags_through_first_top_10_hit,major_genre_categories_through_first_top_10_hit,#_of_major_genre_categories_through_first_top_10_hit,musicbrainz_major_genre_categories,musicbrainz_#_of_genres,spotify_genres,spotify_major_genre_categories,combined_major_genre_categories
0,!!! (chk chk chk),<NA>,NaN,NaN,!!! (Chk Chk Chk),<NA>,<NA>,<NA>,<NA>,<NA>,NaN,2007-2007,0,0,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN
1,"""groove"" holmes",<NA>,NaN,NaN,"""Groove"" Holmes",<NA>,1966,1966,<NA>,<NA>,1966.0,1966-1966,44,11,NaN,1966.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN
2,"""little"" jimmy dickens",<NA>,NaN,NaN,"""Little"" Jimmy Dickens",1965,1965,1965,1,1,1965.0,1965-1965,15,10,NaN,1965.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN
3,"""pookie"" hudson",232958.0,29dc9009-015f-47c4-bd17-ed2af6d2ae0c,NaN,"""Pookie"" Hudson",<NA>,1963,1963,<NA>,<NA>,1963.0,1963-1963,96,1,NaN,1963.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN
4,"""weird al"" yankovic",<NA>,NaN,NaN,"""Weird Al"" Yankovic",1984,1983,2014,2,4,1983.0,1983-2014,63,8,NaN,1983.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN

In [29]:
# Merge network metrics into df_artists

# Load df_artists_network_metrics from CSV.

import pandas as pd

df_artists_network_metrics = pd.read_csv(
    '/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists_network_metrics.csv'
)

print(df_artists_network_metrics.shape)
df_artists_network_metrics.head()

(13609, 26)

,name,musicbrainz_artist_id,degree_centrality_top20_yearly,degree_centrality_firstsong_yearly,degree_centrality_top20_rolling5,degree_centrality_firstsong_rolling5,closeness_centrality_top20_yearly,closeness_centrality_firstsong_yearly,closeness_centrality_top20_rolling5,closeness_centrality_firstsong_rolling5,harmonic_closeness_centrality_top20_yearly,harmonic_closeness_centrality_firstsong_yearly,harmonic_closeness_centrality_top20_rolling5,harmonic_closeness_centrality_firstsong_rolling5,betweenness_centrality_top20_yearly,betweenness_centrality_firstsong_yearly,betweenness_centrality_top20_rolling5,betweenness_centrality_firstsong_rolling5,eigenvector_centrality_top20_yearly,eigenvector_centrality_firstsong_yearly,eigenvector_centrality_top20_rolling5,eigenvector_centrality_firstsong_rolling5,power_of_connected_artists_top20_yearly,power_of_connected_artists_firstsong_yearly,power_of_connected_artists_top20_rolling5,power_of_connected_artists_firstsong_rolling5
0,!!! (chk chk chk),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""groove"" holmes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"""little"" jimmy dickens",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""pookie"" hudson",232958.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"""weird al"" yankovic",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Merge 5 network metric columns into df_artists.
# Drops NaN musicbrainz_artist_id rows from metrics before merging
# to prevent NaN-to-NaN cartesian product explosion.

metric_cols = [
    'degree_centrality_top20_rolling5',
    'harmonic_closeness_centrality_top20_rolling5',
    'betweenness_centrality_top20_rolling5',
    'eigenvector_centrality_top20_rolling5',
    'power_of_connected_artists_top20_rolling5',
]

df_artists = df_artists.drop(columns=[c for c in metric_cols if c in df_artists.columns])

metrics_to_merge = df_artists_network_metrics[['musicbrainz_artist_id'] + metric_cols].copy()
for col in ['musicbrainz_artist_id'] + metric_cols:
    metrics_to_merge[col] = pd.to_numeric(metrics_to_merge[col], errors='coerce')

metrics_to_merge = metrics_to_merge.dropna(subset=['musicbrainz_artist_id'])

df_artists['musicbrainz_artist_id'] = pd.to_numeric(df_artists['musicbrainz_artist_id'], errors='coerce')

df_artists = df_artists.merge(metrics_to_merge, on='musicbrainz_artist_id', how='left')

print(df_artists.shape)
print(df_artists[metric_cols].notna().sum())

(13655, 29)
degree_centrality_top20_rolling5                1322
harmonic_closeness_centrality_top20_rolling5    1322
betweenness_centrality_top20_rolling5           1322
eigenvector_centrality_top20_rolling5           1322
power_of_connected_artists_top20_rolling5       1076
dtype: int64

In [41]:
# For each artist's first top-20 hit song in df_songs, map aggregate_major_genre_category_musicbrainz
# to df_artists as 'first_top_20_song_major_genres', placed after combined_major_genre_categories.
# Primary join: df_songs['musicbrainz_artist_id'] (UUID) ↔ df_artists['musicbrainz_mbid']
# Fallback join: name ↔ name, for artists with no UUID match.

# Step 1: isolate first top-20 hit per artist in df_songs
top20_songs = (
    df_songs[df_songs['peak_pos'] <= 20]
    .sort_values(['musicbrainz_artist_id', 'first_charting_year', 'peak_pos'])
    .drop_duplicates(subset=['musicbrainz_artist_id'], keep='first')
)[['musicbrainz_artist_id', 'name', 'aggregate_major_genre_category_musicbrainz']]

# Step 2: build UUID-keyed and name-keyed lookups
uuid_lookup = (
    top20_songs.dropna(subset=['musicbrainz_artist_id'])
    .set_index('musicbrainz_artist_id')['aggregate_major_genre_category_musicbrainz']
)
name_lookup = (
    top20_songs.dropna(subset=['name'])
    .drop_duplicates(subset=['name'], keep='first')
    .set_index('name')['aggregate_major_genre_category_musicbrainz']
)

# Step 3: map via musicbrainz_mbid first, then name fallback
df_artists['first_top_20_song_major_genres'] = df_artists['musicbrainz_mbid'].map(uuid_lookup)

no_match = df_artists['first_top_20_song_major_genres'].isna()
df_artists.loc[no_match, 'first_top_20_song_major_genres'] = df_artists.loc[no_match, 'name'].map(name_lookup)

# Step 4: move column to after combined_major_genre_categories
ref_col = 'combined_major_genre_categories'
cols = list(df_artists.columns)
cols.remove('first_top_20_song_major_genres')
insert_at = cols.index(ref_col) + 1
cols.insert(insert_at, 'first_top_20_song_major_genres')
df_artists = df_artists[cols]

print(df_artists['first_top_20_song_major_genres'].notna().sum(), 'artists mapped')
print(df_artists[['name', 'first_top_20_song_major_genres']].dropna().head(10).to_string(index=False))

1281 artists mapped
          name                                                   first_top_20_song_major_genres
        *nsync                                                                              Pop
10,000 maniacs                                                                             Rock
           112              Electronic/Dance, Hip Hop/Rap, Pop, R&B/Soul/Funk, Reggae/Caribbean
    20 fingers                                                                 Electronic/Dance
      24kgoldn Electronic/Dance, Hip Hop/Rap, Latin, Pop, R&B/Soul/Funk, Reggae/Caribbean, Rock
  3 doors down                                                               Blues, Metal, Rock
    38 special                                                                        Pop, Rock
            3t                                                       Hip Hop/Rap, R&B/Soul/Funk
 4 non blondes                                                                        Pop, Rock
      40 thevz                                         Electronic/Dance, Hip Hop/Rap, Pop, Rock

In [54]:
# Calculate average weeks on chart for top-20 hit songs with first_charting_year 2000–2020.

mask = (
    (df_songs['peak_pos'] <= 20) &
    (df_songs['first_charting_year'].between(2000, 2020))
)

avg_wks = df_songs[mask]['wks_on_chart'].mean()
print(f"Average weeks on chart: {avg_wks:.1f}")

# Calculate deciles of weeks on chart for top-20 songs with first_charting_year 2000–2020.

import numpy as np

deciles = df_songs[mask]['wks_on_chart'].quantile(np.arange(0.1, 1.1, 0.1))
deciles.index = [f"{int(q*100)}th" for q in deciles.index]
print(deciles.to_string())

Average weeks on chart: 24.8
10th     11.0
20th     20.0
30th     20.0
40th     21.0
50th     23.0
60th     26.0
70th     28.0
80th     32.0
90th     39.0
100th    90.0

In [57]:
# Add weeks on chart metric but only for top 20 hit songs

# Add wks_on_chart from df_songs to df_artists for each artist's first top-20 hit song.
# Primary join: df_songs['musicbrainz_artist_id'] (UUID) ↔ df_artists['musicbrainz_mbid']
# Fallback join: name ↔ name

# Step 1: isolate first top-20 hit per artist
first_top20 = (
    df_songs[df_songs['peak_pos'] <= 20]
    .sort_values(['musicbrainz_artist_id', 'first_charting_year', 'peak_pos'])
    .drop_duplicates(subset=['musicbrainz_artist_id'], keep='first')
)[['musicbrainz_artist_id', 'name', 'wks_on_chart']]

# Step 2: build lookups
uuid_lookup = (
    first_top20.dropna(subset=['musicbrainz_artist_id'])
    .set_index('musicbrainz_artist_id')['wks_on_chart']
)
name_lookup = (
    first_top20.dropna(subset=['name'])
    .drop_duplicates(subset=['name'], keep='first')
    .set_index('name')['wks_on_chart']
)

# Step 3: map to df_artists
df_artists['top_20_hit_song_#_wks_on_chart_any_position'] = df_artists['musicbrainz_mbid'].map(uuid_lookup)

no_match = df_artists['top_20_hit_song_#_wks_on_chart_any_position'].isna()
df_artists.loc[no_match, 'top_20_hit_song_#_wks_on_chart_any_position'] = \
    df_artists.loc[no_match, 'name'].map(name_lookup)

print(df_artists['top_20_hit_song_#_wks_on_chart_any_position'].notna().sum(), 'artists mapped')

2890 artists mapped

In [ ]:
# Move top_20_hit_song_#_wks_on_chart_any_position to after first_charting_song_duration.

cols = list(df_artists.columns)
cols.remove('top_20_hit_song_#_wks_on_chart_any_position')
insert_at = cols.index('first_charting_song_duration') + 1
cols.insert(insert_at, 'top_20_hit_song_#_wks_on_chart_any_position')
df_artists = df_artists[cols]

,name,musicbrainz_artist_id,musicbrainz_mbid,spotify_id,performer_pre_normalized,first_top_20_hit_year,first_charting_song_year,last_charting_song_year,years_through_first_top_20_hit,#_of_charting_songs_through_first_top_20_hit,first_song_year,years_active_on_charts,first_charting_song_position,first_charting_song_duration,top_20_hit_song_#_wks_on_chart_any_position,genre_tags_musicbrainz,first_year_on_chart_songs,genre_tags_through_first_top_10_hit,major_genre_categories_through_first_top_10_hit,#_of_major_genre_categories_through_first_top_10_hit,musicbrainz_major_genre_categories,musicbrainz_#_of_genres,spotify_genres,spotify_major_genre_categories,combined_major_genre_categories,first_top_20_song_major_genres,degree_centrality_top20_rolling5,harmonic_closeness_centrality_top20_rolling5,betweenness_centrality_top20_rolling5,eigenvector_centrality_top20_rolling5,power_of_connected_artists_top20_rolling5
0,!!! (chk chk chk),NaN,NaN,NaN,!!! (Chk Chk Chk),NaN,NaN,NaN,NaN,NaN,NaN,2007-2007,0,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""groove"" holmes",NaN,NaN,NaN,"""Groove"" Holmes",NaN,1966.0,1966.0,NaN,NaN,1966.0,1966-1966,44,11,NaN,NaN,1966.0,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Load google_trends_top3000.csv as google_trends_top3000.

google_trends_top3000 = pd.read_csv(
    '/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/google_trends_top3000.csv'
)

print(google_trends_top3000.shape)
google_trends_top3000.head()

# Load billboard_hot100_1958_2026.csv as billboard_hot100_songs, replacing the existing dataframe.

billboard_hot100_songs = pd.read_csv(
    '/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/billboard_hot100_1958_2026.csv'
)

print(billboard_hot100_songs.shape)
billboard_hot100_songs.head()

(215, 5555)

         date  "Weird Al" Yankovic_web  "Weird Al" Yankovic_youtube  \
0  2004-01-01                        0                            0
1  2004-02-01                       27                            0
2  2004-03-01                        0                            0
3  2004-04-01                       34                            0
4  2004-05-01                       29                            0

   'N Sync_web  'Til Tuesday_web  'Til Tuesday_youtube  10,000 Maniacs_web  \
0            0                 0                     0                  85
1            0                 0                     0                  88
2            0                 0                     0                 100
3            0                 0                     0                  70
4            0                 0                     0                  72

   10,000 Maniacs_youtube  100 Proof Aged in Soul_web  \
0                       0                           0
1                       0                           0
2                       0                           0
3                       0                           0
4                       0                           0

   100 Proof Aged in Soul_youtube  10cc_web  10cc_youtube  112_web  \
0                               0         0             0       54
1                               0        71             0       51
2                               0         0             0       49
3                               0         0             0       42
4                               0        80             0       39

   112_youtube  1910 Fruitgum Co._web  2 Chainz Featuring Drake_web  \
0            0                      0                             0
1            0                      0                             0
2            0                      0                             0
3            0                      0                             0
4            0                      0                             0

   2 Chainz Featuring Drake_youtube  2 Chainz_web  2 Chainz_youtube  \
0                                 0             0                 0
1                                 0             0                 0
2                                 0             0                 0
3                                 0             0                 0
4                                 0             0                 0

   2 In A Room_web  2 In A Room_youtube  2 Unlimited_web  2 Unlimited_youtube  \
0                0                    0                0                    0
1                0                    0                0                    0
2                0                    0                0                    0
3                0                    0                0                    0
4                0                    0                0                    0

   20 Fingers Featuring Gillette_web  21 Savage & Metro Boomin_web  \
0                                  0                             0
1                                  0                             0
2                                  0                             0
3                                  0                             0
4                                  0                             0

   21 Savage & Metro Boomin_youtube  21 Savage_web  21 Savage_youtube  \
0                                 0              0                  0
1                                 0              0                  0
2                                 0              0                  0
3                                 0              0                  0
4                                 0              0                  0

   24kGoldn Featuring iann dior_web  24kGoldn Featuring iann dior_youtube  \
0                                 0                                     0
1                                 0                                     0
2                                 0                                     0
3                                 0                                     0
4                                 0                                     0

   2Pac_web  2Pac_youtube  3 Doors Down_web  3 Doors Down_youtube  \
0        97             0                95                     0
1        86             0                68                     0
2        75             0                61                     0
3        74             0                54                     0
4        73             0                40                     0

   30 Seconds To Mars_web  30 Seconds To Mars_youtube  38 Special_web  \
0                       5                           0               0
1                       6                           0              47
2                       4                           0              75
3                       3                           0              50
4                       5                           0              64

   38 Special_youtube  3LW_web  3LW_youtube  3OH!3_web  3OH!3_youtube  3T_web  \
0                   0      100            0          0              0       0
1                   0       83            0          0              0       0
2                   0       90            0          0              0       0
3                   0       75            0          0              0       0
4                   0       64            0          0              0       0

   3T_youtube  3rd Party_web  3rd Party_youtube  4 Non Blondes_web  \
0           0              0                  0                  0
1           0              0                  0                  0
2           0              0                  0                  0
3           0              0                  0                  0
4           0              0                  0                  0

   4 Non Blondes_youtube  4PM_web  4PM_youtube  5 Seconds Of Summer_web  \
0                      0        0            0                        0
1                      0        0            0                        0
2                      0        0            0                        0
3                      0        0            0                        0
4                      0        0            0                        0

   5 Seconds Of Summer_youtube  50 Cent_web  50 Cent_youtube  69 Boyz_web  \
0                            0           20                0            0
1                            0           21                0            0
2                            0           17                0            0
3                            0           14                0            0
4                            0           14                0            0

   69 Boyz_youtube  6ix9ine_web  6ix9ine_youtube  702_web  702_youtube  \
0                0            0                0       32            0
1                0            0                0       31            0
2                0            0                0       41            0
3                0            0                0        0            0
4                0            0                0       35            0

   95 South_web  95 South_youtube  98 Degrees_web  98 Degrees_youtube  \
0             0                 0             100                   0
1             0                 0              65                   0
2             0                 0              49                   0
3             0                 0              47                   0
4             0                 0              43                   0

   A Boogie Wit da Hoodie_web  A Boogie Wit da Hoodie_youtube  \
0                           0                               0
1                           0                               0
2                           0                               0
3                           0                               0
4                           0                               0

   A Flock Of Seagulls_web  A Flock Of Seagulls_youtube  \
0                      100                            0
1                       52                            0
2                       49                            0
3                       42                            0
4                        0                            0

   A Great Big World & Christina Aguilera_web  \
0                                           0
1                                           0
2                                           0
3                                           0
4                                           0

   A Great Big World & Christina Aguilera_youtube  A Taste Of Honey_web  \
0                                               0                     0
1                                               0                     0
2                                               0                     0
3                                               0                     0
4                                               0                     0

   A Taste Of Honey_youtube  A Tribe Called Quest_web  \
0                         0                         6
1                         0                         8
2                         0                         8
3                         0                         6
4                         0                         6

   A Tribe Called Quest_youtube  \
0                             0
1                             0
2                             0
3                             0
4                             0

   A$AP Rocky Featuring Drake, 2 Chainz & Kendrick Lamar_web  A'me Lorain_web  \
0                                                  0                        0
1                                                  0                        0
2                                                  0                        0
3                                                  0                        0
4                                                  0                        0

   A'me Lorain_youtube  AB Logic_web  AB Logic_youtube  ABBA_web  \
0                    0             0                 0        37
1                    0             0                 0        31
2                    0             0                 0        32
3                    0             0                 0        39
4                    0             0                 0        33

   ABBA_youtube  ABC_web  ABC_youtube  AC/DC_web  AC/DC_youtube  AFI_web  \
0             0       67            0         73              0       48
1             0       64            0         64              0       50
2             0       61            0         75              0       46
3             0       55            0         71              0       40
4             0       62            0         76              0       33

   AFI_youtube  AJR_web  AJR_youtube  AWB_web  AWB_youtube  AWOLNATION_web  \
0            0        0            0        0            0               0
1            0        0            0        0            0               0
2            0        0            0        0            0               0
3            0        0            0        0            0               0
4            0        0            0        0            0               0

   AWOLNATION_youtube  Aaliyah_web  Aaliyah_youtube  Aaron Hall_web  \
0                   0           28                0               0
1                   0           28                0               0
2                   0           27                0               0
3                   0           25                0               0
4                   0           23                0              49

   Aaron Hall_youtube  Aaron Neville_web  Aaron Neville_youtube  \
0                   0                 32                      0
1                   0                 19                      0
2                   0                  0                      0
3                   0                 14                      0
4                   0                 11                      0

   Aaron Tippin_web  Aaron Tippin_youtube  Ace Cannon_web  Ace Cannon_youtube  \
0                 0                     0               0                   0
1                58                     0               0                   0
2                 0                     0               0                   0
3                62                     0               0                   0
4                53                     0               0                   0

   Ace Of Base_web  Ace Of Base_youtube  Adam Ant_web  Adam Ant_youtube  \
0              100                    0            46                 0
1               87                    0            48                 0
2               82                    0            75                 0
3               70                    0            78                 0
4               66                    0            62                 0

   Adam Lambert_web  Adam Lambert_youtube  Adam Wade_web  Adam Wade_youtube  \
0                 0                     0              0                  0
1                 0                     0              0                  0
2                 0                     0              0                  0
3                 0                     0              0                  0
4                 0                     0              0                  0

   Addrisi Brothers_web  Addrisi Brothers_youtube  Adele_web  Adele_youtube  \
0                     0                         0          1              0
1                     0                         0          1              0
2                     0                         0          1              0
3                     0                         0          0              0
4                     0                         0          0              0

   Adina Howard_web  Adina Howard_youtube  Aerosmith_web  Aerosmith_youtube  \
0                39                     0             67                  0
1                31                     0             92                  0
2                46                     0            100                  0
3                96                     0             92                  0
4                86                     0             79                  0

   After 7_web  After 7_youtube  After The Fire_web  After The Fire_youtube  \
0            0                0                   0                       0
1            0                0                   0                       0
2            0                0                 100                       0
3            0                0                   0                       0
4            0                0                   0                       0

   Air Supply_web  Air Supply_youtube  Akon Featuring Eminem_web  \
0              51                   0                          0
1              76                   0                          0
2              51                   0                          0
3              42                   0                          0
4              55                   0                          0

   Akon Featuring Eminem_youtube  Akon Featuring Snoop Dogg_web  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0

   Akon Featuring Snoop Dogg_youtube  Akon Featuring Styles P._youtube  \
0                                  0                                 0
1                                  0                                 0
2                                  0                                 0
3                                  0                                 0
4                                  0                                 0

   Akon_web  Akon_youtube  Al B. Sure!_web  Al B. Sure!_youtube  Al Green_web  \
0         0             0                0                    0            49
1         0             0                0                    0            53
2         1             0                0                    0            46
3         1             0                0                    0            47
4         4             0                0                    0            46

   Al Green_youtube  Al Jarreau_web  Al Jarreau_youtube  Al Martino_web  \
0                 0               0                   0               0
1                 0               2                   0              21
2                 0               0                   0               0
3                 0               3                   0               0
4                 0               0                   0              19

   Al Martino_youtube  Al Stewart_web  Al Stewart_youtube  Al Wilson_web  \
0                   0               0                   0              0
1                   0               0                   0             90
2                   0               0                   0              0
3                   0             100                   0              0
4                   0               0                   0              0

   Al Wilson_youtube  Alabama_web  Alabama_youtube  Alan Jackson_web  \
0                  0           83                0               100
1                  0           73                0                84
2                  0           78                0                65
3                  0           79                0                62
4                  0           74                0                56

   Alan Jackson_youtube  Alan O'Day_web  Alan O'Day_youtube  \
0                     0               0                   0
1                     0               0                   0
2                     0               0                   0
3                     0               0                   0
4                     0               0                   0

   Alanis Morissette_web  Alanis Morissette_youtube  Alannah Myles_web  \
0                     53                          0                  0
1                     50                          0                  0
2                     65                          0                  0
3                     97                          0                  0
4                    100                          0                  0

   Alannah Myles_youtube  Albert Hammond_web  Albert Hammond_youtube  \
0                      0                   0                       0
1                      0                   0                       0
2                      0                   0                       0
3                      0                   0                       0
4                      0                   0                       0

   Alessia Cara_web  Alessia Cara_youtube  Alex Clare_web  Alex Clare_youtube  \
0                 0                     0               0                   0
1                 0                     0               0                   0
2                 0                     0               0                   0
3                 0                     0               0                   0
4                 0                     0               0                   0

   Alexander O'Neal_web  Alexander O'Neal_youtube  Alias_web  Alias_youtube  \
0                     0                         0         60              0
1                     0                         0         41              0
2                     0                         0         59              0
3                     0                         0         67              0

In [69]:
# Find the first charting month and year per song from the week-by-week Billboard data,
# then add it to df_songs as first_charting_month_and_year after first_charting_year.
# Joins on title + performer (lowercased) to handle minor capitalization differences.

import pandas as pd

# Step 1: find first chart_week per title+performer
billboard_hot100_songs['chart_week'] = pd.to_datetime(billboard_hot100_songs['chart_week'])

first_chart_date = (
    billboard_hot100_songs
    .assign(
        _title    = billboard_hot100_songs['title'].str.lower().str.strip(),
        _performer = billboard_hot100_songs['performer'].str.lower().str.strip()
    )
    .groupby(['_title', '_performer'])['chart_week']
    .min()
    .reset_index()
)
first_chart_date['first_charting_month_and_year'] = (
    first_chart_date['chart_week'].dt.strftime('%B %Y')
)

# Step 2: map to df_songs via title + name (both lowercased)
df_songs['_title']     = df_songs['title'].str.lower().str.strip()
df_songs['_performer'] = df_songs['name'].str.lower().str.strip()

df_songs = df_songs.merge(
    first_chart_date[['_title', '_performer', 'first_charting_month_and_year']],
    on=['_title', '_performer'],
    how='left'
).drop(columns=['_title', '_performer'])

# Step 3: move column to after first_charting_year
cols = list(df_songs.columns)
cols.remove('first_charting_month_and_year')
cols.insert(cols.index('first_charting_year') + 1, 'first_charting_month_and_year')
df_songs = df_songs[cols]

print(df_songs['first_charting_month_and_year'].notna().sum(), '/', len(df_songs), 'songs mapped')
print(df_songs[['title', 'name', 'first_charting_year', 'first_charting_month_and_year']].head(5).to_string(index=False))

27350 / 38383 songs mapped
                          title             name  first_charting_year first_charting_month_and_year
           It's All In The Game    tommy edwards                 1958                   August 1958
         It's Only Make Believe    conway twitty                 1958                September 1958
                    Little Star     the elegants                 1958                   August 1958
Nel Blu Dipinto Di Blu (Volaré) domenico modugno                 1958                   August 1958
               Poor Little Fool     ricky nelson                 1958                   August 1958

In [84]:
# Merge Spotify audio feature columns from each artist's first top-20 hit song
# into df_artists, prefixed with 'first_top_20_song_', placed after first_top_20_song_major_genres.
# Primary join: df_songs['musicbrainz_artist_id'] (UUID) ↔ df_artists['musicbrainz_mbid']
# Fallback: name ↔ name

audio_cols = ['duration_ms', 'acousticness', 'danceability', 'energy',
              'instrumentalness', 'liveness', 'loudness', 'speechiness',
              'tempo', 'valence', 'mode', 'explicit']

new_cols = [f'first_top_20_song_{c}' for c in audio_cols]

# Drop any existing versions
df_artists = df_artists.drop(columns=[c for c in new_cols if c in df_artists.columns])

# Step 1: isolate first top-20 hit per artist
first_top20_audio = (
    df_songs[df_songs['peak_pos'] <= 20]
    .sort_values(['musicbrainz_artist_id', 'first_charting_year', 'peak_pos'])
    .drop_duplicates(subset=['musicbrainz_artist_id'], keep='first')
)[['musicbrainz_artist_id', 'name'] + audio_cols]

# Rename audio cols with prefix
first_top20_audio = first_top20_audio.rename(
    columns={c: f'first_top_20_song_{c}' for c in audio_cols}
)

# Step 2: UUID-keyed lookup
uuid_lookup = (
    first_top20_audio.dropna(subset=['musicbrainz_artist_id'])
    .set_index('musicbrainz_artist_id')[new_cols]
)

# Step 3: name-keyed lookup (for fallback)
name_lookup = (
    first_top20_audio.dropna(subset=['name'])
    .drop_duplicates(subset=['name'], keep='first')
    .set_index('name')[new_cols]
)

# Step 4: map via musicbrainz_mbid first, then name fallback
for col in new_cols:
    df_artists[col] = df_artists['musicbrainz_mbid'].map(uuid_lookup[col])

no_match = df_artists[new_cols[0]].isna()
for col in new_cols:
    df_artists.loc[no_match, col] = df_artists.loc[no_match, 'name'].map(name_lookup[col])

# Step 5: reorder — insert all new cols after first_top_20_song_major_genres
cols = list(df_artists.columns)
for c in new_cols:
    cols.remove(c)
insert_at = cols.index('first_top_20_song_major_genres') + 1
for i, c in enumerate(new_cols):
    cols.insert(insert_at + i, c)
df_artists = df_artists[cols]

print(df_artists[new_cols].notna().sum())

first_top_20_song_duration_ms         1628
first_top_20_song_acousticness        1628
first_top_20_song_danceability        1628
first_top_20_song_energy              1628
first_top_20_song_instrumentalness    1628
first_top_20_song_liveness            1628
first_top_20_song_loudness            1628
first_top_20_song_speechiness         1628
first_top_20_song_tempo               1628
first_top_20_song_valence             1628
first_top_20_song_mode                1628
first_top_20_song_explicit            1628
dtype: int64

In [88]:
# Add binary target column 'top_20_hitmaker' to df_artists.
# 1 if the artist had more than 1 top-20 song, 0 if exactly 1, NaN if no top-20 songs.

top20_counts = (
    df_songs[df_songs['peak_pos'] <= 20]
    .groupby('name')
    .size()
    .reset_index(name='_n_top20')
)

df_artists = df_artists.merge(top20_counts, on='name', how='left')
df_artists['top_20_hitmaker'] = df_artists['_n_top20'].apply(
    lambda x: 1 if x > 1 else (0 if x == 1 else None)
)
df_artists = df_artists.drop(columns=['_n_top20'])

print(df_artists['top_20_hitmaker'].value_counts(dropna=False))

top_20_hitmaker
NaN    10396
0.0     1867
1.0     1392
Name: count, dtype: int64

In [90]:
# Count top_20_hitmaker values (1 vs 0) among artists whose first top-20 hit was 2000–2020.

mask = df_artists['first_top_20_hit_year'].between(2000, 2020)
counts = df_artists[mask]['top_20_hitmaker'].value_counts(dropna=False)
total = mask.sum()

for val, n in counts.items():
    label = 'Hitmaker (>1 top-20)' if val == 1 else ('One-hit wonder (1 top-20)' if val == 0 else 'No top-20')
    print(f"{label}: {n} ({100 * n / total:.1f}%)")

One-hit wonder (1 top-20): 454 (56.0%)
Hitmaker (>1 top-20): 347 (42.8%)
No top-20: 10 (1.2%)

In [ ]:
# Rename musicbrainz_artist_id to musicbrainz_artist_mbid in df_songs and save to CSV
df_songs = df_songs.rename(columns={'musicbrainz_artist_id': 'musicbrainz_artist_mbid'})
df_songs.to_csv('/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_songs.csv', index=False)
print(f"Saved {len(df_songs):,} rows")

,title,name,performer_pre_normalized,original_performer_name,original_performer_name_normalized,peak_pos,wks_on_chart,first_charting_year,musicbrainz_artist_id,musicbrainz_recording_mbid,label,major_label,major_label_names,other_label,other_label_names,warner,universal,sony,label_mbid,song_genre_tags_musicbrainz,song_tags_musicbrainz,album_genre_tags_musicbrainz,song_major_genre_category_musicbrainz,album_major_genre_category_musicbrainz,aggregate_major_genre_category_musicbrainz,#_of_genres_song,#_of_genres_aggregate,spotify_id,duration_ms,release_date,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,It's All In The Game,tommy edwards,Tommy Edwards,NaN,NaN,1,22,1958,0b1a0ca5-52cb-4d1d-8344-746f905ae115,7cf06b8f-a898-4f2c-a589-a98af8af6001,['Not Now Music'],False,NaN,True,['Not Now Music'],False,False,False,['b454b444-eb75-46ed-b400-19e85d8e1c64'],NaN,NaN,NaN,NaN,NaN,NaN,0,0,2lmPUdIdzlFH64PWJrw6Zb,159040.0,1/1/94,0.038,0.384,0.276,0.000000,0.309,-13.527,0.0295,105.181,0.654,1.0,3.0,49.0,0.0
1,It's Only Make Believe,conway twitty,Conway Twitty,NaN,NaN,1,21,1958,a3c60d26-90d6-4788-ba9b-a89693fc396d,4123e40f-d667-4634-919d-6e1d77a19934,['Remasters Workshop'],False,NaN,True,['Remasters Workshop'],False,False,False,['e55f5360-a4d0-43a1-b84d-f69b8510f3c6'],NaN,NaN,NaN,NaN,NaN,NaN,0,0,1xVOttVNT27FBTD8iHjOfU,132027.0,1/1/59,0.860,0.461,0.466,0.000028,0.135,-9.627,0.0598,128.537,0.251,1.0,11.0,51.0,0.0
2,Little Star,the elegants,The Elegants,NaN,NaN,1,17,1958,91919ad2-80cb-4077-bbb3-2803fa129fab,e15d4722-47a7-4874-99f6-285529503569,['Club Records'],False,NaN,True,['Club Records'],False,False,False,['9019dc41-f533-4c25-81b1-35fc98531903'],NaN,NaN,NaN,NaN,NaN,NaN,0,0,3c7KT5CN8uYRaK3xThhdYt,162773.0,7/26/05,0.873,0.408,0.397,0.000000,0.280,-12.536,0.0300,72.615,0.697,1.0,9.0,40.0,0.0
3,Nel Blu Dipinto Di Blu (Volaré),domenico modugno,Domenico Modugno,NaN,NaN,1,16,1958,b8e60837-e646-4f18-8f92-27d1173511b0,858ea2b4-7cc8-4a13-aa93-a3a5a73e71fd,['Warner Music Italy'],True,['Warner Music Italy'],False,NaN,True,False,False,['30d5acae-ae46-4689-9a91-99293a55e95e'],NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Poor Little Fool,ricky nelson,Ricky Nelson,NaN,NaN,1,11,1958,28d0c272-4d51-4c24-b31f-e20aac2ba7de,100b7f30-1519-427a-adc2-2b0d6a737db1,['Chartbuster Karaoke'],False,NaN,True,['Chartbuster Karaoke'],False,False,False,['4c44731f-f69b-4bac-b396-064980e894eb'],NaN,NaN,NaN,NaN,NaN,NaN,0,0,1ugZWl7RmEq95dea9hqorZ,153667.0,1/1/90,0.702,0.522,0.227,0.000095,0.238,-16.426,0.0318,155.514,0.839,1.0,0.0,35.0,0.0

In [91]:
# Save cleaned df_artists to CSV
out_path = '/Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv'
df_artists.to_csv(out_path, index=False)
print(f'Saved df_artists: {df_artists.shape}')
print(f'Path: {out_path}')

Saved df_artists: (13655, 44)
Path: /Users/jamesemcnally/Documents/GitHub/spring-2026-hitmakers/df_artists.csv